### ISSUE TITLE
Consider adding additional event types for persistence events such as remove and update. [DATAMONGO-267]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1202]
**[Mark Pollack](https://jira.spring.io/secure/ViewProfile.jspa?name=mark.pollack)** opened **[DATAMONGO-267](https://jira.spring.io/browse/DATAMONGO-267?redirect=false)** and commented

The current event infrastructure does not contain a full set of lifecycle events like those found in hibernate here - http://docs.jboss.org/hibernate/core/3.5/javadoc/org/hibernate/event/AbstractEvent.html

Consider adding some more event types, for example, those related to remove, update

---

**Issue Links:**
- [DATAMONGO-545](https://jira.spring.io/browse/DATAMONGO-545) Add before delete and after delete events for AbstractMongoEventListener

4 votes, 5 watchers

**Comment by christophstrobl** [comment]
Declined following the argumentation in [spring-projects/spring-data-commons/issues/2084](https://github.com/spring-projects/spring-data-commons/issues/2084)
