### ISSUE TITLE
Spring Data Mongodb performance compared to plain MongoDB driver [DATAMONGO-520]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1451]
**[Ilya Skorik](https://jira.spring.io/secure/ViewProfile.jspa?name=ilyaskorik)** opened **[DATAMONGO-520](https://jira.spring.io/browse/DATAMONGO-520?redirect=false)** and commented

Very slow running queries, 10-30 times slower than the native. Details in the discussion on the link to Mongo-db-driver JIRA. I want to understand what my error or a bug in Spring-data

---

**Affects:** 1.1 GA

**Reference URL:** https://jira.mongodb.org/browse/JAVA-631

**Attachments:**
- [database.zip](https://jira.spring.io/secure/attachment/20397/database.zip) (_65.11 kB_)
- [LoginForm.java](https://jira.spring.io/secure/attachment/20395/LoginForm.java) (_3.04 kB_)
- [LoginForm.java](https://jira.spring.io/secure/attachment/20392/LoginForm.java) (_2.53 kB_)
- [LoginForm.java](https://jira.spring.io/secure/attachment/20391/LoginForm.java) (_2.07 kB_)
- [MongoConfig.java](https://jira.spring.io/secure/attachment/20390/MongoConfig.java) (_1.35 kB_)
- [zr-matrix-test.zip](https://jira.spring.io/secure/attachment/20399/zr-matrix-test.zip) (_49.12 kB_)
- [zr-matrix-test.zip](https://jira.spring.io/secure/attachment/20396/zr-matrix-test.zip) (_66.17 kB_)

**Comment by kain64** [comment]
lol issue still exist.. why exist this tracker if answers are : ask on forum... real performance issue still exist ..
