### ISSUE TITLE
Spring Data for MongoDb doesn't save null values when @Version is added to domain class  [DATAMONGO-571]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1502]
**[Patryk Hajduk](https://jira.spring.io/secure/ViewProfile.jspa?name=exo)** opened **[DATAMONGO-571](https://jira.spring.io/browse/DATAMONGO-571?redirect=false)** and commented

Scenario:

1. Domain class is loaded from mongodb using `CrudRepository.findOne(…)` method.
2. The loaded instance’s any non `id` nor `@Version` annotated field is set to `null`.
3. The loaded instance is saved to same mongodb using `CrudRepository.save(…)` method.
4. The field that has been set to `null` doesn’t write to database, it’s unchanged.

Important: The problem doesn’t occur when `@Version` annotation is not used in the domain class definition

---

**Affects:** 1.1.1

**Attachments:**
- [mylyn-context.zip](https://jira.spring.io/secure/attachment/21154/mylyn-context.zip) (_90.75 kB_)

1 votes, 5 watchers

**Comment by odrotbohm** [comment]
This is a pretty dated ticket. Feel free to open a new one if you can reproduce the described issue on recent version of Spring Data MongoDB.
