### ISSUE TITLE
Expose new QueryDSL elemMatch feature [DATAMONGO-595]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1524]
**[Raman Gupta](https://jira.spring.io/secure/ViewProfile.jspa?name=raman)** opened **[DATAMONGO-595](https://jira.spring.io/browse/DATAMONGO-595?redirect=false)** and commented

QueryDSL, as of version 2.5.0, supports building queries with the MongoDB $elemMatch operator:

https://github.com/mysema/querydsl/issues/115

This functionality is available from MongodbQuery using the builder returned by the new method anyEmbedded. However, I don't see any way to access this functionality via QueryDslMongoRepository.

See also: https://github.com/mysema/querydsl/issues/324

---

**Affects:** 1.1.1

**Issue Links:**
- [DATAMONGO-1848](https://jira.spring.io/browse/DATAMONGO-1848) Migrate to Document API-based Querydsl implementation

3 votes, 6 watchers

**Comment by Eitraz** [comment]
As I spent some time searching the web for a solution to fit my needs I just want to share how I (miss)-use the elemMatch functionality.

I came up with this util method:

```java
public static <D, Q extends SimpleExpression<D>> PredicateOperation elemMatch(@NonNull ListPath<D, Q> path,
                                                                              @NonNull Q queryDocument,
                                                                              @NonNull List<Function<Q, Predicate>> predicates) {
    return ExpressionUtils.predicate(
            MongodbOps.ELEM_MATCH,
            path.any(),
            ExpressionUtils.allOf(predicates
                    .stream()
                    .map(predicate -> predicate.apply(queryDocument))
                    .toList())
    );
}
```

That I use in the following way when building predicates:

```java
personRepository.findAll(
        QPerson.person.name.eq("Luke")
                .and(elemMatch(
                        QPerson.person.shippingAddresses,
                        QAddress.address,
                        List.of(
                                address -> address.planet.eq("Tatooine"),
                                address -> address.planet.region.eq("Outer Rim")
                        )
                ))
);
```

I hope it can help someone with the same problem :) 

Regards,
Petter
