### ISSUE TITLE
Unable to save Map<String, ?> when one of it's keys starts with dollar sign [DATAMONGO-604]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1533]
**[Siarhei Krukau](https://jira.spring.io/secure/ViewProfile.jspa?name=madhead)** opened **[DATAMONGO-604](https://jira.spring.io/browse/DATAMONGO-604?redirect=false)** and commented

MongoDB cannot store JSON keys, starting from "$". So, when we try to save a Map with a $-starting key, mongo fails with:

```
fields stored in the db can't start with '$' (Bad Key: '$key')
```

My current workaround is to extend `org.springframework.data.mongodb.core.convert.MappingMongoConverter` and override `potentiallyEscapeMapKey(String)`. Maybe this is good to be in master?

---

**Affects:** 1.1 GA

**Reference URL:** https://groups.google.com/forum/?fromgroups#!topic/mongodb-user/5UQYAQ6o5Wg

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/20928/demo.zip) (_3.78 kB_)

3 votes, 4 watchers

**Comment by christophstrobl** [comment]
The current hooks (`potentiallyConvertMapKey` & `potentiallyUnescapeMapKey`) in place seem to be sufficient.
