### ISSUE TITLE
Add a register multiple converters example with Java to the Spring Data MongoDB reference docs. [DATAMONGO-733]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1666]
**[Drag](https://jira.spring.io/secure/ViewProfile.jspa?name=dragenesis)** opened **[DATAMONGO-733](https://jira.spring.io/browse/DATAMONGO-733?redirect=false)** and commented

In the reference documentation for Spring Data MongoDB, there is an example of registering custom converters with MongoConverter to be used with MongoTemplate.  However, unlike other sections, there is only an example for doing it in XML.  Please add examples of how you would register one or more converters with MongoConverter using Java into the documentation

---

**Reference URL:** http://static.springsource.org/spring-data/data-mongodb/docs/current/reference/html/mongo.core.html#mongo.custom-converters

**Comment by christophstrobl** [comment]
covered via [Registering Spring Converters with the MongoConverter](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.custom-converters.xml)
