### ISSUE TITLE
Simple annotation processor for models annotated with @Document [DATAMONGO-744]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1677]
**[Paweł Mendelski](https://jira.spring.io/secure/ViewProfile.jspa?name=mendlik)** opened **[DATAMONGO-744](https://jira.spring.io/browse/DATAMONGO-744?redirect=false)** and commented

I would like to propose a new feature: simple annotation processor for models annotated with `@Document`.
Let's call it: **`spring-data-mongodb-processor`**.

This annotation preprocessor should be reposnsible for (and only for) generating meta model for all classes annotated with `@Document`. This way we could create type safe queries with spring-data-mongodb.

Why QueryDSL for MongoDB is not sufficient?
- QueryDSL can be used only in queries. What about updating and deleting data?
- QueryDSL comes with a bunch of dependencies. Do we really need them? Our need is simple - just generate meta model in order to replace string queries.
- In application that uses spring-data-mongodb, QueryDSL is a kind of a second (duplicated) way of querying data. I know that QueryDSL predicates are quite handy but I would like all project queries to use the same mechanism. Moreover sytax used in pure spring-data-mongodb is much more similar to MongoDB shell syntax.
- How can I use QueryDSL mechanism with plain MonogoTemplate?
- QueryDSL have some minor problems with querying arrays of nested documents in QueryDSL. For example it's impossible to create such a query: `db.inventory.find( { 'memos.0.by': 'shipping' } )` (see MongoDB doc: [match-a-field-in-the-subdocument-using-the-array-index](http://docs.mongodb.org/manual/tutorial/query-documents/#match-a-field-in-the-subdocument-using-the-array-index))

Maybe some of these arguments come from my lack of knowledge. Maybe I didn't study the documentation as hard as I should. If I am wrong please correct me.

For my current project I created a simple annotation processor which does what I expect it to do. Feel free to use it, change it, love it or hate it. Github: https://github.com/mendlik/spring-data-mongodb-processor

---

**Reference URL:** https://github.com/mendlik/spring-data-mongodb-processor

**Comment by christophstrobl** [comment]
There has been literally no movement in the past years so for now at least I think we can close this issue as it's unlikely to happen.
