### ISSUE TITLE
String @Query with @DBref field [DATAMONGO-748]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1681]
**[Matej Zachar](https://jira.spring.io/secure/ViewProfile.jspa?name=mzachar)** opened **[DATAMONGO-748](https://jira.spring.io/browse/DATAMONGO-748?redirect=false)** and commented

It nice that you can do query by method name for `@DBRef` fields e.g.:

```
@Document
public class Person {

   @Id
   private ObjectId id;

   @DBRef
   private Address address;

   ...
}
```

```
public List<Person> findAllByAddress(Address address);
```

However if you want to accomplish the same using custom query inside `@Query` annotation you have to use the address ObjectId e.g.:

```
@Query("{address.$id: ?0}")
pulic List<Person> custom(ObjectId addressId);
```

It would be nice to use Address object directly instead of its id:

```
@Query("{address: ?0}")
pulic List<Person> custom(Address address);
```

probably implementation easier solution could be:

```
@Query("{address.$id: ?0}")
public List<Person> custom(Address address);
```

---

**Affects:** 1.2.3

**Comment by christophstrobl** [comment]
With string based queries the control is up to the user
