### ISSUE TITLE
Repository - findBy<Field>IgnoreCase doesnt work [DATAMONGO-770]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1700]
**[regis](https://jira.spring.io/secure/ViewProfile.jspa?name=regis.leray)** opened **[DATAMONGO-770](https://jira.spring.io/browse/DATAMONGO-770?redirect=false)** and commented

I create a simple user document with an email field,

```java
 
@Document(collection = "user")
public class UserDocument {

    @Id
    private ObjectId id;

    private String status;
    private String firstname;
    private String lastname;

    @Indexed(unique = true)
    private String email;

   all getter/ setter provided

}
```

 

Here my repository

```java
 
public interface UserRepository extends CrudRepository<UserDocument, ObjectId>, QueryDslPredicateExecutor<UserDocument> {
    UserDocument findByEmailIgnoreCase(String email);

}
```

 

its working - i find a user document with

```java
 
UserDocument foundUser = repository.findByEmailIgnoreCase("test@test.com");
```

 

its NOT working - i dont find a user document with

```java
UserDocument foundUser = repository.findByEmailIgnoreCase("Test@Test.com");
```

 

I also try with the firstname it also doesnt work

Here my logs

```
 
DEBUG o.s.d.m.c.MongoTemplate - findOne using query: { "email" : "Test@Test.Com"} in db.collection: portfolio_test.user
```

 

I m using spring-data-mongodb 1.3.1
mongodb 2.4.6
open jdk 7

I try to debug but it is in spring-data-common where it is handle the findBy stragegy lookup

PS: right now im using Query DSL to handle this

```java
 
QUserDocument userDocument = new QUserDocument("userdocument");
return userRepository.findOne(userDocument.email.equalsIgnoreCase(email));
```

 

---

**Affects:** 1.3 GA, 1.3.1

**Referenced from:** commits https://github.com/spring-projects/spring-data-mongodb/commit/e8a303b6eda89e74db9781b2e1f359681f137d1d, https://github.com/spring-projects/spring-data-mongodb/commit/fe41202f96ca054cbfdc5ee611eb3bc7f78a41ea

**Comment by ps-tunnelsoft** [comment]
> **[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** commented
> 
> `IgnoreCase` is currently not supported at all. We're going to include that in the first milestone of the upcoming release train Codd

I could not find the IgnoreCase query keyword in the documentation and I wonder what happened with this feature request in the milestone

**Comment by christophstrobl** [comment]
@ps-tunnelsoft the _Codd_ release train has reached EOL already quite some time ago. You can find supported keywords (may vary depending on the store implementation) in the [appendix](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#appendix.query.method.predicate).

**Comment by ps-tunnelsoft** [comment]
@christophstrobl I just tested it and IgnoreCase keyword works but it isn't in the list of supported keywords

**Comment by christophstrobl** [comment]
I see - it's missing in the `Query Methods` section of the reference documentation. Created #3916 for this. Thanks!
