### ISSUE TITLE
Allow @DbRef only on properties that represent a persistent entity type. [DATAMONGO-815]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1743]
**[Thomas Darimont](https://jira.spring.io/secure/ViewProfile.jspa?name=thomasd)** opened **[DATAMONGO-815](https://jira.spring.io/browse/DATAMONGO-815?redirect=false)** and commented

We should not allow `@DbRef` on properties that are of a wrapper or primitive type

---
No further details from [DATAMONGO-815](https://jira.spring.io/browse/DATAMONGO-815?redirect=false)

**Comment by christophstrobl** [comment]
At this point I don't think we're going to pick this issue up in the future.
