### ISSUE TITLE
Clean up QueryMapper and UpdateMapper [DATAMONGO-836]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1764]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-836](https://jira.spring.io/browse/DATAMONGO-836?redirect=false)** and commented

Currently `UpdateMapper` extends `QueryMapper` to use some of the functions provided in `QueryMapper`. Though both mappers do not have that much in common. `UpdateMapper` does not have to know about keywords like `$in` or `$or` as those are specific to `Query` and are not used in `Update`.

Split classes and extract a common base to be used in both.

---
No further details from [DATAMONGO-836](https://jira.spring.io/browse/DATAMONGO-836?redirect=false)

**Comment by christophstrobl** [comment]
Closing this one as it's an ongoing task that.
