### ISSUE TITLE
MongoTemplate mapReduce void returning functions should be added [DATAMONGO-864]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1792]
**[bertrand zanni](https://jira.spring.io/secure/ViewProfile.jspa?name=bzanni)** opened **[DATAMONGO-864](https://jira.spring.io/browse/DATAMONGO-864?redirect=false)** and commented

every MongoTemplate mapReduce functions like:
\<T> MapReduceResults\<T>	mapReduce(...)
should have a duplicate like:
\<T> void	mapReduce(...)

Indeed, long running mapreduce jobs are not permitted because result is sent to java List<> and provoke OutOfMemoryExceptions

---
No further details from [DATAMONGO-864](https://jira.spring.io/browse/DATAMONGO-864?redirect=false)

**Comment by christophstrobl** [comment]
map reduce has been deprecated by MongoDB
