### ISSUE TITLE
ReadPreference and WriteConcern at collection and operation level. [DATAMONGO-902]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1827]
**[Poorna Subhash](https://jira.spring.io/secure/ViewProfile.jspa?name=poornasubhash)** opened **[DATAMONGO-902](https://jira.spring.io/browse/DATAMONGO-902?redirect=false)** and commented

currently the framework supports ReadPreference and WriteConcern only at MongoTemplate. However, MongoDB supports these settings at collection and operation level.  
The brief usecase for this requirement is written at http://stackoverflow.com/questions/16731597/spring-mongodb-read-preference-at-operation-level .

Here are my thoughts.
Collection level preferences may be implemented using some sort of annotation/extending `@Document` annotation and then change prepareCollection() method of MongoTemplate.

Operation level preference may require addition additional overloaded methods to MongoOperations interface and Repository interfaces.

---

3 votes, 4 watchers

**Comment by christophstrobl** [comment]
resolved via #4288
