### ISSUE TITLE
Provide ReadPreferenceResolver similar to WriteConcernResolver [DATAMONGO-947]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1856]
**[Alexej Kubarev](https://jira.spring.io/secure/ViewProfile.jspa?name=alexejk)** opened **[DATAMONGO-947](https://jira.spring.io/browse/DATAMONGO-947?redirect=false)** and commented

In some applications it's required to change the readPreference for one or more repository (and keep it distinct from a default ReadPreference set on MongoTemplate).

A mechanism similar to WriteConcernResolver would make this very flexible and achieve this functionality.

Currently there are two workarounds which are not very clean:
1. Creating repository in question with a different MongoTemplate (does not allow per-action preferences changes)
2. Subclassing MongoTemplate and hooking in desired functionality there

---

**Affects:** 1.5 GA (Dijkstra)

**Comment by christophstrobl** [comment]
Resolved via: #4288
