### ISSUE TITLE
Annotation @CreatedDate isn't working, when ID is assigned manually [DATAMONGO-946]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1872]
**[Sebastian Scheele](https://jira.spring.io/secure/ViewProfile.jspa?name=sebastian)** opened **[DATAMONGO-946](https://jira.spring.io/browse/DATAMONGO-946?redirect=false)** and commented

When I assign the ID in the constructor manually, the annotation `@CreatedDate` is not working. The reason is, that in class `IsNewAwareAuditingHandler` the `strategy.isNew(object)` is `false` and so directly at creation time the `markModified(object);` is executed instead of `markCreated(object);`.

I test it with the https://github.com/spring-guides/gs-accessing-data-mongodb.git example and change it like this:

```java
public class Customer {

	@Id
	private String id;

	@CreatedDate
	private DateTime createdDate;
	private String firstName;
	private String lastName;

	public Customer() {
		this.id = UUID.randomUUID().toString();
	}

	public Customer(String firstName, String lastName) {
		this.id = UUID.randomUUID().toString();
		this.firstName = firstName;
		this.lastName = lastName;
	}
	…
}
```

---

**Affects:** 1.5 GA (Dijkstra)

0 votes, 5 watchers

**Comment by mjustin** [comment]
> The implementation of that resolution can be found in IsNewStrategyFactorySupport (Persistable trumps everything) and the fallback MappingContextIsNewStrategyFactory that will inspect the persistence metadata

As of https://github.com/spring-projects/spring-data-commons/issues/1771 implemented in 2018, this is now implemented in [`BasicPersistentEntity`](https://github.com/spring-projects/spring-data-commons/blob/8bd2f9bf3452b6d168b082a36ac59a28bd1ff888/src/main/java/org/springframework/data/mapping/model/BasicPersistentEntity.java#L121), which delegates to either [`PersistableIsNewStrategy`](https://github.com/spring-projects/spring-data-commons/blob/8bd2f9bf3452b6d168b082a36ac59a28bd1ff888/src/main/java/org/springframework/data/support/PersistableIsNewStrategy.java) or [`PersistentEntityIsNewStrategy`](https://github.com/spring-projects/spring-data-commons/blob/8bd2f9bf3452b6d168b082a36ac59a28bd1ff888/src/main/java/org/springframework/data/mapping/model/PersistentEntityIsNewStrategy.java), depending on whether the entity implements `Persistable`:

```java
		this.isNewStrategy = Lazy.of(() -> Persistable.class.isAssignableFrom(information.getType()) //
				? PersistableIsNewStrategy.INSTANCE
				: getFallbackIsNewStrategy());
```
