### ISSUE TITLE
methods in AbstractMongoConfiguration should have implementations [DATAMONGO-1000]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1926]
**[Christopher Smith](https://jira.spring.io/secure/ViewProfile.jspa?name=w_c_smith)** opened **[DATAMONGO-1000](https://jira.spring.io/browse/DATAMONGO-1000?redirect=false)** and commented

The `AbstractMongoConfiguration` handles several related but distinct concerns, including creating a `Mongo` object, pulling that up into a `MongoDbFactory`, and registering the appropriate converters, mapping context, and template.

In my application, I need to register custom type converters, and I'm using Spring Cloud to autodiscover the MongoDB provider at runtime. Spring Cloud's service adapter injects a `MongoDbFactory`. The most obvious integration point is to extend `AbstractMongoConfiguration` and override `mongoDbFactory()`.

Since the abstract methods in `AbstractMongoConfiguration` are called **only** from the `mongoDbFactory()` method, there's no need for supplying implementations for them, and the restriction that they return `null` is unnecessary when it's overridden

---

**Affects:** 1.6 M1 (Evans)

**Reference URL:** https://github.com/spring-projects/spring-cloud/tree/master/spring-cloud-spring-service-connector

**Comment by christophstrobl** [comment]
Resolved via #557
