### ISSUE TITLE
Enhance exception for better understanding [DATAMONGO-1014]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1938]
**[Assaf](https://jira.spring.io/secure/ViewProfile.jspa?name=checklist)** opened **[DATAMONGO-1014](https://jira.spring.io/browse/DATAMONGO-1014?redirect=false)** and commented

Hi,

Please see the reference URL for an issue I am having. I wanted to suggest that you update the code with clearer info for the developers. Right now I see on my error log a lot of these issues but have no idea where they are originating. Something like the following would be helpful:

```
LOG.warn("Customizing field name for id property not allowed! Custom name will not be considered! Owner:" + owner.toString() + ":Field:" + field.toString());
```

---

**Affects:** 1.5.2 (Dijkstra SR2)

**Reference URL:** http://stackoverflow.com/questions/25118286/spring-mongo-exception-customizing-field-name-for-id-property-not-allowed-cus

1 votes, 2 watchers

**Comment by christophstrobl** [comment]
Resolved via #830
