### ISSUE TITLE
JOURNAL_SAFE  has been superseded by JOURNALED [DATAMONGO-1047]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1969]
**[Titi Wangsa](https://jira.spring.io/secure/ViewProfile.jspa?name=blacksnow666)** opened **[DATAMONGO-1047](https://jira.spring.io/browse/DATAMONGO-1047?redirect=false)** and commented

xml setting mongo:db-factory supports the "write-concern" attribute. This attribute supports "JOURNAL_SAFE" value but not "JOURNALED".

actual:
when i do ctrl+space on the write-concern attribute, i do not see "JOURNALED".

expected
when i do ctrl+space on the write-concern attribute, i want to see "JOURNALED".

---
No further details from [DATAMONGO-1047](https://jira.spring.io/browse/DATAMONGO-1047?redirect=false)

**Comment by christophstrobl** [comment]
Resolved via #823
