### ISSUE TITLE
Conversion of BSONTimstamp should not happen [DATAMONGO-1059]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1980]
**[John Butler](https://jira.spring.io/secure/ViewProfile.jspa?name=dancerjohn)** opened **[DATAMONGO-1059](https://jira.spring.io/browse/DATAMONGO-1059?redirect=false)** and commented

I have code that takes advantage of MongoDB's capability to assign the value of a BSONTimestamp server-side. This is done by inserting a DBObject whose first field is a "new BSONTimestamp()". However, Spring Data is not recognizing that BSONTimestamp is a MongoDB-specific class and is converting it to a BasicDBObject. This is file for the cases where this value is populated client-side but breaks when it is populated server-side.

Please see the "Timestamps" section of http://docs.mongodb.org/manual/reference/bson-types/

---
No further details from [DATAMONGO-1059](https://jira.spring.io/browse/DATAMONGO-1059?redirect=false)

**Comment by christophstrobl** [comment]
resolved via #579
