### ISSUE TITLE
ReadPreference not applied consistently in concurrent usage of MongoTemplate [DATAMONGO-1061]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1982]
**[Bogdan Apetrei](https://jira.spring.io/secure/ViewProfile.jspa?name=bogdan.apetrei)** opened **[DATAMONGO-1061](https://jira.spring.io/browse/DATAMONGO-1061?redirect=false)** and commented

In the scenario when we have one mongodb factory used by two mongo templates defined as below:

```
          <bean id="mongoTemplateReadFromPrimary" class="org.springframework.data.mongodb.core.MongoTemplate">
              <constructor-arg name="mongoDbFactory" ref="mongoDbFactory" />
          </bean>

          <bean id="mongoTemplateReadFromSecondary" class="org.springframework.data.mongodb.core.MongoTemplate">
              <constructor-arg name="mongoDbFactory" ref="mongoDbFactory" />
              <property name="readPreference" value="SECONDARY" />
          </bean>
```

    operations using mongoTemplateReadFromPrimary will be executed also on secondaries.
    
    This can cause unreliable reads since there is a small delay in the replication process.
    
    This behaviour comes in contradiction with:
    
    - MongoDB documentation:
    
        "By default, an application directs its read operations to the primary member in a replica set.
        Reading from the primary guarantees that read operations reflect the latest version of a document."
    
    - Behaviour when only one mongoTemplate is used, when all reads go to primary
    
    - Spring Data MongoDB documentation, where the need to explicitly specify the readPreference is not documented.
        (at least I was not able to find it)
    
    Problem is hard to identify when the application is highly concurrent. (concurrency was excluded from test scenarios)
    
    I attached the project I used for the test scenarios. You can find there both the java code but also the docker files
    and the code used to create the mongod, mongos and mongo config servers

---

**Attachments:**
- [MongoDB-Docker-dev (1).zip](https://jira.spring.io/secure/attachment/22353/MongoDB-Docker-dev+%281%29.zip) (_13.32 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/386

**Comment by mp911de** [comment]
Fixed via #4286.
