### ISSUE TITLE
Allow usage of java.util.Optional as field type in domain types [DATAMONGO-1083]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2003]
**[Ben Romberg](https://jira.spring.io/secure/ViewProfile.jspa?name=benromberg)** opened **[DATAMONGO-1083](https://jira.spring.io/browse/DATAMONGO-1083?redirect=false)** and commented

Using Optional works, but a separate JSON Object with a "value" field is created, as there seems to be no special case handling Optionals. Also, I doubt it's possible to implement this using a GenericConverter, as it doesn't support to introspect the generic type of the Optional.

Consider the following Entity:

public class Entity {
private String id;
private Optional\<String> email;
}

Expected outcome when persisting into Mongo:
{
"_id": "...",
"email": "..."
}

Actual outcome:
{
"_id": "...",
"email": {
"value": "..."
}
}

---

**Affects:** 1.6.1 (Evans SR1)

1 votes, 3 watchers

**Comment by kefi7** [comment]
It sure is a pretty convenient option to have, albeit the lack of the specific programming construct (yet). Something similar along the lines of [@Basic(optional=true)](https://stackoverflow.com/questions/19098541/jpa-optional-columns), but it's intention is entirely different.
