### ISSUE TITLE
Allow MongoCredentials (CR or GSSAPI) in MongoFactoryBean (iso MongoDbFactoryBean). [DATAMONGO-1091]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2010]
**[Geert Pante](https://jira.spring.io/secure/ViewProfile.jspa?name=greyfairer)** opened **[DATAMONGO-1091](https://jira.spring.io/browse/DATAMONGO-1091?redirect=false)** and commented

Since mongo-java-driver 2.11, the preferred (documented) way to authenticate in MongoDB is to pass credentials to the MongoClient, independent of the database. When creating a connection, MongoDB will first authenticate using the given credentials before connecting to any database. See http://docs.mongodb.org/ecosystem/tutorial/authenticate-with-java-driver/, introduced by https://jira.mongodb.org/browse/JAVA-691

```
MongoCredential credential = MongoCredential.createMongoCRCredential(userName, authDb, password.toCharArray());
MongoClient mongoClient = new MongoClient(new ServerAddress(server), Arrays.asList(credential));
```

This obsoletes the repeated usage of client credentials for multiple databases, i.e. per db-factory. This also obsoletes the usage of an authentication-dbname, since the authentication database is in the credentials, not in the database factory.

Possibly, you could also support GSSAPI credentials (MongoDB enterprise)

```
MongoCredential credential = MongoCredential.createGSSAPICredential(userName);
MongoClient mongoClient = new MongoClient(new ServerAddress(server), Arrays.asList(credential));
```

---

2 votes, 3 watchers

**Comment by christophstrobl** [comment]
Resolved via #273
