### ISSUE TITLE
Support for saving of Null values for a property [DATAMONGO-1107]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2024]
**[Alexej Kubarev](https://jira.spring.io/secure/ViewProfile.jspa?name=alexejk)** opened **[DATAMONGO-1107](https://jira.spring.io/browse/DATAMONGO-1107?redirect=false)** and commented

Currently it is not possible to save null-values for properties of an entity.
For example if trying to save an object Person that looks like below:

```
@Data
class Person {
    @Id
    private ObjectId id;
    private ObjectId parentId;
    private String name;
}
```

With only name set, it's natural that id is auto-created later, but in some cases it's desired to save `parentId: null` explicitly.
Today, saving this object would result in

```
{
   _id: ObjectId("......."),
   _class: "....Person",
   name: "some name"
}
```

I can understand the reasoning as Java does not really differentiate between null and undefined but this may cause problems in interoperability between different systems that work on the same data (i know, opening a Pandora's Box here).

If a system that created a person object in a DB was using another language or native driver, it would be possible to create entries with explicit `parentId` property set to `null`. If our system, however can also create Person, then we would never be able to achieve this simple with a `MongoRepository.save(Entity s);` method. So on both system we would have to query for something like findByParentIdNotExistsOrIsNull().

Generally todays behavior seems appropriate, but it would be helpful if we can have some way of saying that this value is nullable and thus should be explicitly saves as null. Maybe a `@Nullable` annotation on a field?.

It was also pointed out that it's possible to work around this by having an event listener for the `AfterConvertEvent` and explicitly set this value to null if needed on the entity as MongoDB driver supports saving null values

---

**Affects:** 1.6.1 (Evans SR1)

**Attachments:**
- [image-2019-04-09-21-37-11-690.png](https://jira.spring.io/secure/attachment/26204/image-2019-04-09-21-37-11-690.png) (_49.16 kB_)

5 votes, 5 watchers

**Comment by christophstrobl** [comment]
Resolved by #3407
