### ISSUE TITLE
Ignore mapReduce results when output type is not inline [DATAMONGO-1109]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2026]
**[oregek](https://jira.spring.io/secure/ViewProfile.jspa?name=oregek)** opened **[DATAMONGO-1109](https://jira.spring.io/browse/DATAMONGO-1109?redirect=false)** and commented

We use mongo template for mapReduce with 'reduce'  and 'merge'  output.
But for both types template is quering the collection for results. We have thousands of large documents there. So it leads to OutOfMemoryException in application.

Here a patch we use to avoid the error.
https://gist.github.com/ol-loginov/d1103eb74e205c7735ad

It'd be great if you integrate this solution or provide other mechanism to skip results for output other than 'inline'

---

**Affects:** 1.3.2 (Babbage SR1)

1 votes, 2 watchers

**Comment by christophstrobl** [comment]
MapReduce has been deprecated by MongoDB
