### ISSUE TITLE
Add repository support via annotations for calling server side scripts. [DATAMONGO-1112]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2029]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1112](https://jira.spring.io/browse/DATAMONGO-1112?redirect=false)** and commented

---

**Issue Links:**
- [DATAMONGO-479](https://jira.spring.io/browse/DATAMONGO-479) Support calling of MongoDB stored javascripts
 (_**"depends on"**_)

**Comment by christophstrobl** [comment]
Running serverside scripts has been deprecated by mongodb
