### ISSUE TITLE
Support addition GeoJSON classes for queries [DATAMONGO-1114]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2031]
**[Lieven Doclo](https://jira.spring.io/secure/ViewProfile.jspa?name=lievendoclo)** opened **[DATAMONGO-1114](https://jira.spring.io/browse/DATAMONGO-1114?redirect=false)** and commented

According to the MongoDB documentation, it supports a lot of GeoJSON geometries currently not supported by Spring Data for MongoDB. See: http://docs.mongodb.org/manual/core/2dsphere/

Provide additional support for MultiPolygon, Polygon with inner rings, MultiPoint, LineString, MultiLineString and GeometryCollection

---

2 votes, 3 watchers

**Comment by christophstrobl** [comment]
resolved via #2052
