### ISSUE TITLE
Add means to disable sub-document indexes [DATAMONGO-1168]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2087]
**[Christian Kleinhuis](https://jira.spring.io/secure/ViewProfile.jspa?name=ck)** opened **[DATAMONGO-1168](https://jira.spring.io/browse/DATAMONGO-1168?redirect=false)** and commented

I feel a little helpless so i try it to post it directly here in your precious JIRA. I wanted to update to a more current version of Spring Data MongoDB we where using v1.4.0.RC1 in our project, this project makes heavy use of sub-documents, to persist snapshots of the store system we build and now with any version higher than 1.5 (where the feature was introduced) we get those "duplicate key " errors, which absolutely make no sense. What is the strategy to disable the sub-indexing?

---

**Affects:** 1.7 GA (Fowler)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by christophstrobl** [comment]
Though the annotation based index model comes in handy we do recommend defining indexes via the dedicated API.
We currently do not plan to alter the existing behaviour and removing the superfluous  annotation on the `_id` field seems to have solved the problem.
