### ISSUE TITLE
Remove deprecated configuration options. [DATAMONGO-1177]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2096]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1177](https://jira.spring.io/browse/DATAMONGO-1177?redirect=false)** and commented

* Remove reflective invokers introduced in _Fowler_.
* Remove mongo element from xsd
* Remove Factory beans for `Mongo` and `MongoOptions`

---
No further details from [DATAMONGO-1177](https://jira.spring.io/browse/DATAMONGO-1177?redirect=false)

**Comment by christophstrobl** [comment]
done for 3.x
