### ISSUE TITLE
Avoid data write loss while primary node is down [DATAMONGO-1215]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2131]
**[Mohamed Kamal Hasan](https://jira.spring.io/secure/ViewProfile.jspa?name=mohamed.hasanh)** opened **[DATAMONGO-1215](https://jira.spring.io/browse/DATAMONGO-1215?redirect=false)** and commented

Hi,

I have configured MongoDB replica set with  3 or 4 nodes and using spring data mongo framework as my ORM.
Mongo Server takes some amount of time to choose secondary as primary while primary goes down. In this span of time, my application loses its write request and getting error message from Mongo Server.

Is there any solution to avoid this issue.

Thanks in Advance!

---
No further details from [DATAMONGO-1215](https://jira.spring.io/browse/DATAMONGO-1215?redirect=false)

**Comment by christophstrobl** [comment]
That's what Spring Retry may handle.
