### ISSUE TITLE
Add support for $slice to find operations. [DATAMONGO-1230]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2145]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1230](https://jira.spring.io/browse/DATAMONGO-1230?redirect=false)** and commented

`$slice` allows to limit the numer of elements returned from an array attribute.

```javascript
// return only the first 5 elements in comments array
db.posts.find( {}, { comments: { $slice: 5 } } )
```

---

**Reference URL:** http://docs.mongodb.org/manual/reference/operator/projection/slice/

1 votes, 2 watchers

**Comment by christophstrobl** [comment]
This works already in current _main_ development line. 

```java
Query query = Query.query(Criteria.where(...));
query.fields().slice("comments", 5);
```
