### ISSUE TITLE
Add $update support to MongoRespository (@Query  annotation) [DATAMONGO-1253]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2170]
**[John Mark](https://jira.spring.io/secure/ViewProfile.jspa?name=springiscool)** opened **[DATAMONGO-1253](https://jira.spring.io/browse/DATAMONGO-1253?redirect=false)** and commented

It would be great if the `MongoRepository` supported the [`$update` operation](http://docs.mongodb.org/manual/tutorial/modify-documents/#Updating-ModifierOperations) to enable updating parts of a document.  Right now the only way to do this with Spring Data MongoDB is to write code using a `MongoTemplate`

---
No further details from [DATAMONGO-1253](https://jira.spring.io/browse/DATAMONGO-1253?redirect=false)

**Comment by christophstrobl** [comment]
implemented via #284.
