### ISSUE TITLE
A check before using loging in method getPersistentId of class MongoChangeSetPersister.java is needed [DATAMONGO-1277]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2195]
**[Oleksandr Vengrovskiy](https://jira.spring.io/secure/ViewProfile.jspa?name=alexvengrovsk)** opened **[DATAMONGO-1277](https://jira.spring.io/browse/DATAMONGO-1277?redirect=false)** and commented

Add checking for debug enabling in the getPersistentId method. It is not a serious change, but, I think it would be good to have common approach for whole class to debug() method using, where parameter is a concatenated String

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/317

**Comment by christophstrobl** [comment]
resolved via 97da43645ad3891cc0848bb1200cadbfd80cd477
