### ISSUE TITLE
Possibility to create repositories for entities with indexes without connection [DATAMONGO-1309]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2223]
**[Dmitry Bobrov](https://jira.spring.io/secure/ViewProfile.jspa?name=dvbobrov)** opened **[DATAMONGO-1309](https://jira.spring.io/browse/DATAMONGO-1309?redirect=false)** and commented

When I start an application with repositories of documents having `@Indexed` fields, Spring Data tries to create those indexes, and if database connection cannot be established, application cannot start due to BeanCreationException in repository instantiation, though some parts of it are able to function without database connection. It would be great to have lazy index checking in this case

---

**Affects:** 1.8 GA (Gosling)

**Comment by christophstrobl** [comment]
We recommend setting up indexes manually.
