### ISSUE TITLE
Add support for minDistance to geoNear. [DATAMONGO-1330]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2242]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1330](https://jira.spring.io/browse/DATAMONGO-1330?redirect=false)** and commented

---

**Reference URL:** https://docs.mongodb.org/master/reference/operator/aggregation/geoNear/

**Comment by christophstrobl** [comment]
This is supported via the unerlying `NearQuery` of the `GeoNearOperation`. see #744
