### ISSUE TITLE
Upsert does not generate _class field in document [DATAMONGO-1362]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2258]
**[Remi Dettai](https://jira.spring.io/secure/ViewProfile.jspa?name=rdettai)** opened **[DATAMONGO-1362](https://jira.spring.io/browse/DATAMONGO-1362?redirect=false)** and commented

Upsert does not generate `_class` attribute event if entity class is specified.

The attached Spring Boot test demonstrates this. As you can see in the Robomongo screenshot, the document generated by this test does not have the `_class` field that is always added by Spring-Data-Mongodb when saving entities. It could (should?) be added though as the entity class is specified in the upsert method

---

**Affects:** 1.8.1 (Gosling SR1)

**Attachments:**
- [robomongo_screenshot.JPG](https://jira.spring.io/secure/attachment/23264/robomongo_screenshot.JPG) (_38.66 kB_)
- [spring-data-upsert-bug.zip](https://jira.spring.io/secure/attachment/23265/spring-data-upsert-bug.zip) (_11.18 kB_)

**Comment by laubfall** [comment]
Any updates on this issue? MongoTemplate.upsert still does not include the "_class" attribute. In ran into this issue when i tried to retrieve documents via myRepo.findAll(example, exampleMatcher). The call always returned 0 documents even with any constraint to any property cause the underlying query matches only documents with "_class" attribute equals to the persisted entity class.

**Comment by christophstrobl** [comment]
This is the expected behaviour. Update will not add the type hint within the root object as it is specifically targeting fields and not entire objects.
