### ISSUE TITLE
Support for java.time.Duration [DATAMONGO-1347]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2262]
**[Boris Morris](https://jira.spring.io/secure/ViewProfile.jspa?name=bmorris591)** opened **[DATAMONGO-1347](https://jira.spring.io/browse/DATAMONGO-1347?redirect=false)** and commented

Currently if a document contains a field of type `java.time.Duration` then this is persisted by reading the fields of `Duration` resulting in:

```json
"duration" : { "seconds" : NumberLong(300), "nanos" : 0 }
```

Which then fails to be mapped back to a `Duration` when the object is read when the following error:

??mongodb "No property null found on entity class java.time.Duration to bind constructor parameter to!"??

`org.springframework.data.convert.Jsr310Converters` does not seem to have support for `java.time.Duration` and so this results in this error.

Adding the following two custom converters solves the problem:

```java
    public enum DurationToStringConverter implements Converter<Duration, String> {
        INSTANCE;


        @Override
        public String convert(final Duration source) {
            return source.toString();
        }
    }

    public enum StringToDurationConverter implements Converter<String, Duration> {
        INSTANCE;

        @Override
        public Duration convert(final String source) {
            return Duration.parse(source);
        }
    }
```

It may, however, be faster to persist a `Duration` as already happens by default and add some way to create a `Duration` from the sub-document. I don't have enough experience, yet, with MongoDB or Spring Data MongoDB to do that however

---

**Affects:** 1.8.1 (Gosling SR1)

**Comment by christophstrobl** [comment]
Those are part of the defaults registered via `Jsr310Converters`.
