### ISSUE TITLE
NearQuery uses "legacy coordinate pairs" not GeoJSON points [DATAMONGO-1348]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2263]
**[Andrew Thorburn](https://jira.spring.io/secure/ViewProfile.jspa?name=ipsi)** opened **[DATAMONGO-1348](https://jira.spring.io/browse/DATAMONGO-1348?redirect=false)** and commented

According to the MongoDB docs (https://docs.mongodb.org/manual/reference/command/geoNear/), `near` can take either a GeoJSON point or a "legacy coordinate pair" (https://docs.mongodb.org/manual/reference/glossary/#term-legacy-coordinate-pairs). The latter is only required to support version of Mongo pre-2.4, but Spring Data MongoDB 1.8.1 requires 2.6 or above (http://docs.spring.io/spring-data/mongodb/docs/1.8.1.RELEASE/reference/html/#mongodb-getting-started)

---

**Affects:** 1.8.1 (Gosling SR1)

**Issue Links:**
- [DATAMONGO-2166](https://jira.spring.io/browse/DATAMONGO-2166) NearQuery Aggregation passes legacy coordinates even on passing GeoJsonPoint

- [DATAMONGO-2394](https://jira.spring.io/browse/DATAMONGO-2394) nearSphere query wrongly generated with radian parameter instead of meters

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/339

**Comment by sarthak-shivgan** [comment]
> **[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** commented
> 
> PR rebased on current master. Documentation added

Hi @christophstrobl,
I'm facing an issue. Below is my part of code which I'm using to construct $geonear aggregation stage to fetch the clinics near a geoJSON point.

NearByRequest nearByRequest = searchRequest.getNearByRequest();
GeoJsonPoint geoJsonPoint = new GeoJsonPoint(nearByRequest.getLog(),nearByRequest.getLat());
GeoNearOperation geoNearOperation = Aggregation.geoNear(
                NearQuery.near(geoJsonPoint).spherical(true).minDistance(nearByRequest.getMinDistanceInMeters())
                .maxDistance(nearByRequest.getMaxDistanceInMeters()),DbConstants.DISTANCE_IN_METERS);
                
PLease note I have passed maxDistanceInMethers = 5000, minMinDistanceInMeters = 0
And there are some more aggregation stages in the pipeline.
When I debug my code I found that the aggregation query generated by spring data MongoDB is as follows:

{ "aggregate" : "__collection__", "pipeline" : [ { "$geoNear" : { "maxDistance" : 3.1890685E10, "minDistance" : 0.0, "distanceMultiplier" : 1.6E-7, "near" : { "$java" : Point [x=73.944724, y=18.549858] }, "spherical" : true, "distanceField" : "distanceInMeters" } }, { "$skip" : 0}, { "$limit" : 5}, { "$project" : { "consultationServices" : 1, "doctorId" : "$doctor._id", "doctorProfilePhoto" : "$doctor.profilePhoto", "doctorFirstName" : "$doctor.firstName", "doctorLastName" : "$doctor.lastName", "doctorGender" : "$doctor.gender", "yearsOfExperience" : "$doctor.yearsOfExperience", "specialization" : "$doctor.specialization", "facilityId" : "$facilityEntity._id", "facilityName" : "$facilityEntity.facilityName", "facilityAddress" : "$facilityEntity.address", "facilityGeoLocation" : "$facilityEntity.geoLocation", "facilityType" : "$facilityEntity.facilityType"}} ] }

Here I observed that automatically distanceMultiplier is included and also maxDistance is different than what I passed.
The final result set I'm getting is also wrong. Can you please help me with this?
