### ISSUE TITLE
Cannot convert generic sub-document List [DATAMONGO-1388]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2273]
**[Mircea Gaceanu](https://jira.spring.io/secure/ViewProfile.jspa?name=mirtzi)** opened **[DATAMONGO-1388](https://jira.spring.io/browse/DATAMONGO-1388?redirect=false)** and commented

This might be related to [DATAMONGO-1312](https://jira.spring.io/browse/DATAMONGO-1312).
In this case a `java.util.List` field (`agg.min`) is converted to a `Double` list instead of a `Float` list.
**Model:**

```java
public class MyDAO {
    @Id
    private String id;
    public Aggregation<List<Float>, List<Double>, Float> agg;
    // ...
}
```

```java
public class Aggregation<T, R, V> {

    private R avg;
    private T min;
    private V val;
}
```

**Test:**

```java
public class MyDAOTest {

    @Autowired
    private MyDAORepository myDAORepository;    

    @Test
    public void givenGenericEntities_whenFindOne_thenReturnCorrectTypes() {
        // GIVEN
        Aggregation<List<Float>, List<Double>, Float> agg = new Aggregation<>();
        agg.setAvg(Arrays.asList(1d, 2d, 3d));
        agg.setMin(Arrays.asList(0f, 1f, 2f));
        agg.setVal(2f);

        MyDAO myDAO = new MyDAO(agg);
        myDAORepository.save(myDAO);

        // WHEN
        MyDAO dbMyDAO = myDAORepository.findOne(myDAO.getId());

        // THEN
        Aggregation<List<Float>, List<Double>, Float> dbAgg = dbMyDAO.getAgg();

        List<Double> avg = dbAgg.getAvg();
        assertTrue("Types don't match", avg.get(0) instanceof Double);

        Float val = dbAgg.getVal();
        assertTrue("Types don't match", val instanceof Float);
       
        // this FAILS
        List<Float> min = dbAgg.getMin();
        assertTrue("Types don't match", min.get(0) instanceof Float);
    }
}
```

**Versions:**
* spring-data-mongodb - 1.8.4.RELEASE
* spring-data-commons - 1.11.4.RELEASE

Attaching also maven project containing the classes and unit test

---

**Affects:** 1.8.4 (Gosling SR4)

**Attachments:**
- [spring-data-generics.zip](https://jira.spring.io/secure/attachment/23325/spring-data-generics.zip) (_23.41 kB_)

**Comment by christophstrobl** [comment]
issue has been resolved in the past few years. test passes on current _main_ (4.1.0-SNAPSHOT) development line.
