### ISSUE TITLE
I as developer want to provide an explicit Index name for a set of annotated collection fields for the purpose of a TextIndexed search [DATAMONGO-1364]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2279]
**[Urso](https://jira.spring.io/secure/ViewProfile.jspa?name=uwieske)** opened **[DATAMONGO-1364](https://jira.spring.io/browse/DATAMONGO-1364?redirect=false)** and commented

I as developer want to provide an explicit Index name for a set of annotated collection fields for the purpose of a TextIndexed search.

I have created an "TextIndex" for a couple of collection fields (multiple fields) by annotating them with `@TextIndexed`.  Unfortunately I get an runtime error, because the generated indexname is longer than 128 characters (a limit which is enforced by MongoDB). I have a couple of 4 to 5 fieldnames which together (namespaced by their collection name) exceeds more than 127 chars. An alternative solution is to "come up" with a shorter field names to decrease the probability of character exceeding.... but this is a wrong approach of course...). An plausible solution is to manually create TextIndex (in my Spring configuration object) where I am able to set the required field names PLUS a textindex name for this textindex object.)

But, there is currently no way of specifying a name for this TextIndex explicitly using annotations.
It would be great to have a mechanism for explicitly defining the name of an textindex.

```java
@Document
public class SomeDocument {
    
     @Id
     private String uid;

    @TextIndexed
     private String fieldA;

     private String fieldB;

     @TextIndexed
     private String fieldC;

     @TextIndexed
     private String fieldD;

     private String fieldE;
}
```

+Proposed solution:+

Since MongoDB states that only one textindex is allowed per collection, the following alternatives for a solution hold;
1. provide at least one occurrence of a TextIndexed annotation in the class with an annotation attribute "name".
2. or provide all of them (TextIndexed annotations within the class) the same name
3. or define no name on a TextIndex annotation but introduce a new annotation at class level which declares a name for all  of the annotated fields (with `@TextIndexed`). **(See below the SomeDocument example for the proposed class level annotation)**

```java
@Document
*@TextIndexName("idxName1")*
public class SomeDocument {
    
     @Id
     private String uid;

    @TextIndexed
     private String fieldA;

     private String fieldB;

     @TextIndexed
     private String fieldC;

     @TextIndexed
     private String fieldD;

     private String fieldE;
}
```

Thanks and best regards,

Urso Wieske

---
No further details from [DATAMONGO-1364](https://jira.spring.io/browse/DATAMONGO-1364?redirect=false)

**Comment by christophstrobl** [comment]
Thanks for the proposal, we generally recommend manual index setup.
