### ISSUE TITLE
Add Lifecycle Events for update [DATAMONGO-1383]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2297]
**[John Mark](https://jira.spring.io/secure/ViewProfile.jspa?name=springiscool)** opened **[DATAMONGO-1383](https://jira.spring.io/browse/DATAMONGO-1383?redirect=false)** and commented

The current `org.springframework.context.ApplicationEvent` support is nice, but lacks support for catching updates. For example, I have a `lastModified` field that I would like to keep up-to-date, but Spring Data does not provide any way to do this if the document is modified using `MongoTemplate.update()` or `MongoTemplate.findAndModify()`

---
No further details from [DATAMONGO-1383](https://jira.spring.io/browse/DATAMONGO-1383?redirect=false)

**Comment by gobozov** [comment]
Hello folks.
Any update on this? What is the reason behind not emitting event when MongoTemplate.update is called? Because of query may end up with updating multiple documents?

**Comment by christophstrobl** [comment]
As commented on #4291 there's not much we can offer here.
