### ISSUE TITLE
Incorrect warning "Customizing field name for id property not allowed" [DATAMONGO-1417]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2328]
**[Sylvain LAURENT](https://jira.spring.io/secure/ViewProfile.jspa?name=sylvain.laurent)** opened **[DATAMONGO-1417](https://jira.spring.io/browse/DATAMONGO-1417?redirect=false)** and commented

(On v1.8.2)
In BasicMongoPersistentProperty, the warning about

> Customizing field name for id property not allowed! Custom name will not be considered!

is sometimes incorrect.
Indeed, the test is is :

```java
if (isIdProperty() && getFieldName() != ID_FIELD_NAME) {
     LOG.warn("Customizing field name for id property not allowed! Custom name will not be considered!");
}
```

But comparing 2 String must be done with equals(), not by comparing references!
With the debugger, I did check that the result of getFieldName() was "_id" but with a different String instance than the constant ID_FIELD_NAME

---

**Affects:** 1.8.4 (Gosling SR4)

**Comment by christophstrobl** [comment]
issue has been resolved in the past few years. No longer valid on current _main_ (4.1.0-SNAPSHOT) development line.
