### ISSUE TITLE
Read Preference TagSet Support [DATAMONGO-1428]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2339]
**[George Cao](https://jira.spring.io/secure/ViewProfile.jspa?name=georgecao)** opened **[DATAMONGO-1428](https://jira.spring.io/browse/DATAMONGO-1428?redirect=false)** and commented

Right now, spring-data-mongodb does not support read preference with a tag set list.  The mongo-client-options only support the  built-in read preference.

For example, mongo-java-driver 3.0.2 **ReadPreference** has a static method to support read preference with tag sets.

```java
public static TaggableReadPreference secondary(final List<TagSet> tagSetList) {
    return new TaggableReadPreference.SecondaryReadPreference(tagSetList);
}
```

---

**Affects:** 1.8.4 (Gosling SR4), 1.9.1 (Hopper SR1)

**Comment by christophstrobl** [comment]
while we do not intend to extend the xml namespace to support this #4288 allows manual configuration of the `ReadPreference`.
