### ISSUE TITLE
Configurable exception translators [DATAMONGO-1432]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2343]
**[Jonathan Castellani](https://jira.spring.io/secure/ViewProfile.jspa?name=jcastellani)** opened **[DATAMONGO-1432](https://jira.spring.io/browse/DATAMONGO-1432?redirect=false)** and commented

We'd like to hook into the Mongo exception translation in order to fire alerts for certain events, especially those related to `DataAccessResourceFailureException`, from a central location.  We were thinking we could extend `MongoExceptionTranslator` and have that implementation used, but alas, the implementation is not pluggable.

If there's a different/better way of handling this case, we're happy to try it.  We also understand that allowing users to change the behavior of `MongoExceptionTranslator` might not be palatable for you.

---

**Affects:** 1.9.1 (Hopper SR1)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
