### ISSUE TITLE
Spring Data MongoDB auditing doesn't work for embedded documents [DATAMONGO-1440]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2351]
**[Egor Lyashenko](https://jira.spring.io/secure/ViewProfile.jspa?name=yagich)** opened **[DATAMONGO-1440](https://jira.spring.io/browse/DATAMONGO-1440?redirect=false)** and commented

I'm trying to introduce auditing by using `@LastModifiedDate` annotation. It works fine for top-level documents but I've faced with the problem for embedded objects.

For example, by default, when I save document object with inner list, `updated` value is set only for this document but not for any object from the children list. But in this case I want to audit them too

---

**Affects:** 1.9.1 (Hopper SR1)

**Reference URL:** http://stackoverflow.com/questions/37324188/spring-data-mongodb-auditing-doesnt-work-for-embedded-documents/37346938#37346938

5 votes, 6 watchers

**Comment by benzgrant** [comment]
Hey there, any update about this issue?

**Comment by christophstrobl** [comment]
Auditing is targeting the aggregate as a whole and not individual parts of it. Looking at the linked SO reference the `ChildDocument` is part of the aggregate. To enable auditing for `ChildDocument` those would need to be stored individually using `DBRef` to link them to the `ParentDocument`.
