### ISSUE TITLE
GridFsTemplate.getGridFs() shouldn't create a new GridFS instance for every invocation [DATAMONGO-1441]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2352]
**[Derek](https://jira.spring.io/secure/ViewProfile.jspa?name=envoydada)** opened **[DATAMONGO-1441](https://jira.spring.io/browse/DATAMONGO-1441?redirect=false)** and commented

Why create GridFS(new GridFS) everytime?
In GridFS constructor, " filesCollection.count() ,chunksCollection.count()" excute everytime

---

**Affects:** 1.8.4 (Gosling SR4), 1.9.1 (Hopper SR1), 1.8.6 (Gosling SR6), 1.9.5 (Hopper SR5), 1.10 GA (Ingalls)

**Reference URL:** https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/gridfs/GridFsTemplate.java

**Comment by christophstrobl** [comment]
Resolved via #1627.
