### ISSUE TITLE
auditing with java 8 time causes Found cycle for field 'date' in type 'LocalDateTime' for path 'createdDate' [DATAMONGO-1443]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2354]
**[Leon Radley](https://jira.spring.io/secure/ViewProfile.jspa?name=leon)** opened **[DATAMONGO-1443](https://jira.spring.io/browse/DATAMONGO-1443?redirect=false)** and commented

It says in the reference manual that you can use java8 date / times as types

> As you can see, the annotations can be applied selectively, depending on which information you’d like to capture. For the annotations capturing the points in time can be used on properties of type JodaTimes DateTime, legacy Java Date and Calendar, JDK8 date/time types as well as long/Long.

http://docs.spring.io/spring-data/data-mongo/docs/1.9.1.RELEASE/reference/html/#auditing.annotations

, but when I do I get the follow  at startup:

```java
Found cycle for field 'date' in type 'LocalDateTime' for path 'createdDate'
```

If I change the LocalDateTime to a Date, it works

---

**Affects:** 1.9.1 (Hopper SR1)

**Reference URL:** https://github.com/leon/temp-spring-mongo-audit-localdatetime-error

**Comment by christophstrobl** [comment]
fixed in recent _main_ development line
