### ISSUE TITLE
Add support for sorting and paging for criteria based queries [DATAMONGO-1481]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2398]
**[Bob Tiernay](https://jira.spring.io/secure/ViewProfile.jspa?name=btiernay)** opened **[DATAMONGO-1481](https://jira.spring.io/browse/DATAMONGO-1481?redirect=false)** and commented

Currently this is not possible:

http://stackoverflow.com/questions/17255932/is-it-possible-to-use-springdata-mongodb-repository-to-execute-an-arbitrary-quer

However, this looks like it is possible with JPA and `Specification`. This is a very desirable feature for Spring Data REST when a user wants to find by one or more attributes supplied as query params. It would be nice to have parity with JPA in this regard

---

**Reference URL:** http://stackoverflow.com/questions/17255932/is-it-possible-to-use-springdata-mongodb-repository-to-execute-an-arbitrary-quer

1 votes, 3 watchers

**Comment by christophstrobl** [comment]
We don't want to add `query` nor `criteria` into the repository layer and recommend custom implementations or usage of Querydsl if needed.
