### ISSUE TITLE
Auditing annotations does not work when updated using MongoTemplate [DATAMONGO-1482]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2399]
**[Srini Kandula](https://jira.spring.io/secure/ViewProfile.jspa?name=srinikandula)** opened **[DATAMONGO-1482](https://jira.spring.io/browse/DATAMONGO-1482?redirect=false)** and commented

I'm using annotation based configuration.

```java
@Configuration
@Profile("default")
@ComponentScan(basePackages = "com.*")
@EnableMongoRepositories
@EnableMongoAuditing
public class ApplicationDataConfig ....
```

And I also have `@LastModifiedDate`, `@CreatedDate` annotation set on fields of type `org.joda.time.DateTime` on my model class fields. When I use `MongoRepository.save(…)` both the audit fields are set just fine. But when I use `MongoTemplate.updateFirst(…)/updateMulti(…)` the field with `lastupdatedDate` is not being updated. Does anybody have a clue of what could be wrong? I'm using Spring Data MongoDB 1.8.3.

---

**Issue Links:**
- [DATAMONGO-869](https://jira.spring.io/browse/DATAMONGO-869) update* and findAndModify methods do not update audit fields
 (_**"duplicates"**_)

3 votes, 7 watchers

**Comment by ValentineSean** [comment]
> **[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** commented
> 
> I think you don't fully understand the situation. Auditing works on an entity instance level. We need access to the entity instance to set property values on it. `updateMulti(…)`/`updateFirst(…)` just don't work that way. The entire operation is executed **within** the database. I.e. the documents selected by the query aren't even becoming entity instances for the updates.
> 
> `MongoTemplate` contains operations operating on entity instances but also methods that provide more fine-grained operations and control over the database interaction at the expense of less convenience.

Is it now possible to configure MongoTemplate update query to trigger auditing functionality? Also how to make MongoTemplate to operate on entity instance level?
