### ISSUE TITLE
Cant set 'localThreshold' property of MongoClientOptions using MongoClientOptionsFactoryBean [DATAMONGO-1524]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2435]
**[Dariusz Chojnacki](https://jira.spring.io/secure/ViewProfile.jspa?name=dariusz.chojnacki@allegrogroup.com)** opened **[DATAMONGO-1524](https://jira.spring.io/browse/DATAMONGO-1524?redirect=false)** and commented

`com.mongodb.MongoClientOptions` allow to set property 'localThreshold' which is not avaliable when using `org.springframework.data.mongodb.core.MongoClientOptionsFactoryBean`

---

**Affects:** 1.9.4 (Hopper SR4)

**Comment by christophstrobl** [comment]
We do not plan to extend the xml based configuration.
