### ISSUE TITLE
Add SpEL criteria support to $filter [DATAMONGO-1537]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2449]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAMONGO-1537](https://jira.spring.io/browse/DATAMONGO-1537?redirect=false)** and commented

Currently, `$filter` accepts `AggregationExpression` to filter arrays for projection operations. Creation of `AggregationExpression` for each step is somewhat cumbersome and it would be great being able to use SpEL expressions with AST evaluation.

Today's code:

```
project().and("items")
  .filter("item", AggregationFunctionExpressions.GTE.of(field("item.price"), 100)).as("items");
```

Possible code using SpEL

```
project().and("items")
  .filter("item", "item.price >= 100").as("items");
```

---
No further details from [DATAMONGO-1537](https://jira.spring.io/browse/DATAMONGO-1537?redirect=false)

**Comment by christophstrobl** [comment]
This can be done using `AggregationSpELExpression` as outlined below.
```java
Aggregation aggregation = Aggregation.newAggregation(
	Aggregation.project()
		.and("items")
		.filter("item", AggregationSpELExpression.expressionOf("item.price >= 100")).as("items")
);
```
