### ISSUE TITLE
Could the CrudRepository/query generation support findByQuery? [DATAMONGO-1570]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2459]
**[Tony Day](https://jira.spring.io/secure/ViewProfile.jspa?name=balone1988)** opened **[DATAMONGO-1570](https://jira.spring.io/browse/DATAMONGO-1570?redirect=false)** and commented

Would it be possible to allow CrudRepository or query generation to support one of the following:

- findByQuery(Query)
- findByCriteria(Criteria)

The main reasons for this would be:
- Not having to create a custom interface and implementation of a repository just in order to use Query/Criteria.
- Support for projections should work from the outset. For example, at the moment I have no way of taking advantage of the automatic projections with SpEL/`@Value`("#{target.foo}") when I want to use Query/Criteria

---
No further details from [DATAMONGO-1570](https://jira.spring.io/browse/DATAMONGO-1570?redirect=false)

**Comment by christophstrobl** [comment]
we don't want to add `query` nor `criteria` options to the repository layer and recommend a custom implementation or using Querydsl if needed.
