### ISSUE TITLE
Support DBRef in Spring Data Mongo Reactive [DATAMONGO-1584]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2468]
**[Sébastien Deleuze](https://jira.spring.io/secure/ViewProfile.jspa?name=sdeleuze)** opened **[DATAMONGO-1584](https://jira.spring.io/browse/DATAMONGO-1584?redirect=false)** and commented

I have tried to use `@DBRef` in my [Spring Reactive + Kotlin reference application](https://github.com/mix-it/mixit/), but it seems not supported since I get a list with `NULL` values when I do that.

Could you introduce support for eager `@DBRef` resolution in Spring Data Mongo Reactive and throw an exception when `@DBRef` lazy attribute is enabled until [DATAMONGO-1583](https://jira.spring.io/browse/DATAMONGO-1583) is fixed?

Thanks in advance for your help!

---

**Affects:** 2.0 M1 (Kay)

**Reference URL:** https://github.com/mix-it/mixit/blob/master/src/main/kotlin/mixit/model/Session.kt#L13

**Attachments:**
- [DbConfig.kt](https://jira.spring.io/secure/attachment/25445/DbConfig.kt) (_1.51 kB_)
- [NbDbRefResolver.java](https://jira.spring.io/secure/attachment/25446/NbDbRefResolver.java) (_5.28 kB_)

**Issue Links:**
- [DATAMONGO-2146](https://jira.spring.io/browse/DATAMONGO-2146) DBRef resolution is not supported using only reactive MongoDB

- [DATAMONGO-1583](https://jira.spring.io/browse/DATAMONGO-1583) Investigate reactive lazy DBRef resolution

**Referenced from:** commits https://github.com/spring-projects/spring-data-commons/commit/c62bc6f7cccbe9742dcec150eb190012e155a02a

0 votes, 7 watchers

**Comment by charboubmustapha** [comment]
> @Bean
> 	MongoClient reactiveMongoClient() {
> 
> 		ConnectionString connectionString = new ConnectionString("mongodb://localhost");
> 
> 		MongoClientSettings.Builder builder = MongoClientSettings.builder()
> 				.clusterSettings(ClusterSettings.builder().applyConnectionString(connectionString).build())
> 				.connectionPoolSettings(ConnectionPoolSettings.builder().applyConnectionString(connectionString).build())
> 				.serverSettings(ServerSettings.builder().applyConnectionString(connectionString).build())
> 				.credentialList(connectionString.getCredentialList())
> 				.sslSettings(SslSettings.builder().applyConnectionString(connectionString).build())
> 				.socketSettings(SocketSettings.builder().applyConnectionString(connectionString).build());
> 
> 		MongoClientSettings settings = builder.codecRegistry(com.mongodb.MongoClient.getDefaultCodecRegistry()).build();
> 
> 		return MongoClients.create(settings);
> 	}
> 
> 	@Bean
> 	ReactiveMongoTemplate reactiveMongoTemplate(MongoClient mongoClient, MappingMongoConverter mappingMongoConverter) {
> 		return new ReactiveMongoTemplate(new SimpleReactiveMongoDatabaseFactory(mongoClient, "test"),
> 				mappingMongoConverter);
> 	}

Hello , 
I was trying to use this configuration but i i doesn't work , because the MappingMongoConverter is configured with NoOpDbRefResolver in MongoReactiveDataAutoConfiguration .
