### ISSUE TITLE
MappingMongoConverter should convert and excape dollar prefix [DATAMONGO-1554]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2470]
**[schoster barak](https://jira.spring.io/secure/ViewProfile.jspa?name=schosterbarak)** opened **[DATAMONGO-1554](https://jira.spring.io/browse/DATAMONGO-1554?redirect=false)** and commented

MappingMongoConverter should convert and escape dollar prefix as they are not supported as Map key in mongoDb.
in other words, the key can not start in "$"

---

**Affects:** 2.0 M1 (Kay), 1.9.5 (Hopper SR5)

**Reference URL:** https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L704

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/427

**Comment by christophstrobl** [comment]
With MongoDB 5.0 we saw some movement regarding the usage of `$` prefixed keys in both the root as well as nested document structures.

Generally speaking it is possible to store `$` prefixed fields in the root level document. 
```java
class With$FieldName {
	
    @Field("$myValue")
    String value;
}
```
```json
{
    "_id" : "...",
    "$myValue" : "v1"
}
```

The culprit there is the query part which only allows known keywords and requires a rewrite form `{ '$myValue' : 'v1' }` to something like the snippet below, which seems not feasible with the current query mapping.
```json
{ "$expr" : { "$eq" : [ { "$getField" : { "$literal" : "$myValue"}}, "v1"]}}
```

Regarding the usage of `$` in nested documents or similar `Map` like structures it is possible to insert but not upsert those.

```java
class With$MapKey {
    Map<String,String> map;
}

With$MapKey source = new With$MapKey();
source.map = Map.of("k1", "v1", "$k2", "v2");

// works
template.insert(source);

// fails with: Field names in a replacement document can not start with '$' but '$myValue' does
template.save(source); 
```
There's a lot of [restrictions](https://www.mongodb.com/docs/manual/core/dot-dollar-considerations/#general-restrictions) that come with the usage of `$` for field names though it is generally possible using the current API.
The hooks already mentioned in previous comments provide a sufficient enough workaround and we do not intend to change the current mapping process but ask to respect store specific limitations which may require some data preprocessing prior to storage.
