### ISSUE TITLE
Cannot find DB entities using a nested entity id in String form [DATAMONGO-1680]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2591]
**[Hugh Davey](https://jira.spring.io/secure/ViewProfile.jspa?name=hughjdavey)** opened **[DATAMONGO-1680](https://jira.spring.io/browse/DATAMONGO-1680?redirect=false)** and commented

Spring repository `findByX` methods return `null` when trying to find an entity using a nested entity id given as a `String`. This does not happen trying to find the entity using its own id given as a `String`, nor does it happen when an `org.bson.types.ObjectId` is used as the id.

I have reproduced this issue on github and linked to it in the Reference URL field.

An example of this issue on StackOverflow is [here](http://stackoverflow.com/questions/25441514/how-to-find-collections-by-its-nested-objects-objectid-in-spring-data-using-rep)

---

**Affects:** 1.10.1 (Ingalls SR1)

**Reference URL:** https://github.com/hughjdavey/spring-mongo-nested-id

**Comment by christophstrobl** [comment]
works as designed given the answers on Stackoverflow.
