### ISSUE TITLE
Add support for View creation [DATAMONGO-1727]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2594]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAMONGO-1727](https://jira.spring.io/browse/DATAMONGO-1727?redirect=false)** and commented

Add support to create views (introduced with MongoDB 3.4) from aggregation pipelines

---

**Reference URL:** https://docs.mongodb.com/manual/core/views/

**Comment by faryang-sh** [comment]
Does the spring-data-mongodb support view now？
