### ISSUE TITLE
Query interceptor for handling soft deletes [DATAMONGO-1692]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2605]
**[Fırat KÜÇÜK](https://jira.spring.io/secure/ViewProfile.jspa?name=firatkucuk)** opened **[DATAMONGO-1692](https://jira.spring.io/browse/DATAMONGO-1692?redirect=false)** and commented

After query converted to db object an event may be fired. BasicQuery constructor may be the right place. I do not know exactly.

```java
	public BasicQuery(String query, String fields) {
		this.queryObject = (DBObject) JSON.parse(query);
		this.fieldsObject = (DBObject) JSON.parse(fields);

                // fire event here so we can add additional is_deleted where condition
	}
```

---
No further details from [DATAMONGO-1692](https://jira.spring.io/browse/DATAMONGO-1692?redirect=false)

**Comment by ntthuat** [comment]
Is this issue still here? Hope we can resolve this ticket soon...

**Comment by christophstrobl** [comment]
The implications this feature carries along are quite complex. Nearly every operation needs to be aware of the documents that must not be found nor modified and include the according filter to prevent accidental access.
Therefore, we decided to not include this feature. 
Nevertheless, we're happy to discuss extensions/modifications of the existing API to better support custom soft delete solutions. Please open a new issue to start the discussion.
