### ISSUE TITLE
@Field(order = …) is not taken into account when iterating over properties [DATAMONGO-1737]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2643]
**[Joan Bordeau](https://jira.spring.io/secure/ViewProfile.jspa?name=jbordeau)** opened **[DATAMONGO-1737](https://jira.spring.io/browse/DATAMONGO-1737?redirect=false)** and commented

link : https://jira.spring.io/browse/DATAMONGO-172

---

**Affects:** 1.9.11 (Hopper SR11), 1.10.8 (Ingalls SR8), 2.0.1 (Kay SR1)

**Comment by christophstrobl** [comment]
The issue has been resolve quite some time ago (Nov. 2017 - via eb51828d) but never got closed.
