### ISSUE TITLE
Bulk operations do not emit application events [DATAMONGO-1743]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2648]
**[schoster barak](https://jira.spring.io/secure/ViewProfile.jspa?name=schosterbarak)** opened **[DATAMONGO-1743](https://jira.spring.io/browse/DATAMONGO-1743?redirect=false)** and commented

mongoTemplate does not use eventPublisher in case of bulk insert.
as a result, custom application listeners that implements ApplicationListener<BeforeConvertEvent\<Object>> are not called.

---

**Affects:** 1.10.4 (Ingalls SR4), 1.9.11 (Hopper SR11)

**Issue Links:**
- [DATAMONGO-2290](https://jira.spring.io/browse/DATAMONGO-2290) BulkOperation does not trigger lifecycle callbacks for entities
 (_**"is duplicated by"**_)

1 votes, 2 watchers

**Comment by christophstrobl** [comment]
we do not plan to emit events for bulk operations.
