### ISSUE TITLE
Add support for aggregation operator $arrayToObject and $objectToArray [DATAMONGO-1832]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2734]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1832](https://jira.spring.io/browse/DATAMONGO-1832?redirect=false)** and commented

---

**Reference URL:** https://docs.mongodb.com/v3.6/reference/operator/aggregation/arrayToObject/

2 votes, 2 watchers

**Comment by christophstrobl** [comment]
has already been resolved via #603
