### ISSUE TITLE
Add support for $expr to Criteria query. [DATAMONGO-1845]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2750]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1845](https://jira.spring.io/browse/DATAMONGO-1845?redirect=false)** and commented

Allow usage of Aggregation expressions in filter queries using `$expr`.

```javascript
db.monthlyBudget.find( { $expr: { $gt: [ "$spent" , "$budget" ] } } )
```

---

**Reference URL:** https://docs.mongodb.com/manual/reference/operator/query/expr/

3 votes, 3 watchers

**Comment by petitcl** [comment]
What about adding an `exprOperator` method to `Criteria` that accepts an  `AggregationExpression` and behave like `orOperator` and `andOperator` ? It allows to reuse all the aggregation operators already defined in spring-data-mongodb.

```java
public Criteria exprOperator(AggregationExpression expression)
```

The example above could be written like this:
```java
Criteria criteria = new Criteria()
    .exprOperator(
        ComparisonOperators.Gt
              .valueOf("spent")
              .greaterThan("budget")
    );
```

**Comment by davidb-e4s** [comment]
opened over 4 years ago...would be good to get this.
