### ISSUE TITLE
Add support for com.mongodb.client.model.geojson types. [DATAMONGO-1856]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2757]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-1856](https://jira.spring.io/browse/DATAMONGO-1856?redirect=false)** and commented

MongoDB Java Driver supports its own `com.mongodb.client.model.geojson` model and provides codecs for the types declared within that namespace. We should support those types in both queries and domain type

---
No further details from [DATAMONGO-1856](https://jira.spring.io/browse/DATAMONGO-1856?redirect=false)

**Comment by christophstrobl** [comment]
resolved via #3203
