### ISSUE TITLE
@Query placeholder extracted with extra characters  [DATAMONGO-1925]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2824]
**[Weihong Zhang](https://jira.spring.io/secure/ViewProfile.jspa?name=weihongzhang)** opened **[DATAMONGO-1925](https://jira.spring.io/browse/DATAMONGO-1925?redirect=false)** and commented

```java
@Query(value = "{'myId': ?0,'category':?1}")
```

This query failed. The root cause is on `ExpressionEvaluatingParameterBinder.replacePlaceholders`, the first placeholder it extracted is `?0,`", but should be `?0`. Add a space before the single quote can make this query work:

```java
@Query(value = "{'myId': ?0, 'category':?1}")
```

---

**Affects:** 1.9.11 (Hopper SR11), 1.10.11 (Ingalls SR11)

**Comment by christophstrobl** [comment]
already solved by #643
