### ISSUE TITLE
Support nested level projections through interface-based projection [DATAMONGO-1989]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2860]
**[Dennis Nijssen](https://jira.spring.io/secure/ViewProfile.jspa?name=dnijssen)** opened **[DATAMONGO-1989](https://jira.spring.io/browse/DATAMONGO-1989?redirect=false)** and commented

It would be great to support nested level projections through interfaces. Given a closed projection with a nested class, we would be able to support nested fields.

The document / collection class:

```java
@Document
public class Person {

    private String firstName;
    private String lastName;
    private Address address;

    static class Address {

        private String zipCode, city;

        // getters and setters
    }

    // getters and setters
}
```

The closed projection interface:

```java
public interface PersonSummary {

    String getFirstName();

    AddressSummary getAddress();

    interface AddressSummary {

        String getCity();
    }
}
```

Actual "fields" outcome right now:

```
fields: Document`firstName=1, address=1`
```

Expected "fields" outcome:

```
fields: Document`firstName=1, address.city=1`
```

 

---

**Reference URL:** https://stackoverflow.com/questions/50487231/spring-data-mongodb-interface-based-projection-recursively

1 votes, 2 watchers

**Comment by mp911de** [comment]
See also https://github.com/spring-projects/spring-data-commons/pull/2420.

**Comment by christophstrobl** [comment]
resloved via #3894
