### ISSUE TITLE
Unnecessary string distance calculation when using @Field [DATAMONGO-1991]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2862]
**[Ludek Novotny](https://jira.spring.io/secure/ViewProfile.jspa?name=novotny)** opened **[DATAMONGO-1991](https://jira.spring.io/browse/DATAMONGO-1991?redirect=false)** and commented

When `@Field` annotation is used to have different Mongo Document field name than bean field name, string distance (org.springframework.beans.PropertyMatches.calculateStringDistance) is calculated for all combinations of fields. If the distance is too big, name from annotation is used as fallback.

This causes a big performance hit in our application. Our solution was to implement cache in PropertyMatches but more permanent solution would be appreciated as we don't really want to maintain our version of spring-beans. We also believe the cache isn't the best solution. Is there a reason why field name from `@Field` isn't used with highest priority and string distance would be fallback?

This issue is somehow related to [BATCH-1876](https://jira.spring.io/browse/BATCH-1876). But our use case is with Mongo. Our application is running on Spring Boot 2.0.0-RELEASE

---

**Reference URL:** https://jira.spring.io/browse/BATCH-1876

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
Superseded by spring-projects/spring-data-commons#2837
