### ISSUE TITLE
Support For Named Json Queries In Spring Data MongoDB [DATAMONGO-2013]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2882]
**[Ankur Pathak](https://jira.spring.io/secure/ViewProfile.jspa?name=ankur%20pathak)** opened **[DATAMONGO-2013](https://jira.spring.io/browse/DATAMONGO-2013?redirect=false)** and commented

We should store our mongo db queries in json something like below: 

{
"filters" : {
"User.username" : {
"username" : "?1"
}
},

"sorts": {
"User.username" :{
"username" : -1
}

},

"projections" : {
"User.username" : {
"firstName": true,
"lastName" : true,
"_id": false

}

},

"aggregations": {

}

}

 And then use them in repositories like below:

interface IUserRepository extends MongoRepository<User, Long> {

`@NamedQuery`(sort = "User.username", filter: "User.username", projetion: "User.username")
Page\<User> findByUsername(Pageable pageable);
}

This will separate the queries(strings) and repository(java) separate. It will also make queries easier to write. The queries will look elegant and natural as they are used in mongodb

---
No further details from [DATAMONGO-2013](https://jira.spring.io/browse/DATAMONGO-2013?redirect=false)

**Comment by christophstrobl** [comment]
Closing this one as we're not adding yet another way to express queries.
