### ISSUE TITLE
Query By Example does not handle includeNullValues together with ignorePaths [DATAMONGO-2060]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#2926]
**[John Mark](https://jira.spring.io/secure/ViewProfile.jspa?name=springiscool)** opened **[DATAMONGO-2060](https://jira.spring.io/browse/DATAMONGO-2060?redirect=false)** and commented

They way query by example (QBE) currently implements `withIncludeNullValues` is to use embedded document matching instead of dot notation property matching. While this works well if there are no ignored paths, it does not work when paired with ignore paths (i.e. There are two different fields in the object used to create the `Example`, one is null and the other has a value but is ignored using `withIgnorePaths`). What currently happens is that the ignore paths are stripped out of the embedded document query, which means that it will won't match since the document in the database may contain the ignored paths

---

**Affects:** 2.0.9 (Kay SR9)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by SebastianOltmanns** [comment]
> **[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** commented
> 
> Thank you for briging this up. `MongoExampleMapper` strives to stay in sync with the read/write symetry of domain types provided by the `MongoConverter`. This is why probes are pushed through the very same object mapping as any bean is that is written to the store. Ignoring properies on an `Example` level using ignored paths breaks this symetry.
> 
> Thinking of an alternative way to solve the issue it might be possible to use `PropertyValueTransformer` those paths advising the mapper to resolve them to `$exists : true`. Still you'd have to drop usage of `withIgnoreNullValues()` as query operators cannot be nested inside a full document for matching

@christophstrobl Do I interpret correctly, that `ExampleMatcher.withIncludeNullValues` cannot be used when using spring-mongodb? Using `withIgnorePaths` or not using it does not matter?

I just wanted to use `withIncludeNullValues`, and it did not work. I converted the code to JPA/hibernate and there, it works. In addition to being very sad about this, I am confused, because in the [official spring docs](https://docs.spring.io/spring-data/mongodb/reference/data-commons/query-by-example.html), exactly this method is used as an example.
