### ISSUE TITLE
Check MongoException error labels for recoverable transaction errors [DATAMONGO-2073]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2939]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2073](https://jira.spring.io/browse/DATAMONGO-2073?redirect=false)** and commented

Check `MongoException` for lables `TransientTransactionError, UnknownTransactionCommitResult` indicating potentially recoverable transaction commit errors and translate them to `TransientDataAccessException`.

See `MongoException#hasErrorLabel(String)`.

---

**Issue Links:**
- [DATAMONGO-2075](https://jira.spring.io/browse/DATAMONGO-2075) Open up MongoTransaction manager to allow transaction commit retry.

- [DATAMONGO-2291](https://jira.spring.io/browse/DATAMONGO-2291) MongoExceptionTranslator hides WriteConflicts

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/605

1 votes, 2 watchers

**Comment by WitekBaranowskiAllegro** [comment]
@christophstrobl do you have any plans to fix this issue?

**Comment by mp911de** [comment]
We do not have means to represent the dimension of contextual transient exceptions. If we would wrap certain exceptions into a `TransientException` wrapper, then calling code would not be able to handle the actual exception type. Also, conditionally using a different exception type would introduce a different behavior potentially breaking existing application code.

As there is no other means of adding the information, we suggest using `MongoExceptionTranslator.isTransientFailure`.
