### ISSUE TITLE
Support single result with @Query annotation [DATAMONGO-2117]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2984]
**[gillius](https://jira.spring.io/secure/ViewProfile.jspa?name=gillius)** opened **[DATAMONGO-2117](https://jira.spring.io/browse/DATAMONGO-2117?redirect=false)** and commented

I recently upgraded a Spring Data Mongo 1.3.5, Java 7 project to 2.1.1, Java 8. The biggest issue I faced was with repository support in that when using custom queries, there is no way I could find to support a single item query. Here is the original code, a method declaration in an interface:

```java
/**
 * Finds the id of the most recently approved document with the given name.
 */
@Query(value="{$query:   {name: ?0, approval: {'$ne': null}}," +
             " $orderby: {'approval.approvedDate': -1}}",
          fields = "{ _id: 1 }")
ItemValueSet getLatestApprovedIdByName(String name);
```

And here is the best possible code I could discover using 2.1.1:

```java
	/**
	 * Please use {@link #getLatestApprovedIdByName(String)}.
	 */
	@Query(value="{name: ?0, approval: {'$ne': null}}",
			sort="{'approval.approvedDate': -1}",
			fields = "{ _id: 1 }")
	List<ItemValueSet> getLatestApprovedIdByName(String name, Pageable pageable);

	/**
	 * Finds the id of the most recently approved document with the given name.
	 */
	default ItemValueSet getLatestApprovedIdByName(String name) {
		return getLatestApprovedIdByName(name, PageRequest.of(0, 1)).stream().findFirst().orElse(null);
	}

```

The Spring Data 1 version worked to return a single item. The Spring Data 2 version requires the use of List and Pageable. At this point, it's barely any benefit over implementing with MongoTemplate directly, and it adds a method that I have to document as "please never call it".

The complexity of the query is such that I can't (or don't know how to) transform this into a findFirstByXOrderByY method name.

Please provide a way to allow a limit or at least a single element query.

Side note: I tried having the method declare Stream instead of List. When I did that, the method run time went from 8ms to 4.7 seconds. I repeated the test multiple times on 2 different (remote) servers and the performance difference held. The collection only had 3 documents, but the documents are very large, so I suspect the projection (limiting to _id) field was not working and maybe downloading the whole document. I can file a separate JIRA on this if desired but I don't have more information on the reason

---

**Affects:** 2.1.1 (Lovelace SR1)

**Comment by christophstrobl** [comment]
There are a couple of ways to do this. Easiest and most efficient one is to make sure the query returns just a single element takes load off both server and client side.
