### ISSUE TITLE
Flaky Tests. [DATAMONGO-2122]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2988]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAMONGO-2122](https://jira.spring.io/browse/DATAMONGO-2122?redirect=false)** and commented

The Travis build of the 2.1.2.RELEASE tag was broken today.

I reran it and it was broken again, I think with a different testfailure:

`changeStreamEventsShouldBeEmittedCorrectly ... expected <3> but was <1>`

Restarting the build made the error go away

---
No further details from [DATAMONGO-2122](https://jira.spring.io/browse/DATAMONGO-2122?redirect=false)

**Comment by christophstrobl** [comment]
seems to be resolved in the meantime - build is running pretty stable by now.
