### ISSUE TITLE
NearQuery Aggregation passes legacy coordinates even on passing GeoJsonPoint [DATAMONGO-2166]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#2989]
**[ubarua123](https://jira.spring.io/secure/ViewProfile.jspa?name=ubarua123)** opened **[DATAMONGO-2166](https://jira.spring.io/browse/DATAMONGO-2166?redirect=false)** and commented

As mentioned, 

I have a database which has GeoJson points. Sample doc:

 

```java
 {
	"_id" : ObjectId("5c0f99b0c583dc0bfefaa579"),
	"address" : "CMR Residency, Chandanagar, Ashok Nagar, Ramachandra Puram, Hyderabad, Telangana 502032, India",
	"loc" : {
		"type" : "Point",
		"coordinates" : [
			78.3142108,
			17.504163100000003
		]
	},
	"city" : "Hyderabad",
	"country" : "IN"
}
```

In order to execute $geoNear, one has to pass GeoJson point otherwise it'll return erroneous results since the objects stored are of type GeoJson.

Example $geoNear:

 

```java
// $geoNear: {
        near: { type: "Point", coordinates: [ -73.99279 , 40.719296 ] },
        distanceField: "dist.calculated",
        maxDistance: 2,
        query: { type: "public" },
        includeLocs: "dist.location",
        num: 5,
        spherical: true
     }
```

 

 

If you notice the "near" parameter, its of type "Point".

In Spring, NearQuery has a constructor method which accepts "Point" as an argument. I expected that if I pass Point object, it'll pass the same as it is to the aggregation framework. Instead it passes **Legacy Coordinate Array.** This return wrong results and is not able to calculate accurate distance.

 

Code:

```java
GeoJsonPoint point = new GeoJsonPoint(78.35394790000001, 17.4470426);
NearQuery nearQuery =
        near(point)
                .num(limit)
                .spherical(true);
GeoNearOperation gno = Aggregation.geoNear(nearQuery,"distanceCalculated");
final TypedAggregation aggregation = Aggregation.newAggregation(PickupPointDistanceDO.class, gno);
AggregationResults<PickupPointDistanceDO> results = mongoTemplate.aggregate(aggregation, PickupPointDistanceDO.class);
```

```java
2018-12-12 15:55:06.958 DEBUG 3384 --- [onPool-worker-3] o.s.data.mongodb.core.MongoTemplate:

// [{ "$geoNear": 
     { 
       "num": 50, 
       "near": [78.35394790000001, 17.4470426], 
       "spherical": true, 
       "distanceField": "distanceCalculated" 
      }
     }]
```

 On going through **NearQuery.java** code, i found the line in the method **toDocument()**

```java
document.put("near", Arrays.asList(point.getX(), point.getY()));
```

This is obviously wrong as its purposely converting the point object to an array of **Legacy Coordinates**.

 

---

**Affects:** 2.1.3 (Lovelace SR3)

**Reference URL:** https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/

**Issue Links:**
- [DATAMONGO-1348](https://jira.spring.io/browse/DATAMONGO-1348) NearQuery uses "legacy coordinate pairs" not GeoJSON points

**Comment by sarthak-shivgan** [comment]
Hi @christophstrobl ,
I'm facing an issue. Below is my part of code which I'm using to construct $geonear aggregation stage to fetch the clinics near a geoJSON point.

NearByRequest nearByRequest = searchRequest.getNearByRequest();
GeoJsonPoint geoJsonPoint = new GeoJsonPoint(nearByRequest.getLog(),nearByRequest.getLat());
GeoNearOperation geoNearOperation = Aggregation.geoNear(
NearQuery.near(geoJsonPoint).spherical(true).minDistance(nearByRequest.getMinDistanceInMeters())
.maxDistance(nearByRequest.getMaxDistanceInMeters()),DbConstants.DISTANCE_IN_METERS);

PLease note I have passed maxDistanceInMethers = 5000, minMinDistanceInMeters = 0
And there are some more aggregation stages in the pipeline.
When I debug my code I found that the aggregation query generated by spring data MongoDB is as follows:

{ "aggregate" : "collection", "pipeline" : [ { "$geoNear" : { "maxDistance" : 3.1890685E10, "minDistance" : 0.0, "distanceMultiplier" : 1.6E-7, "near" : { "$java" : Point [x=73.944724, y=18.549858] }, "spherical" : true, "distanceField" : "distanceInMeters" } }, { "$skip" : 0}, { "$limit" : 5}, { "$project" : { "consultationServices" : 1, "doctorId" : "$doctor._id", "doctorProfilePhoto" : "$doctor.profilePhoto", "doctorFirstName" : "$doctor.firstName", "doctorLastName" : "$doctor.lastName", "doctorGender" : "$doctor.gender", "yearsOfExperience" : "$doctor.yearsOfExperience", "specialization" : "$doctor.specialization", "facilityId" : "$facilityEntity._id", "facilityName" : "$facilityEntity.facilityName", "facilityAddress" : "$facilityEntity.address", "facilityGeoLocation" : "$facilityEntity.geoLocation", "facilityType" : "$facilityEntity.facilityType"}} ] }

Here I observed that automatically distanceMultiplier is included and also maxDistance is different than what I passed.
The final result set I'm getting is also wrong. Can you please help me with this?

**Comment by christophstrobl** [comment]
@sarthak-shivgan we prefer to use GitHub issues only for bugs and enhancements. If you feel you encountered a bug in the current implementation please open a new issue (an potentially link related ones). Also make sure to take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.
