### ISSUE TITLE
Provide field level converter [DATAMONGO-2131]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3000]
**[iqjumps](https://jira.spring.io/secure/ViewProfile.jspa?name=iqjumps)** opened **[DATAMONGO-2131](https://jira.spring.io/browse/DATAMONGO-2131?redirect=false)** and commented

I know Spring Data MongoDB supports Type-based custom converter.
But it's helpful to provide custom converter for specific fields.
(javax.persistence.Convert annotation is similar what I'm saying)

Thanks

---

1 votes, 1 watchers

**Comment by christophstrobl** [comment]
Resolved via #3982
