### ISSUE TITLE
Save Map with list of objects in value as DBRef [DATAMONGO-2132]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3001]
**[yuremboo](https://jira.spring.io/secure/ViewProfile.jspa?name=yuremboo)** opened **[DATAMONGO-2132](https://jira.spring.io/browse/DATAMONGO-2132?redirect=false)** and commented

Add possibility to save as DBRef Map with value which has list of entity objects. E.g.

```java
@DBRef
private Map<String, List<Child>> children;
```

 

Expected behavior: In mongodb we'll get:

 

```java
"children": {
  "child1": [
    {"$ref": "Child","$id": "5e6c1dec-4744-4eff-94c3-f66727d63156","$db": ""}, {"$ref": "Child","$id": "5e6c1dec-4744-4eff-94c3-f66727d85469","$db": ""}
  ], "child2": [ {"$ref": "Child","$id": "856c1dec-4744-4eff-94c3-f66727d63156","$db": ""}, {"$ref": "Child","$id": "886c1dec-4744-4eff-94c3-f66727d85469","$db": ""} ]
}
```

Actual behavior:

MappingException: No id property found on class class java.util.ArrayList

 

---

7 votes, 5 watchers

**Comment by Sukesh190** [comment]
I have same problem.

**Comment by christophstrobl** [comment]
This is something we do not plan to support.
