### ISSUE TITLE
@CompoundIndex has no configuration for collation and strength  [DATAMONGO-2133]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3002]
**[Bjorn Harvold](https://jira.spring.io/secure/ViewProfile.jspa?name=bjornharvold)** opened **[DATAMONGO-2133](https://jira.spring.io/browse/DATAMONGO-2133?redirect=false)** and commented

Request: Add support for collation and strength and other options to `@CompoundIndex`... or add documentation on adding all this is possible within def. E.g. def="\{a: 1, b:1}{collation:'en', strength:2}".

From what I can see, there is no support for adding collation or strength or similar options using `@CompoundIndex`. There might be a way to do it within the the "def" property but I cannot find any documentation that explains how to do this. Index fields and options are two different JSON pairs and I am not sure they would fit into "def" that only looks to cover the actual fields themselves

---

**Affects:** 2.1.2 (Lovelace SR2)

1 votes, 1 watchers

**Comment by StefanTirea** [comment]
Hi @odrotbohm,
I would like to try to work on/solve this issue.
I just wanted to make sure that nobody is already working on this before I start🙂.
