### ISSUE TITLE
Type-safe Kotlin update extension [DATAMONGO-2163]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3028]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAMONGO-2163](https://jira.spring.io/browse/DATAMONGO-2163?redirect=false)** and commented

Similar to [DATAMONGO-2138](https://jira.spring.io/browse/DATAMONGO-2138), we should provide a type-safe Update DSL using Kotlin property references. The initial pull request contained already a potential example:

```java
operations.updateFirst(Book::name isEqualTo "Moby-Dick", set(Book::price, 11)) 
```

---

**Reference URL:** https://github.com/spring-projects/spring-data-mongodb/pull/622

**Issue Links:**
- [DATAMONGO-2138](https://jira.spring.io/browse/DATAMONGO-2138) Type-safe Kotlin query extension
 (_**"depends on"**_)

1 votes, 4 watchers

**Comment by inakov** [comment]
Hey there, is someone working on this? With your help, I can try to prepare a PR for this, because I really hate mixing both typed queries and Update builders.

**Comment by pmatysek** [comment]
Hi,
I've prepared a PR with the proposal for this type-safe Update DSL. For every method in the Update class, I created an extension equivalent in Kotlin taking KProperty<T> as a key
