### ISSUE TITLE
Spring Data MongoDB: @DBRef does not handle Back-References -> Stackoverflow Exception [DATAMONGO-2299]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3156]
**[bollywood-coder](https://jira.spring.io/secure/ViewProfile.jspa?name=bollywood-coder)** opened **[DATAMONGO-2299](https://jira.spring.io/browse/DATAMONGO-2299?redirect=false)** and commented

As referenced to the Spring Github Issue page.

https://github.com/spring-projects/spring-boot/issues/17105

---

**Affects:** 2.1.8 (Lovelace SR8)

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/17105

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by christophstrobl** [comment]
Though not idiomatic Kotlin, we do not intend to pick up Kotlin `lateinit` for references as an alternative for `@DBRef(lazy=true)` as we cannot distinguish between an explicitly set `lazy=false` and the default value.
