### ISSUE TITLE
Support Trigonometry Expressions in Aggregations [DATAMONGO-2369]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3226]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2369](https://jira.spring.io/browse/DATAMONGO-2369?redirect=false)** and commented

---

**Reference URL:** https://docs.mongodb.com/manual/release-notes/4.2/#aggregation-trigonometry-expressions

**Comment by christophstrobl** [comment]
resolved by #3728
