### ISSUE TITLE
Add support for Aggregation Regular Expressions [DATAMONGO-2371]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3227]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2371](https://jira.spring.io/browse/DATAMONGO-2371?redirect=false)** and commented

---

**Reference URL:** https://docs.mongodb.com/manual/release-notes/4.2/#aggregation-regular-expressions-regex-operators

**Comment by christophstrobl** [comment]
resolved by #3725
