### ISSUE TITLE
Native UUID datatype support [DATAMONGO-2389]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3248]
**[Sola](https://jira.spring.io/secure/ViewProfile.jspa?name=soladev)** opened **[DATAMONGO-2389](https://jira.spring.io/browse/DATAMONGO-2389?redirect=false)** and commented

Since it's possible to have a native UUID datatype in MongoDB:

```javascript
rs0:PRIMARY> db.test.insert({"_id": UUID()})
WriteResult({ "nInserted" : 1 })
rs0:PRIMARY> db.test.find()
{ "_id" : UUID("e4055c96-c10c-48d9-8797-95d665c60c0e") }
rs0:PRIMARY> db.test.find({'_id': UUID('e4055c96-c10c-48d9-8797-95d665c60c0e')})                                                                                                                                   { "_id" : UUID("e4055c96-c10c-48d9-8797-95d665c60c0e") } 
```

Is it possible to make a `java.lang.UUID` mapping directly to MongoDB's UUID datatype?

The reason behind this is querying BinData when you only have the hex form of UUID available inside mongo shell is very painful.

---

**Affects:** 2.2 GA (Moore)

1 votes, 3 watchers

**Comment by christophstrobl** [comment]
Can be done by setting the according `UuidRepresentation` in the configuration.
