### ISSUE TITLE
BeanInstantiationException: Failed to instantiate []: Specified class is an interface [DATAMONGO-2391]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3251]
**[Ilya Zinkevich](https://jira.spring.io/secure/ViewProfile.jspa?name=busotir)** opened **[DATAMONGO-2391](https://jira.spring.io/browse/DATAMONGO-2391?redirect=false)** and commented

Hi,

I get error with package org.springframework.boot:spring-boot-starter-data-mongodb:2.1.5.RELEASE

Description:
I have interface `Call` and class `TokBoxCall` (implements `Call`) in the code.
There is default _typeKey_ in the records in Mongo DB:
`"_class":"com.xxxxx.server.data.model.call.TokBoxCall".`

And I didn't overwrite it in Spring Mongo Config.
However, when I perform reading operations, e.g. `callRepository.findById(id)`, I get Exception:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.xxxxx.server.data.model.Call]: Specified class is an interface
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:119)
        at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:64)}}
```

---

**Affects:** 2.1.11 (Lovelace SR11)

1 votes, 4 watchers

**Comment by monosoul** [comment]
@christophstrobl here's a repository with a reproducer for the issue: https://github.com/monosoul/spring-data-mongo-issue/tree/main

The worst thing about it is that the behavior is inconsistent. You can't reproduce it if you save the document first using the same repository. 
Check [SaveAndGetWithRepositoryTest](https://github.com/monosoul/spring-data-mongo-issue/blob/main/src/test/kotlin/dev/monosoul/spring/data/mongo/issue/SaveAndGetWithRepositoryTest.kt) and [SaveWithTemplateAndGetWithRepositoryTest](https://github.com/monosoul/spring-data-mongo-issue/blob/main/src/test/kotlin/dev/monosoul/spring/data/mongo/issue/SaveWithTemplateAndGetWithRepositoryTest.kt).

I also wrote a blog post explaining the issue and providing multiple ways to solve it: https://blog.monosoul.dev/2022/09/16/spring-data-mongodb-polymorphic-fields/

**Comment by monosoul** [comment]
Hey @christophstrobl , thanks for the prompt reply!

Yeah, initial entity set seems to do the job, although I'd go with something like this:
```kotlin
    override fun getInitialEntitySet() = super.getInitialEntitySet().also {
        it.add(FieldType.FieldTypeImpl::class.java)
        it.add(FieldType.OtherFieldTypeImpl::class.java)
    }
```

Could it have any unexpected side effects though? Is there a chance `FieldTypeImpl` and `OtherFieldTypeImpl` will be treated as separate collections in mongo?

**Comment by ehardy** [comment]
Just bumped into this issue. `getInitialSet()` scans for classes annotated with `@Document`. Would it make sense for it to also look for classes annotated with `@TypeAlias`? Seems to me like it would solve this issue, as that's essentially what we are doing explicitly when overriding `getInitialSet()`.

**Comment by christophstrobl** [comment]
`@TypeAlias`, other than `@Document`,  is not tied to a specific store, which is insufficient to associate entity classes with the `MongoMappingContext`.

**Comment by DobryninVyacheslav** [comment]
Met with this error too. Moreover, it was floating for me, if I first update and then read, then information about the children is added to the cache and everything works fine, but if I make read request right away after startup, then this error appeared.
Finally solved it like this:
- set the `@Document` annotations over the types that implement the interface (an important point, if put over the interface, the scanning mechanism will not add children to the `initialEntitySet`, which will result in the error)
- added `@EntityScan("your.package.with.models")`, this allows to add information about children to the `initialEntitySet`, and then to the cache, as a result, the error described above does not appear.

`initialEntitySet` is a field in the `org.springframework.data.mapping.context.AbstractMappingContext` class:
<img width="1029" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/49430239/c48aac26-0697-42f4-8262-5153c678ba97">
You can put a breakpoint here and see which models are added during the scan:
<img width="663" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/49430239/53034af2-fa31-472f-a1f3-6e1c463a90ae">
And the logic of scanning and populating the given context is executed in the given configuration:
<img width="989" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/49430239/c2bd96ef-924b-4fda-babf-6cd8806ac04b">

**Comment by DobryninVyacheslav** [comment]
Thank you too!
