### ISSUE TITLE
Make @Enumerated work [DATAMONGO-2408]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3268]
**[Burak Bayrakdar](https://jira.spring.io/secure/ViewProfile.jspa?name=bur%C3%A6quete)** opened **[DATAMONGO-2408](https://jira.spring.io/browse/DATAMONGO-2408?redirect=false)** and commented

I'd like to be able to utilize

```java
@Enumerated
```

within my MongoDB documents.
----------------------------

For example;

```java
@Data
@Document
public class Documento {

    @Enumerated(EnumType.ORDINAL)
    private Enumss enumss;
}

public enum Enumss {
    A, B;
}
```

I'd like to see index values for above enumeration, not the names. With above document, the annotation is completely ignored, since the annotation is not even included within the **spring-boot-starter-data-mongodb** dependency.

Why is this not supported, and can it be in the near future?

---

**Affects:** 2.2.1 (Moore SR1)

**Reference URL:** https://stackoverflow.com/questions/12385920/spring-mongodb-storing-retrieving-enums-as-int-not-string

**Comment by ABDO-AR** [comment]
Why must we create a converter for a simple operation like this one?
---
I think this is an important feature that would make it easier to support enums, so please support it & thanks
