### ISSUE TITLE
Add StringBased AggregationOperation using json/Document syntax. [DATAMONGO-2446]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3301]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2446](https://jira.spring.io/browse/DATAMONGO-2446?redirect=false)** and commented

as an alternative to the StringBasedAggregation only present on repository level

---
No further details from [DATAMONGO-2446](https://jira.spring.io/browse/DATAMONGO-2446?redirect=false)

**Comment by christophstrobl** [comment]
Resolved by #4059
