### ISSUE TITLE
Remove joda time converters converting to non native types from StoreConversions. [DATAMONGO-2472]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3327]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2472](https://jira.spring.io/browse/DATAMONGO-2472?redirect=false)** and commented

reading: `java.time.LocalDateTime` -> `org.joda.time.LocalDateTime`

---
No further details from [DATAMONGO-2472](https://jira.spring.io/browse/DATAMONGO-2472?redirect=false)

**Comment by zmes50416** [comment]
Hi, I have encountered the same warn log mentioned in spring-projects/spring-data-commons#2026
May I ask Does the team has a schedule to address this issue? if not, how do I filter out the converter?

Thank

**Comment by SELiOTe** [comment]
problem still exists at 2023,`eureka-client` in my project , and it import `joda-time`, when I start up my application, I get this WARNING

**Comment by christophstrobl** [comment]
The joda time support is gone since 2022. (see: spring-projects/spring-data-commons#2276)
