### ISSUE TITLE
Insertable and un-updatable field annotation [DATAMONGO-2514]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3369]
**[yejianfengblue](https://jira.spring.io/secure/ViewProfile.jspa?name=yejianfengblue)** opened **[DATAMONGO-2514](https://jira.spring.io/browse/DATAMONGO-2514?redirect=false)** and commented

Is it possible to add an annotation to make a field insertable on creation but not updatable on update? That is an equivalent of JPA `@Column`(insertable = true, updatable = false).

For some fields which is part of business key, they should be persisted on creation, but not on update. Currently Spring Data MongoDB checks Spring Data annotation `@Transient` and `@ReadOnlyProperty`, but both annotations make the field NOT insertable also

---

**Affects:** 2.2.6 (Moore SR6)

**Comment by mertaksoy** [comment]
I would like to know why this issue got declined.
