### ISSUE TITLE
Add support for repository updates via @Aggregation [DATAMONGO-2522]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3377]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2522](https://jira.spring.io/browse/DATAMONGO-2522?redirect=false)** and commented

---
No further details from [DATAMONGO-2522](https://jira.spring.io/browse/DATAMONGO-2522?redirect=false)

**Comment by christophstrobl** [comment]
resolved via #284
