### ISSUE TITLE
Test various MongoDB versions against JDK 8, latest stable one against other JDKs [DATAMONGO-2527]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3382]
**[Greg Turnquist](https://jira.spring.io/secure/ViewProfile.jspa?name=gregturn)** opened **[DATAMONGO-2527](https://jira.spring.io/browse/DATAMONGO-2527?redirect=false)** and commented

---
No further details from [DATAMONGO-2527](https://jira.spring.io/browse/DATAMONGO-2527?redirect=false)

**Comment by gregturn** [comment]
Already completed in our present CI plan.
