### ISSUE TITLE
Add routing capabilities to support per tenant database [DATAMONGO-2528]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3384]
**[mouellet](https://jira.spring.io/secure/ViewProfile.jspa?name=mouellet1)** opened **[DATAMONGO-2528](https://jira.spring.io/browse/DATAMONGO-2528?redirect=false)** and commented

Should an `AbstractRoutingMongoDatabaseFactory` be added for both imperative and reactive database factory?

It could follow the same implementation as in [spring-jdbc](https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.java), [spring-data-r2dbc](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/connectionfactory/lookup/AbstractRoutingConnectionFactory.java), [spring-data-cassandra](https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/cql/session/lookup/AbstractRoutingSessionFactory.java), etc

---

**Issue Links:**
- [DATAMONGO-2505](https://jira.spring.io/browse/DATAMONGO-2505) Deferred Database retrieval from ReactiveMongoDatabaseFactory

**Comment by mp911de** [comment]
Superseded by #3636.
