### ISSUE TITLE
Invalid reference '_id' while grouping [DATAMONGO-2546]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3402]
**[itzvarman](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49561)** opened **[DATAMONGO-2546](https://jira.spring.io/browse/DATAMONGO-2546?redirect=false)** and commented

I have data set after projecting `project("name")` which gave you following data

```javascript
{ "_id": 1, "name":"Maths" },
{ "_id": 1, "name":"Maths" },
{ "_id": 2, "name":"Science" },
{ "_id": 2, "name":"Science" }
```

I try to group using

```java
group("_id").first("name").as("name")
```

It throws Invalid reference `_id` error. But when I do like following its working fine

```java
aggregationOperationContext -> {
  return new Document("$group",
             new Document("_id", "$_id").append("name", new Document("$first", "$name")));
}
```

Finally I projected the `_id` field also, then `group("_id").first("name").as("name")` working fine.

In my document class, I have `private ObjectId _id;`
 

---

**Reference URL:** https://stackoverflow.com/questions/61745356/group-by-id-doesnt-work-in-spring-data-mongodb?noredirect=1#comment109225421_61745356

**Comment by christophstrobl** [comment]
This issue has been addressed via #3542.
