### ISSUE TITLE
Deprecate sparse option for index [DATAMONGO-2550]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3406]
**[isopov](https://jira.spring.io/secure/ViewProfile.jspa?name=isopov1)** opened **[DATAMONGO-2550](https://jira.spring.io/browse/DATAMONGO-2550?redirect=false)** and commented

According to https://docs.mongodb.com/manual/core/index-sparse/ and https://docs.mongodb.com/manual/core/index-partial/#index-type-partial 
["partial indexes](https://docs.mongodb.com/manual/core/index-partial/#index-type-partial) should be preferred over sparse indexes" - this seems like a definition of deprecation with replacement

---
No further details from [DATAMONGO-2550](https://jira.spring.io/browse/DATAMONGO-2550?redirect=false)

**Comment by christophstrobl** [comment]
MongoDB documentation gives no indication _sparse_ indexes will be removed nor did the option get deprecated.
