### ISSUE TITLE
"Couldn't find PersistentEntity" for subclass of superclass annotated with @Document  + auditing [DATAMONGO-2569]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3422]
**[Jozef Brokamp](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49709)** opened **[DATAMONGO-2569](https://jira.spring.io/browse/DATAMONGO-2569?redirect=false)** and commented

#### issue: error on save

A desired entity is not added to the list of PersistentEntities in the MongoMappingContext when the following criteria are met:
* desired entity is a subclass of a class annotated with `@Document`.
* desired entity is located in a different package (in our case separate project)
* repository for type (T) of superclass from different package
* Mongo auditing is enabled AND in use

Potentially we're hitting some bad practice that we should address, but this setup has worked in the past (months ago). The desired entity is rarely used, so we found out recently.

### case

It seems surprising that the issue only occurs with auditing enabled. This was our indication that there's an issue with spring-data(-mongodb). We'd expect similar behaviour, agreed?

### workarounds / pointers

There are 3 workarounds of which 1 is acceptable for us:
* remove annotation `@EnableMongoAuditing`
* remove auditing annotations like `@CreatedDate`
* add `@EntityScan` for package with the desired entities (= acceptable)

I've added a [reference url](https://github.com/jbrokamp/spring-data-mongodb-error-reproduction-project) to a GitHub repo with a minimal issue reproducing project

---

**Reference URL:** https://github.com/jbrokamp/spring-data-mongodb-error-reproduction-project.git

**Issue Links:**
- [DATACMNS-1780](https://jira.spring.io/browse/DATACMNS-1780) PersistentEntities should allow in flight metadata creation if the associated mapping context can be identified

1 votes, 3 watchers

**Comment by christophstrobl** [comment]
Fixed via spring-projects/spring-data-commons#462
