### ISSUE TITLE
watch changes to specific fields in MongoDB change stream with Spring Data Mongodb [DATAMONGO-2587]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#3439]
**[Tita](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49928)** opened **[DATAMONGO-2587](https://jira.spring.io/browse/DATAMONGO-2587?redirect=false)** and commented

Hello,

Im working  on an application that implement stream change for mongodb (Version 4.2.8)   , uning springboot mongodb reactive  and reactor kafka  to send all updated events to Kafka. i used an aggregation pipeline  to catch some updates fields on  my collection cdatabase, but unfortunately it does not work  ... here an example of my  filter aggregation .

  

```java
 public static TypedAggregation<ProductStoreStock> getAggregatForUpdatedSpecificFields1() {
		
    	Criteria StkAvailableForSaleCriteria = where("updateDescription.updatedFields.stockAvailableForSale.lastUpdateDate").exists(true)  
                                             .and("updateDescription.updatedFields.stockAvailableForSale.value").exists(true);

	Criteria updateOperationTypeCrit = where(AggregationPipelineConstant.OPERATION_TYPE).is(OperationType.UPDATE.getValue());			
        Criteria criteria = new Criteria().andOperator(StkAvailableForSaleCriteria, updateOperationTypeCrit);
	return Aggregation.newAggregation(ProductStoreStock.class, match(criteria));
	}
 
```

and my filter is called by this watcher :

```java
public ChangeStreamWithFilterAndProjection<ProductStoreStock> getWatcher() {
	    
		return mongoConfig.getReactiveMongoTemplate().changeStream(ProductStoreStock.class)
                    .watchCollection(CollectionName.PRODUCT_STORE_STOCK.getCollectionName())
                    .filter(AggregationUtils.getAggregatForUpdatedSpecificFields1()); 
	}
```

I get not change events. So here is the question: how can I define the Criteria to match updates on  **updatedField.x.y.z ??**

So, I tried to remove my stock filter while keeping only the operation type as 'update' and log of one of these change events looks like:

 

```json
   "updateDescription=UpdateDescription"{
      "removedFields="[

      ],
      "updatedFields="{
         "lastUpdateDate":{
            "$date":"2020-07-13T14:17:04.655Z"
         },
         "stockAvailableForSale.lastUpdateDate":{
            "$date":"2020-07-13T14:17:04.655Z"
         },
         "stockAvailableForSale.value":-5.05,
         "stockAvailableImmediate.lastUpdateDate":{
            "$date":"2020-07-13T14:17:04.655Z"
         },
         "stockAvailableImmediate.value":-5.05
      }
   },
```

 
I changed my filter using matchElemnt, so that it looks like this  :
 

```java
 public static TypedAggregation<ProductStoreStock> getAggregatForUpdatedSpecificFields1() {
	
		Criteria StkAvailableForSaleCriteria = where("updateDescription")
                         .elemMatch(where("updatedFields").exists(true))
                          .elemMatch(where("stockAvailableForSale.lastUpdateDate").exists(true));
    	
	Criteria updateOperationTypeCrit = where(AggregationPipelineConstant.OPERATION_TYPE).is(OperationType.UPDATE.getValue());			
        Criteria criteria = new Criteria().andOperator(StkAvailableForSaleCriteria, updateOperationTypeCrit);
	return Aggregation.newAggregation(ProductStoreStock.class, match(criteria));
	}
 
```

Result ->  No update event is catched !! 
Anyone can help me ?

Thanks in advance.

 

---

**Attachments:**
- [error.png](https://jira.spring.io/secure/attachment/28017/error.png) (_8.80 kB_)
- [pom.xml](https://jira.spring.io/secure/attachment/28014/pom.xml) (_13.21 kB_)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by bboze** [comment]
Hi, Looks that filter can not recognize cases when update is made on subelement, e.g. update of stockAvailableForSale.value directly instead of update of whole stockAvailableForSale filed.
  
If using provided  [reproducer](https://gist.github.com/christophstrobl/fc18a5880dfd125ea5346a4f3fe3ab4c#file-datamongo-2587-reproducer-java-L45) we make change on line 45 using this code:

 ` .apply(new Update().set("stockAvailableForSale.value", 100D)) `
  
test will not pass because filter will not match 
_UpdateDescription{updatedFields={"**stockAvailableForSale.value**": 100.0}}_
  
Only if whole stockAvailableForSale object/field is updated filter can match. And in that case it does not matter if we filter whole stockAvailableForSale or stockAvailableForSale .value, both will match.
_UpdateDescription{updatedFields={"**stockAvailableForSale**": {"**value**": 100.0, "lastUpdateDate": {"$date": "2024-10-29T11:34:52.013Z"}}}}_
  
  This behavior does not help in my case because I need to monitor changes only of specific subelements.

**Comment by bboze** [comment]
Worked for me with $getField

```
new Criteria().orOperator(
	where("updateDescription.updatedFields.fieldA").exists(true),
	expr(MongoExpression.create("{ $getField: {field: \"fieldB.subfield1\", input: \"$updateDescription.updatedFields\"}}"))
)
```
