### ISSUE TITLE
Search by alike() criteria is broken when type alias information is not available [DATAMONGO-2620]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3474]
**[Roman Puchkovskiy](https://jira.spring.io/secure/ViewProfile.jspa?name=rpuch)** opened **[DATAMONGO-2620](https://jira.spring.io/browse/DATAMONGO-2620?redirect=false)** and commented

It is possible to configure `MappingMongoConverter` in such a way that 'class' attribute is not saved to MongoDB. For example, the following setup

```java
MappingContextTypeInformationMapper typeInformationMapper = new MappingContextTypeInformationMapper(
 mappingContext);
DefaultMongoTypeMapper typeMapper = new DefaultMongoTypeMapper(DefaultMongoTypeMapper.DEFAULT_TYPE_KEY,
 singletonList(typeInformationMapper));

MappingMongoConverter converter = new MappingMongoConverter(NoOpDbRefResolver.INSTANCE, mappingContext);
converter.setTypeMapper(typeMapper);
```

would produce the following behavior: if an entity class is annotated with `@TypeAlias`, then the corresponding type alias is saved in `class` attribute to MongoDB, otherwise no such attribute is added.

This setup seems legitimate: one could decide that they do not need `class` attribute at all if they do not plan to ever use inheritance for some their entity classes.

But this setup makes `Criteria.alike(Example)` queries useless: they do not find anything. This happens, because `DefaultMongoTypeMapper#writeTypeRestrictions()` does not check whether `restrictedMappedTypes` is empty and adds `"{'class': {$in: [...]`"}} restriction even in such an (empty) case, which produces `"{'class': {$in: []`"}} which matches nothing as there is simply no `class` attribute.

This restriction is needed to make sure that only entities of the 'right' type are found. But if we don't have any type alias information, it seems natural to just drop the restriction

---

**Affects:** 2.2.9 (Moore SR9), 3.0.3 (Neumann SR3)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/884

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by rpuch** [comment]
I wonder why I have not received any notification about this issue...

**Comment by christophstrobl** [comment]
@rpuch Sorry about that! Might be due to the recent Jira to Github issues migration. The automation added a comment to the ticket in Jira but did not (to avoid noise) try to link authors to GH users when moving tickets over. 

We'll be addressing this issue by updating the documentation.
