### ISSUE TITLE
MappingMongoConverter appears to be using a Maps Value Type to serialise it's Key for Custom Map implementations [DATAMONGO-2650]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3503]
**[ed0906](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50640)** opened **[DATAMONGO-2650](https://jira.spring.io/browse/DATAMONGO-2650?redirect=false)** and commented

I have a custom map implementation

```java
class IdentityMap<T> : MutableMap<Identity, T>
```

And I have registered a

```java
@WritingConverter
 class IdentityWriteConverter : Converter<Identity, String>
```

and a

```java
@ReadingConverter
 class IdentityReadConverter : Converter<String, Identity>
```

so that Spring know how to handle the complex key type.

I use this in a `@Document`

```java
@Document
 class Cache(
 val id: String,
 val timestamps: IdentityMap<Instant> = emptyIdentityMap()
)
```

When saving this document, it generates the expected JSON, however when reading it, the MappingMongoConverter appears to be trying to use the Value Type (Instant in this case) to convert the Key (String) and ends up throwing a
`No converter found capable of converting from type String to type Instant` `ConverterNotFoundException` here:

https://github.com/spring-projects/spring-data-mongodb/blob/6ab43c239191b8e48b257671ffbbb91259d5366d/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L1180

For whatever reason, the two lines a bit higher in the method

```java
Class<?> rawKeyType = keyType != null ? keyType.getType() : null;
 Class<?> rawValueType = valueType != null ? valueType.getType() : null;
```

are both pulling the same type out, `Instant`. Even though the key type of my map implementation is an `Identity`.

Writing appears to work fine, but the above exceptions get thrown on read

---

**Affects:** 2.1.21 (Lovelace SR21)

**Issue Links:**
- [DATACMNS-1828](https://jira.spring.io/browse/DATACMNS-1828) TypeDiscoverer does not detect generic type arguments correctly

**Comment by christophstrobl** [comment]
Fixed by spring-projects/spring-data-commons#2243.
