### ISSUE TITLE
Allow AggregationExpression as part of group operation [DATAMONGO-2651]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#3504]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAMONGO-2651](https://jira.spring.io/browse/DATAMONGO-2651?redirect=false)** and commented

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/898

**Comment by mp911de** [comment]
Fixed via #898.
