### ISSUE TITLE
MappingMongoConverter causes NPE on bson decodeInt [DATAMONGO-2658]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3511]
**[davebarda](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50700)** (@davebarda) opened **[DATAMONGO-2658](https://jira.spring.io/browse/DATAMONGO-2658?redirect=false)** and commented

When I read an object I receive NPE, the exception caused on bson version 4.0.5(which is 3.0.5 supplement)

```java
org.bson.codecs.NumberCodecHelper#decodeInt 
```

on 

```java
BsonType bsonType = reader.getCurrentBsonType(); 
switch (bsonType) {  //bsonType is null here
```

I believe that the root cause is at org.springframework.data.mongodb.core.convert.MappingMongoConverter

```java
if (codecRegistryProvider != null) {

   Optional<? extends Codec<? extends S>> codec = codecRegistryProvider.getCodecFor(rawType);
   if (codec.isPresent()) {
      return codec.get().decode(new JsonReader(target.toJson()), DecoderContext.builder().build());
   }
}
```

as it doesn't set thecurrentBsonType

Unfortunately, I don't have the stack track, it happened a few days ago and I couldn't find the data which caused it, I thought to share it, maybe someone with more knowledge with the code can understand the issue.

Thanks

---

**Affects:** 3.0.5 (Neumann SR5)

**Comment by christophstrobl** [comment]
Can you please give us a bit more information about the error (Domain types involved, the source document,...), ideally a small project/gist with a failing test.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
