### ISSUE TITLE
DateFromParts millisecondsOf returns "milliseconds" as $dateFromParts function but it should be millisecond [DATAMONGO-2671]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-mongodb#3523]
**[taher435](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50782)** opened **[DATAMONGO-2671](https://jira.spring.io/browse/DATAMONGO-2671?redirect=false)** and commented

As mentioned in the mongodb issue log - https://jira.mongodb.org/browse/SERVER-30524 - the date from part operator for milliseconds was changed from "milliseconds" to "millisecond" (singular). However, when using the date part from spring mongodb, it still creates the aggregation query with "milliseconds" and hence the query fails with an unrecognized operator error. Based on the initial investigation, it feels like [this line](https://github.com/spring-projects/spring-data-mongodb/blob/c66ffeaa09400b3ec7455890edd9984609853260/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/aggregation/DateOperators.java#L1975) causes the issue

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-mongodb/pull/897

**Comment by mp911de** [comment]
Fixed via #897.
