### ISSUE TITLE
Enable Prometheus Metrics for Spring Mongo [DATAMONGO-2672]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3524]
**[Sandeep Kongathi](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50798)** opened **[DATAMONGO-2672](https://jira.spring.io/browse/DATAMONGO-2672?redirect=false)** and commented

Similar to jdbc / hikari prometheus metrics, Please enable metrics for Spring-mongodb
* Total Connections
* Max, Min, idle , pending connections
* acquire_seconds_max
* creation_seconds_count
* creation_seconds_max
* connections_timeout_total

---
No further details from [DATAMONGO-2672](https://jira.spring.io/browse/DATAMONGO-2672?redirect=false)

**Comment by christophstrobl** [comment]
This seems to be a request best addressed by the [MongoDB Drivers Team](https://jira.mongodb.org/projects/JAVA).
