### ISSUE TITLE
alike Criteria can't add andOperator

### ISSUE THREAD

**Issue by kioyong** [spring-projects/spring-data-mongodb#3544]
refer below code, It's work on spring-data-mongoDB 2.1.7.RELEASE, expect aFilter and bFilter will apply in query, but after upgrade to latest version(2.4.2), only bFilter work and aFilter will be ignore.
```java
Query query = new Query(new Criteria().alike(Example.of(aFilter)).andOperator(new Criteria(bFilter).is("bValue")));
```
there are workaround in my code is using query().addCriteria to replace  criteria.andOperator()
```java
Query query = new Query(new Criteria().alike(Example.of(aFilter))).addCriteria(new Criteria("bFilter").is("bValue"));
```
i believe this bug is caused by [DATAMONGO-2314](https://github.com/spring-projects/spring-data-mongodb/pull/771/files)  removed .alike  criteriaChain of code, please help to check, thanks.

this is reproduce issue example: https://github.com/kioyong/spring-data-mongodb-bug
just need to run mvn test to reproduce it.

**Comment by christophstrobl** [comment]
Thanks for reporting - we'll look into this.
