### ISSUE TITLE
org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.

### ISSUE THREAD

**Issue by airtaste** [spring-projects/spring-data-mongodb#3546]
I'm trying to upgrade the version of spring boot from 2.3.0 to 2.4.0. After updates I've tried to run my unit tests and got codec exception :disappointed: 

> Caused by: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.

	at org.bson.codecs.UuidCodec.encode(UuidCodec.java:72)
	at org.bson.codecs.UuidCodec.encode(UuidCodec.java:37)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:203)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:217)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:159)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:46)
	at org.bson.Document.toJson(Document.java:440)
	at org.bson.Document.toJson(Document.java:413)
	at org.bson.Document.toJson(Document.java:400)
	at org.springframework.data.mongodb.core.convert.MongoConverters$DocumentToStringConverter.convert(MongoConverters.java:241)
	at org.springframework.data.mongodb.core.convert.MongoConverters$DocumentToStringConverter.convert(MongoConverters.java:234)
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)

An example of a simplified project: https://github.com/airtaste/example/tree/master

Also, I've tried to use Spring Boot property spring.data.mongodb.uuid-representation and set it to 'standard', but the error still occurred. Furthermore, I tried to customize MongoClientSettings to include UuidRepresentation.STANDARD codec registry. Ineffectually.

It's a very odd issue.

Thanks in advance!

**Comment by christophstrobl** [comment]
Having a look at the example the error in `LessonActivityRepositoryUnitTest` results from the log statement invoking `org.bson.Document#toJson()` using the default `Encoder` that does not have the UUID setting. 
Have you tried providing an encoder that has the representation set? Something like `new DocumentCodec().withUuidRepresentation(UuidRepresentation.JAVA_LEGACY)`.

**Comment by airtaste** [comment]
Thanks for the quick response, Christoph! 
I tried to change the next line: 
`            log.debug 'Query: {}', aggregationBlock.toJson()
`
to: 
`log.debug` 'Query: {}', aggregationBlock.toJson( new DocumentCodec().withUuidRepresentation( UuidRepresentation.JAVA_LEGACY ))`

But the test still blowing up :(

**Comment by christophstrobl** [comment]
It seems the uuidRepresentation setting is not picked up by the registry. 
I had to do something like the following to make it work.
```java
MongoClientSettings clientSettings = MongoClientSettings.builder().uuidRepresentation(UuidRepresentation.JAVA_LEGACY).build();
CodecRegistry codecRegistry = MongoClients.create(clientSettings).getDatabase("test").getCodecRegistry();

aggregationBlock.toJson(codecRegistry.get(org.bson.Document.class))
```
You might want to report this issue to the [MongoDB Drivers Team](https://jira.mongodb.org/projects/JAVA/)

**Comment by airtaste** [comment]
@christophstrobl is there a way to customize DocumentCodec uuidRepresentation through spring-context/beans?
I know that MongoClientSettingsBuilderCustomizer exists. I tried to create its bean with the necessary uuidRepresentation, but in the toJson() method spring uses default DocumentCodec with UuidRepresentation.UNSPECIFIED uuid-representation type... How I could customize this? Thanks in advance!

**Comment by airtaste** [comment]
> It seems the uuidRepresentation setting is not picked up by the registry.
> I had to do something like the following to make it work.
> 
> ```java
> MongoClientSettings clientSettings = MongoClientSettings.builder().uuidRepresentation(UuidRepresentation.JAVA_LEGACY).build();
> CodecRegistry codecRegistry = MongoClients.create(clientSettings).getDatabase("test").getCodecRegistry();
> 
> aggregationBlock.toJson(codecRegistry.get(org.bson.Document.class))
> ```
> 
> You might want to report this issue to the [MongoDB Drivers Team](https://jira.mongodb.org/projects/JAVA/)

I found that when the encoder try to write value for a document that has UUID property the next code evaluated:

> ```Codec codec = registry.get(value.getClass());
   encoderContext.encodeWithChildContext(codec, writer, value);
```
>
In case when we write UUID value registry.get() method returned UuidCodec with default Unspecified UUID representation...
And then, when we try to encode value in the UuidCodec we have the next logic in the encode() method: 
>```if (uuidRepresentation == UuidRepresentation.UNSPECIFIED) {
            throw new CodecConfigurationException("The uuidRepresentation has not been specified, so the UUID cannot be encoded.");
        }```
>
Therefore we always will have such error :( 
Odd case... I am really confused.

**Comment by airtaste** [comment]
Eventually, I found the cause… So the problem is that in Spring Data 3.x when I use group like:

> Aggregation.group( FieldOne, FieldTwo, FieldThree )

I will have as result the next aggregation:

> Document { _id: Document { [FieldOne: X, FieldTwo: Y, FieldThree: Z] }, FieldOne: X, FieldTwo: Y, FieldThree: Z }

I have CodecConfigurationExcpetion because _id: [FieldOne: X, FieldTwo: Y, FieldThree: Z] can not be cast to UUID…

Composite ids from Aggregation.Group() are no longer mapped to their respective fields. Could you please provide some info on how to deal with such a case, and is there any way to reverse/configure this?

**Comment by christophstrobl** [comment]
I'm afraid I do not quite understand the last comment on composite ids. 
The `CodecConfigurationExcpetion` originates from the driver library when writing the debug output. You can try `SerializationUtils.serializeToJsonSafely`, which will suppress errors, but generate a slightly different output, for logging, or contact the [MongoDB Drivers Team](https://jira.mongodb.org/projects/JAVA/issues).
If there's problem with the conversion of the aggregation pipeline itself, please consider opening a new dedicated issue.
