### ISSUE TITLE
@CreatedAt annotation not working with nested document field

### ISSUE THREAD

**Issue by boy-ahoy** [spring-projects/spring-data-mongodb#3547]
I am using Spring Boot 2.4.0.

The POJO class mapped to collection is:

```
@SuppressFBWarnings(value = {"EI_EXPOSE_REP", "EI_EXPOSE_REP2"},
    justification = "This is a bean")
@Document(collection = "Posts")
@Data
@Builder
public class Post {

  @Id
  private String id;
  private ActorInfo actorInfo;
  private String text;
  private Media media;
  private int likes; 
  private Meta meta;
  @Version
  private Integer version;

  @Data
  @Builder
  public static class Meta {
    @CreatedDate // <-- this is not working
    private Instant createdAt;
    @LastModifiedDate // <-- this is not working
    private Instant updatedAt;
    private String event; // can be enum?
  }
}
```

I am using MongoRepository to save above POJO in DB using `save()`.
But I don't see the `createdAt` and `updatedAt` being populated in the collection.
This is what is being saved in collection:
```
{ "_id" : ObjectId("600fc6b23d5ebf145b7bbc0d"), "actorInfo" : { "_id" : "1", "role" : "USER" }, "text" : "Helo", "likes" : 0, "meta" : { "event" : "CREATED" }, "version" : 0, "_class" : "com.highstreet.socialmediaservice.adpater.output.type.Post" }
```

**Comment by christophstrobl** [comment]
Did you follow the setup to [enable auditing](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.auditing) in Spring Data MongoDB?

**Comment by boy-ahoy** [comment]
Thanks for sharing the link.
My understanding is I don't need to enable audit if I just want couple of auto generated timestamp field.
I am not using, for example, @CreatedBy field.

**Comment by christophstrobl** [comment]
You do not need to provide `AuditorAware` but still need to enable auditing. 
As per spring-projects/spring-data-commons#1712 auditing annotations on nested types are generally supported. However navigating the path `meta.createdAt` requires the property (`meta` in that case) to be non `null`.
If the issue persists a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) would help us triage the cause.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by boy-ahoy** [comment]
Yeah enabling auditing worked.

**Comment by alabotski** [comment]
I also faced such problem... It is not possible to store given information in a nested object

Judging by the questions on stackoverflow, I'm not the only one with this problem

- https://stackoverflow.com/questions/69389277/how-to-have-version-and-audit-information-inside-a-nested-object-in-springboot-m
- https://stackoverflow.com/questions/44208388/spring-data-mongodb-auditing-information-in-nested-object

**Comment by michelLinkapital** [comment]
> I also faced such problem... It is not possible to store given information in a nested object
> 
> Judging by the questions on stackoverflow, I'm not the only one with this problem
> 
> * https://stackoverflow.com/questions/69389277/how-to-have-version-and-audit-information-inside-a-nested-object-in-springboot-m
> * https://stackoverflow.com/questions/44208388/spring-data-mongodb-auditing-information-in-nested-object

I am needing this today. Unable to find a solution. WIll go manual setting ir and I don't like it

**Comment by xisvaldo** [comment]
No solution for this using nested/embeddable classes?

**Comment by xisvaldo** [comment]
I followed this [link](https://blog.mimacom.com/when-simple-audit-is-enough/) and could achieve using `@Embeddable`.
