### ISSUE TITLE
Générics constructor parameters don't apply converters

### ISSUE THREAD

**Issue by jolangloys** [spring-projects/spring-data-mongodb#3567]
Given a class which has a type parameter, and is not used as super class.
```java
public final class Wrapper<V> {
   private final V value;

   public Wrapper(V value) {
      this.value = value;
   }

   // Getters, etc...
}
```

When used in a constructor/setter for deserialization, with a type that requires the use of a converter, the converter is not called and the value is not converter, resulting in a `ClassCastException` later in the code.

For example, used in correlation with an Enum (which use a converter to be mapped to a String):
```java
@Document
public class Foo {
   private final Wrapper<FooEnum> myEnum;

   @PersistenceConstructor
   public Foo(Wrapper<FooEnum> myEnum) {
       this.myEnum = myEnum;
   }

   // Getters, etc ...

  public enum FooEnum { FOO, BAR }
}
```

I have reproduced this behaviour with other classes which use a converter.

This issue looks like the #2226 one, but here we're in the case were the wrapper class is not extended with a given type.

**Comment by christophstrobl** [comment]
thanks for reporting - we'll look into this!

**Comment by christophstrobl** [comment]
Which version are you using? 
Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to help us spot the issue? I might have missed something, but was not able to reproduce the issue with this [test](https://github.com/spring-projects/spring-data-mongodb/commit/78225dd2a1c3e65ab0b3a5b750864269d60d84c5).

**Comment by jolangloys** [comment]
I'am using version 2.3.2.
I'll try to make an example in the latest version.

**Comment by jolangloys** [comment]
I have made a simple example project: https://github.com/jolangloys/example-3567

Making the example made me realize that the problem only occur when the generic class extends its generic from a super class. In my example,  [Wrapper](https://github.com/jolangloys/example-3567/blob/main/src/main/java/example/Wrapper.java) extends [BaseWrapper](https://github.com/jolangloys/example-3567/blob/main/src/main/java/example/BaseWrapper.java).

**Comment by christophstrobl** [comment]
Thanks for the feedback - good catch!

**Comment by christophstrobl** [comment]
Upgraded the sample to boot-3 snapshots and verified it works as expected with the changes in data-commons linked above.
