### ISSUE TITLE
ConcurrentModificationException thrown when Collections.synchronized* styled collection or map is Concurrently write.

### ISSUE THREAD

**Issue by pcloves** [spring-projects/spring-data-mongodb#3582]
In my game server framework, I have a java bean, there are lots of volatile fields and also Collections.synchronizedList, Collections.synchronizedSet or Collections.synchronizedMap in the bean. I use a logic thread to writing the java bean. Meanwhile, I post the bean to a DB thread to persistent it to mongodb. (My purpose of using the volatile keyword and Collections.synchronized* collection is to make the changes can be seen in the DB thread, so it can be posted to the DB thread safely.)

When the Collections.synchronized* performs the *MappingMongoConverter.writeCollectionInternal* operation by the DB thread and the logic write thread performs an add/delete operation, a ConcurrentModificationException  will be thrown.

How deal with this issue? How about lock the **source** using the synchronized keyword before iterate it in MappingMongoConverter.writeCollectionInternal? If the **source** is a normal collection, CopyOnWrite* series collection, none thread will hold it's object lock, it won't leads to additional performance overhead. If it is a Collections.synchronized* collection, it will resolve my issue.

``` java
...

package org.springframework.data.mongodb.core.convert;

...

public class MappingMongoConverter extends AbstractMongoConverter implements ApplicationContextAware {

    ...
	
	@SuppressWarnings("unchecked")
	private List<Object> writeCollectionInternal(Collection<?> source, @Nullable TypeInformation<?> type,
			Collection<?> sink) {

		TypeInformation<?> componentType = null;

		List<Object> collection = sink instanceof List ? (List<Object>) sink : new ArrayList<>(sink);

		if (type != null) {
			componentType = type.getComponentType();
		}

		//How about use synchronized(source) before iterate the source?
		for (Object element : source) {

			Class<?> elementType = element == null ? null : element.getClass();

			if (elementType == null || conversions.isSimpleType(elementType)) {
				collection.add(getPotentiallyConvertedSimpleWrite(element,
						componentType != null ? componentType.getType() : Object.class));
			} else if (element instanceof Collection || elementType.isArray()) {
				collection.add(writeCollectionInternal(asCollection(element), componentType, new BasicDBList()));
			} else {
				Document document = new Document();
				writeInternal(element, document, componentType);
				collection.add(document);
			}
		}

		return collection;
	}

	...
}

```

**Comment by pcloves** [comment]
I build up a project to reproduce this issue:[spring-data-mongodb-test](https://github.com/pcloves/spring-data-mongodb-test)

**Comment by mp911de** [comment]
Thanks for the report. Following an imperative programming model comes with certain assumptions. One of them is that all processing happens on the same thread. In return, we don't expect mutations to the object being saved as the process of saving an object requires a consistent snapshot. 

Since Spring Data cannot make any assumptions over your code (e.g. when a document is ready to be saved or the point in time when your model is consistent), we can't really do anything here. We'd suggest not sharing a mutable instance across threads and use immutable objects instead. Alternatively, create a snapshot variant of the model you want to save and then call the save method.

**Comment by pcloves** [comment]
> Thanks for the report. Following an imperative programming model comes with certain assumptions. One of them is that all processing happens on the same thread. In return, we don't expect mutations to the object being saved as the process of saving an object requires a consistent snapshot.
> 
> Since Spring Data cannot make any assumptions over your code (e.g. when a document is ready to be saved or the point in time when your model is consistent), we can't really do anything here. We'd suggest not sharing a mutable instance across threads and use immutable objects instead. Alternatively, create a snapshot variant of the model you want to save and then call the save method.

As the suggestions you said, there are two alternative plan: using mutable objects or snapshot variant. The first plane is not suitable for my scenario, Let's talk about the second. In game server development, the object could be very huge(such as a player data in a MMOG). If I make a snapshot of the object, it will cause additional performance overhead, I will have to serialize the data(for example, serialize it to JSON) in my logic thread, after posting the snapshot to the DB thread, deserialize back again. 

What I'm looking for is to avoid serializing the object in my logical thread, So is there any other alternative plane? Very thanks.

**Comment by mp911de** [comment]
> I will have to serialize the data(for example, serialize it to JSON) 

There's no need to employ JSON or a different serialization technology. Creating a full in-memory copy of the object is fine.

**Comment by pcloves** [comment]
> > I will have to serialize the data(for example, serialize it to JSON)
> 
> There's no need to employ JSON or a different serialization technology. Creating a full in-memory copy of the object is fine.

Would you please give some more technical details? How creating a  in-memory copy of the object **efficiently in the logic thread**? Using java's native Object.clone()? It would be time-consuming, This is exactly what I am working on to avoid and solve.


PS1: The domain objects such as a player data would be very huge.
PS2:  In my game server framework, **the logic thread** mentioned above is mainly responsible for processing the game loop. Almost all of the actions are handled in the game loop, such as the players' request handling, So, any function call should not be too time-consuming, otherwise it will affect the PCU(peak concurrent users), which is a very important performance metric.
