### ISSUE TITLE
Support Evaluation Query Operators $expr.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3587]
See: [$expr](https://docs.mongodb.com/manual/reference/operator/query/expr/index.html)

Might be a good fit for `MongoExpression` from #3585 - `Criteria.expr(MongoExpression expression)` maybe?

Origin: [SO#66320786](https://stackoverflow.com/questions/66320786/spring-data-mongodb-criteria-for-expr)
Related: #2750

**Comment by divyajnu08** [comment]
Hi Christoph/Mark

Kindly find the pull request :
DATAMONGO-3587 - Support Evaluation Query Operators $expr
related to this issue and review the changes.
I also made a small change in the EvaluationOpertaors.Expr.toCriteriaDefinition() return type to Criteria kindly check if it's correct.

Thanks

**Comment by paulosalgado** [comment]
Any updates on this issue?

**Comment by divyajnu08** [comment]
Can i work on this issue?

**Comment by lancelot2018** [comment]
oh, buddy, when solve this problem?

**Comment by christophstrobl** [comment]
duplicate of: #2750
eventually be closed by: #4316
