### ISSUE TITLE
Use StringUtils.replace(…) instead of String.replaceAll(…) for mapKeyDotReplacement

### ISSUE THREAD

**Issue by chzhong** [spring-projects/spring-data-mongodb#3613]
When configured to use `mapKeyDotReplacement`, `MappingMongoConverter ` will use `String.replaceAll` to replace all dots in keys into specified replacement, which might cause unnecessary creation of `java.util.regex.Pattern` repeatly. This will lead to rapid GC serialize/deserialize a huge (>= 10MB) mongo document multiple times.

Codes in current version:
```java
	/**
	 * Potentially replaces dots in the given map key with the configured map key replacement if configured or aborts
	 * conversion if none is configured.
	 *
	 * @see #setMapKeyDotReplacement(String)
	 * @param source
	 * @return
	 */
	protected String potentiallyEscapeMapKey(String source) {

		if (!source.contains(".")) {
			return source;
		}

		if (mapKeyDotReplacement == null) {
			throw new MappingException(String.format(
					"Map key %s contains dots but no replacement was configured! Make "
							+ "sure map keys don't contain dots in the first place or configure an appropriate replacement!",
					source));
		}

		return source.replaceAll("\\.", mapKeyDotReplacement);
	}


	/**
	 * Translates the map key replacements in the given key just read with a dot in case a map key replacement has been
	 * configured.
	 *
	 * @param source
	 * @return
	 */
	protected String potentiallyUnescapeMapKey(String source) {
		return mapKeyDotReplacement == null ? source : source.replaceAll(mapKeyDotReplacement, "\\.");
	}
```

Suggestion:
Use `org.springframework.util.StringUtils#replace` or `org.apache.commons.lang3.StringUtils#replace(java.lang.String, java.lang.String, java.lang.String)` to replace dots instead.

**Comment by mp911de** [comment]
Good catch. Care to submit a pull request that makes use of `org.springframework.util.StringUtils#replace`?

**Comment by chzhong** [comment]
> Good catch. Care to submit a pull request that makes use of `org.springframework.util.StringUtils#replace`?

I'm behind a firewall so I can't submit a PR :-(

**Comment by mp911de** [comment]
Thanks for letting us know, we'll take care of this.

**Comment by HermanBovens** [comment]
@mp911de, note that this is a breaking change that, AFAICS, is not mentioned in any upgrade guide.  We were using `"\\+"` in order to replace the dot with `+` (because `+` needs to be escaped in regex) and that code, although it still compiled, was broken.
