### ISSUE TITLE
 SimpleMongoRepository save behavior

### ISSUE THREAD

**Issue by 12sandeep1994** [spring-projects/spring-data-mongodb#3619]
Consider the following Java Class.
```
class Transaction {
@Id
public String id;
public String firstProperty;
public String secondProperty;
} 

class TransactionRepository extends MongoRepository<TransactionInfo , String> {
...
}
```

In Java following code is executed : 
```
Transaction transaction = new Transaction("T1");
transaction.setFirstProperty("first");
transactionRepository.save(transaction);
```

Following document is created.
```
{
_id:123,
firstProperty: "first"
}
```

If this piece of code is executed later : 
```
Transaction transaction = new Transaction("T1");
transaction.setSecondProperty("second");
transactionRepository.save(transaction);
```

Expected Document : 
```
{
_id:123,
firstProperty: "first",
secondProperty: "second"
}
```
Actual Document:
```
{
_id:123,
secondProperty: "second"
}
```
From what I read in MongoDB docs I expect the document to be  updated with "secondProperty" but it results in the removal of "firstProperty" . I think the document is getting created again, instead of getting updated. Please let me know if I am missing something.

**Comment by christophstrobl** [comment]
On _save_ the repository inserts new or replaces existing documents with the given entity. 
Please use the [update API](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongodb-template-update) on `MongoOperations` to add values to documents.
