### ISSUE TITLE
Cannot use or operator with textCriteria

### ISSUE THREAD

**Issue by ovu** [spring-projects/spring-data-mongodb#3622]
Hello, I have the following query that works in mongo using a client, it uses an or operator which combines the result of a text index and a normal attribute. 

db.getCollection('person')
.find( 
{$or: [ { "hrNumber": "123"} , { $text: { $search: "123" } }]  }  )

However, I cannot create a query using the opOperator, because it only accepts Criteria and not TextCriteria. Why is that restriction? It is a feature that is not supported or there is another way create the query as described below?

       val query= org.springframework.data.mongodb.core.query.Query()
       query.addCriteria(Criteria().orOperator( textCriteria, hrNumberCriteria))

**Comment by kioyong** [comment]
@ovu  try use @Query annotation to customer query
```java
@Repository
public interface StoreRepository extends MongoRepository<Store,Integer> {
    
    @Query("{$or: [ { name: ?0 } , { $text: { $search: ?1 } }] }")
    List<Store> findByCustom(String name, String text);
}
```

**Comment by christophstrobl** [comment]
will be addressed by #3895 / #3884

**Comment by NerminKarapandzic** [comment]
is there any progress on this, the issues that you linked which are supposed to solve this are from 2021 and they're still open...

**Comment by ovu** [comment]
Hi, I am not working with that library anymore. I cannot say if the issue was solved.
