### ISSUE TITLE
Spring Data Mongodb Query by embedded document id

### ISSUE THREAD

**Issue by viniciusgati** [spring-projects/spring-data-mongodb#3624]
i am trying to query a model that contains a @Reference as attribute like:

``` 
public class TaskGroups {

    @Reference
    Branch branch;
 
.
.
.

}
```

and so on, then i have a query with more logic and code but in resume i have to filter by the field _id from Branch object, its just id on the object but on database its _id, ok no problem its normal behavior for the framework.

ok now the code that did not work:

```java

public class TaskGroupRepositoryImpl implements TaskGroupCustomRepository {

    private final MongoTemplate mongoTemplate;

    @Autowired
    public TaskGroupRepositoryImpl(MongoTemplate mongoTemplate) {
        this.mongoTemplate = mongoTemplate;
    }

    @Override
    public List<TaskGroup> query(TaskGroupDynamicQuery queryObject) {
        Query query = new Query();
        final List<Criteria> criterias = new ArrayList<>();

        criterias.add(Criteria.where("deleted").is(false));

        if (queryObject.getBranchId() != null) {
            criterias.add(Criteria.where("branch._id").is(new ObjectId(queryObject.getBranchId())));
        }

.
.
.
}
```

So when the code runs the query changes the field "branch._id" to only branch! and then no records returned...

With this behavior i needed to make a workaround, mapping the result to just Object and then converting to the taskGroup class , then the query has no modifications on the attribute names and the filter ocurs without problems.

Is this a bug? or its normal behavior to? is there any workaround to avoid this attribute name change when id fields?

Att.

**Comment by christophstrobl** [comment]
Thanks for reporting. The MongoDB module operates up `@DBRef` which is an `@Reference` but special to the store.
By using `@Reference` instead of `@DBRef` the `Branch` entity will not be linked, but embedded into the `TaskGroups` object. We're already working to enhance the support for linking (#3602) but for now please switch to `@DBRef` which should solve the issue.

**Comment by viniciusgati** [comment]
Hi thanks for your help, sadly i cant use dbref, i am migrating from it due to performance reasons.
But thanks anyway i will keep the workaround.
