### ISSUE TITLE
When inserting list of objects using addToSet and each, can't add with uniqueness of a variable of that object.

### ISSUE THREAD

**Issue by Naman55** [spring-projects/spring-data-mongodb#3626]
My class Watcher is as follows.

```java
@Data
public class Watcher {
    @Id
    @JsonProperty("sName")
    private String name;

    @JsonProperty("sMobileNo")
    private String mobileNo;

    @JsonProperty("sEmailId")
    private String emailId;
}
```

I have watchersList( List<Watcher> watcherList ) and i am adding it in db like this

```java
BasicDBList eachList = new BasicDBList();
eachList.addAll(watcherList);
update.addToSet(
        "watcherList",
        BasicDBObjectBuilder.start("$each", eachList).get()
);
```

But if i am having property "name" of class Watcher as duplicate in a list but having different mobile no and email. It is inserting both the objects of list even having same name. I want to make it unique with "name". How can i do this in spring?

**Comment by christophstrobl** [comment]
This is the behaviour of `$addToSet` as described in the MongoDB [documentation](https://docs.mongodb.com/manual/reference/operator/update/addToSet/#value-to-add-is-a-document).
> the document is a duplicate if an existing document in the array matches the to-be-added document exactly;
