### ISSUE TITLE
$floor isOrOrNor() return true 

### ISSUE THREAD

**Issue by fuxingjun** [spring-projects/spring-data-mongodb#3635]
$floor
method isOrOrNor() return true

![企业微信截图_16191698593453](https://user-images.githubusercontent.com/25798786/115850854-e28e8380-a458-11eb-96b7-fcfba68e5bdf.png)
![企业微信截图_16191697364958](https://user-images.githubusercontent.com/25798786/115850869-e8846480-a458-11eb-8611-265bde6779dc.png)

**Comment by christophstrobl** [comment]
Good catch - thanks for reporting!
It would be great if you'd use [code fences](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) instead of images next time.
