### ISSUE TITLE
NPE in PojoBuilderHelper class for object with custom annotation

### ISSUE THREAD

**Issue by Skiv1989** [spring-projects/spring-data-mongodb#3639]
Hi I have a project (Kotlin + Spring Boot Data) which fails with null pointer exception when upsert is happening. 
I've prepared test project to reproduce the issue: https://github.com/Skiv1989/spring-data-mongo-test

If you run the project it will try to store TestDto class, the class has an field with @SearchCriteria annotation. If I got correctly pojo converter thinks that annotation is a class field and trying to map it, which leads to NPE

Can you check please or advise how to avoid such exception? 

As temporary solution I've made copy of dto classes, but without annotations and then maps dto to dom before store, but classes are absolutely same, so I want to avoid this duplication.

**Comment by christophstrobl** [comment]
As far as I can tell from the provided sample, the problem does not originate from `spring-data-mongodb`, but the the `PojoCodec`. Please report issues with the codec in the MongoDB [Bug Tracker](https://jira.mongodb.org/browse/JAVA).

**Comment by Skiv1989** [comment]
@christophstrobl thank you for advice, I did creation: https://jira.mongodb.org/browse/JAVA-4119
