### ISSUE TITLE
GridFS in transactions

### ISSUE THREAD

**Issue by miroslavvojtus** [spring-projects/spring-data-mongodb#3640]
Hi Spring masters,

we are trying to use MongoDB 4.0 transactions in our project.
Unfortunatelly there is no out of the box transaction support for GridFS (or am I wrong?)

We attempted to create custom transaction aware MongoDatabaseFactory which enabled transactions in constructed GridFSTemplate but it immediately fails due to listIndexes operation which is not possible to disable in default GridFsBucketImpl.

Stack trace starts with:
```
com.mongodb.MongoCommandException: Command failed with error 263 (OperationNotSupportedInTransaction): 'Cannot run 'listIndexes' in a multi-document transaction.'
```

Do you have some hints how to use transactions with current GridFS implementation? Do you plan to implement full fledged transaction support?

Many thanks.

**Comment by christophstrobl** [comment]
Thanks for bringing this to our attention!

You can use `MongoDatabaseUtils` to interact with the transaction support and obtain session bound resources. The current `GridFsTemplate` implementation itself does not use this mechanism, but retrieves the `MongoDatabase` directly from the factory. Still, even if it did so, any `GridFsBucket` interaction would need to be called with the corresponding `ClientSession` which is not the case either. 

I do not think there's a reasonable way how this could work with the `GridFsTemplate` as it is today. 

Transaction support for GridFS clearly is something we'll support in the future. I'll take this to the team for further discussion and planning.

**Comment by miroslavvojtus** [comment]
Could you help me to intorduce transactions prior to your build in support?

My current attempt looks like:

1. Create Transaction aware MongoDatabaseFactory, which simply delegates most of methods to default mongoTemplate or uses MongoDatabaseUtils like `MongoDatabaseUtils.getDatabase(dbName, mongoDatabaseFactory)`
2. Create a GridFSTemplateProvider which simply instantiates the GridFsTemplate like `new GridFsTemplate(TransactionAwareMongoDbFactory.wrap(mongoTemplate.getMongoDatabaseFactory()), mongoTemplate.getConverter(), bucket)`

I thought that once the MongodDatabase produced by  TransactionAwareMongoDatabasefactory there is no need to propagate the ClientSession's. You said it is still necessary.

How would you suggest to retrieve current ClientSession in an eventual custom implementation of GridFsTemplate?
Unfortunately the MongoTransactionObject is protected (I can not read it from resource holder returned by TransactionSynchronizationManager) thus I did not find a way how to read/use it from somewhere?

**Comment by christophstrobl** [comment]
Sorry - got distracted by the `GridFSBucket` API that has some overloads accepting `ClientSession`. Looking at the implementation you're right, the proxied collection should be used, applying the session for you.

Unfortunately, having another look at the documentation, [MongoDB 4.4 does not support multi document transactions for GridFS](https://docs.mongodb.com/manual/core/gridfs/).

**Comment by miroslavvojtus** [comment]
Well this seems to be a pity for us then.
I have asked for a reasoning on the mongodb community forum: https://developer.mongodb.com/community/forums/t/gridfs-does-not-support-multi-document-transactions/105984
