### ISSUE TITLE
Inconsistent nullability of read() in templates: not sure if mapper can skip a document

### ISSUE THREAD

**Issue by pkubowicz** [spring-projects/spring-data-mongodb#3648]
In spring-data-mongodb 3.1.8 ReactiveMongoTemplate.ReadDocumentCallback#doWith includes code to deal with null:
```java
			T source = reader.read(type, document);
			if (source != null) {
                        // …
			}

			return Mono.empty();
```
This code suggests that I can write a custom reader that returns null for elements that cannot be mapped and should be skipped.

However, this is not true. org.springframework.data.convert.EntityReader is not annotated with `@Nullable`, so `source` can never be null. In Kotlin, the compiler won't allow writing an implementation returning null.

## Use case
By default it is impossible to use `findAll` on a collection that contains one malformed document: mapping exception will crash the operation and no elements will be emitted. I am looking for a way to ignore invalid documents and return remaining ones.

If I am mistaken and there is a way to write a custom mapper that is able to skip documents that cannot be mapped, please let me know.

**Comment by mp911de** [comment]
While `EntityReader` should never return `null`, there are possibilities where a `Converter` might return `null` as Spring's `Converter` may return `null`.

> In Kotlin, the compiler won't allow writing an implementation returning null.

Actually, Kotlin suggests the right thing to do.

> I am looking for a way to ignore invalid documents and return remaining ones.

Spring Data actually never intended to support skipping results, it happened more by accident. I'd suggest registering a lifecycle listener that allows you to update the document prior to mapping it.

**Comment by pkubowicz** [comment]
Thanks for the explanation. Do you plan to remove the null-handling branch from the code then?

**Comment by mp911de** [comment]
We decided to revisit the mentioned code paths and to remove code paths that allow for `null` as a result of `EntityReader`. Thanks for making us aware of this.
