### ISSUE TITLE
Nested data structure update (numeric keys)

### ISSUE THREAD

**Issue by MarcoFlo** [spring-projects/spring-data-mongodb#3652]
When I try to update a nested data structure with numeric keys, the operation doesn't turn out as expected and the nested structure is not preserved.

An example:
`new org.springframework.data.mongodb.core.query.Update().set("node.1.59.21", dataEntity)`
![insert_err](https://user-images.githubusercontent.com/23399429/118461589-1da17100-b6fe-11eb-878d-412b3f6925b9.jpg)

This behaviour was not present in spring-boot-starter-data-mongodb/2.3.9.RELEASE, but from that version onwards yes (2.3.10.RELEASE and 2.4.5 tested)

The java driver (4.0.5, 4.0.6, 4.1.2) itself has been excluded, due to the fact
`com.mongodb.client.model.Updates.set("node.1.59.21", dataEntity.toDocument())`
works as expected and it's my current workaround.

**Comment by christophstrobl** [comment]
Thanks for reporting. 
Can you please share the context this is used in. The domain types and the actual update invocation. A [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) would be ideal.

The following seems to work as expected with `spring-data-mongodb:3.1.8` used by `spring-boot:2.4.5`.

```java
Update update = new Update().set("node.1.59.21", new Document("the", "value"));
Document mappedUpdate = updateMapper.getMappedObject(update.getUpdateObject(), context.getPersistentEntity(Model.class));
assertThat(mappedUpdate).isEqualTo(Document.parse("{ '$set' : { 'node.1.59.21' : {'the' : 'value' }}}"));
```

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by MarcoFlo** [comment]
@christophstrobl I'm not really able to pin point the reason, but I'm no more able to reproduce this behaviour and now it's all working as expected.

I suppose the issue can be closed.
Sorry for the late and kind of response
