### ISSUE TITLE
ParameterBindingDocumentCodec: Nested List values parsing bug

### ISSUE THREAD

**Issue by pruv** [spring-projects/spring-data-mongodb#3653]
ParameterBindingDocumentCodec codec is not parsing query correctly when nested lists are involved. Below is an example query where `["$_id"]` in concatArrays section is being parsed as string `$_id`.

`{$project: { domainIds: { $concatArrays: [ "$children._id", ["$_id"] ] } }}`

This gets translated to 
`{"$project": {"domainIds": {"$concatArrays": ["$children._id", "$_id"]}}}`

Below are the links for code where this is happening. 
[readValue](https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/util/json/ParameterBindingDocumentCodec.java#L346) and [readList](https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/util/json/ParameterBindingDocumentCodec.java#L368)

Please let me know if there any other alternatives to make this work correctly or any other solution

**Comment by christophstrobl** [comment]
Which version of spring-data-mongodb are you using? 
This looks similar to #3488 which was fixed in 3.0.5 (via #888).

**Comment by pruv** [comment]
I am using spring boot `2.2.2.RELEASE` which is pulling `spring-data-mongodb:2.2.3.RELEASE`. 
what version of spring boot pulls spring-data-mongodb 3.0.5?

**Comment by christophstrobl** [comment]
data-mongo `3.0.5` is pulled in by boot `2.3.5`. In case you need to stick to the boot `2.2.x` line, you can use boot `2.2.11` which comes with a data mongodb version that also includes the fix.
Boot dependencies can be looked up in the [reference documentation appendix](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html).

**Comment by pruv** [comment]
@christophstrobl boot `2.2.11` is pulling the fix and it is working fine now. Thank you very much!

**Comment by christophstrobl** [comment]
Thanks for the feedback!
