### ISSUE TITLE
BsonDiscriminator

### ISSUE THREAD

**Issue by DaatEmet** [spring-projects/spring-data-mongodb#3655]
Spring data mongodb supports BsonDisriminator? If yes, how it work?

**Comment by christophstrobl** [comment]
We use GitHub issues to track bug reports and feature requests. Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/spring-data-mongodb) for questions. 
Nevertheless `BsonDisriminator` does not seem to be part of the MongoDB Java Driver nor server API. So, no. It's not supported.
