### ISSUE TITLE
Blocking program startup when adding a new composite index using @CompoundIndex

### ISSUE THREAD

**Issue by warmliX** [spring-projects/spring-data-mongodb#3657]
Excuse me，I want to ask you some problems about spring-mongo. When I added a new index to the original Document entity class using spring-mongo and restarted the service, my spring program got stuck in the steps to create an index in MongoPersistentEntityIndexCreator. It is may be due to a lot of data in the table corresponding to this entity class. I checked the question list of spring-data-mongo, but found no helpful information. It seems that the only way to avoid this problem is to disable automatic index creation by setting spring.data.mongodb.auto-index-creation=false. For this, is there any other way to make the "create index" step into asynchronous execution instead of stopping when my program starts? Looking forward to receiving your reply. Thank you.

**Comment by IsNull** [comment]
You can (should actually) create indexes via 

```java
@EventListener(ApplicationReadyEvent.class)
public void initIndicesAfterStartup() {

        var indexOps = mongoOperations.indexOps(Customer.class);

        indexOps.ensureIndex(
                TextIndexDefinition
                        .builder()
                        .named("TextIndex")
                        .onField("name")
                        .onField("validInterval.start")
                        .build()
        );
    }  
```
Example: https://gitlab.com/elderbyte/public/examples/spring-mongo-index-issue/-/blob/main/demo-starter-mongo/src/main/java/com/elderbyte/starter/demo/domain/customers/CustomerIndexConfiguration.java

**Comment by mp911de** [comment]
Setting `@Indexed(background=true)` enables background creation. In general, we recommend not using `@Indexed` if your database contains a significant amount of data and move index creation towards an external admin task.
