### ISSUE TITLE
Add manullay populate subdocument support

### ISSUE THREAD

**Issue by shengzhou1216** [spring-projects/spring-data-mongodb#3663]
reference https://mongoosejs.com/docs/populate.html

**Comment by christophstrobl** [comment]
Please take the time to elaborate the goal of your request.
Consider existing functionality for linking documents/projections and tell us why those do not fit your needs.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
