### ISSUE TITLE
connection is not equally created over each secondary node in a replicas set MongoDB cluster 

### ISSUE THREAD

**Issue by suesunss** [spring-projects/spring-data-mongodb#3664]
Hi,

I have a 3 node mongodb replica set cluster, with one node handles write requests and two others handle read requests.

I have also a Spring Boot web server (with Spring Data **MongoDB 3.0.6.REALEASE**), which exposes a simple READ operation over a collection: 

`db.myCollectionName.aggregate([{ "$sample" : { "size" : 100}}, { "$project" : { "myFieldName" : 1, "_id" : 0}}])`

This query use `$sample` operator to randomly select 100 documents over a collection having about 100m documents, and project one field.

I use JMeter to do pressure test over the application, with `ReadPreference.secondaryPrefererd()` configured, it turns out that each secondary node can handle about 600 ops. However, the strange thing is:

**One secondary node has 100 more connection count over another, whereas can only handles the same #Ops**. The node which bears less connection count also has much less active reads.

We can always repeat this problem if we try to retest more times.

Each secondary node has exactly the same software configuration and hardware setting.

Can anyone give some tips ?

BTW, I notice there is a server selecting algorithm: 
https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst

I tried to increase `localThresholdMS` however it does not work.

**Comment by mp911de** [comment]
Care to elaborate how Spring Data is involved? This sounds being a driver question.

**Comment by suesunss** [comment]
> Care to elaborate how Spring Data is involved? This sounds being a driver question.

Basically I am using Spring Data MongoDB to handle the conneciton setup and query the collection. I am curious about if Spring Data comes down to the **Sever Selection** issue.

**Comment by mp911de** [comment]
Thanks for the detail. Spring Data isn't really in the business of configuring the MongoDB client, our components are ideally configured with a Client instance (or `MongoDatabase`) and we stay away from the internals as much as possible. Attaching read preference/write concerns is the maximal level of runtime involvement.

There are support classes in Spring Data MongoDB to create a client instance using `MongoClientSettings` but that is mostly to ease configuration and not to register Spring components into the driver.

**Comment by suesunss** [comment]
> Thanks for the detail. Spring Data isn't really in the business of configuring the MongoDB client, our components are ideally configured with a Client instance (or `MongoDatabase`) and we stay away from the internals as much as possible. Attaching read preference/write concerns is the maximal level of runtime involvement.
> 
> There are support classes in Spring Data MongoDB to create a client instance using `MongoClientSettings` but that is mostly to ease configuration and not to register Spring components into the driver.

Thanks for the reply. Per your detail, it should be a driver-side issue. I will try to figure out in MongoDB community.

We can close the issue now.
