### ISSUE TITLE
Documentation references outdated `Mongo` client

### ISSUE THREAD

**Issue by XSun771** [spring-projects/spring-data-mongodb#3666]
[Spring Data MongoDB - Reference Documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.mongo-java-config)

[image](https://i.loli.net/2021/06/13/tiYQVxZ2Bvpblzo.png)

**Comment by mp911de** [comment]
![tiYQVxZ2Bvpblzo](https://user-images.githubusercontent.com/1035015/121906747-b3dfab80-cd2b-11eb-9509-01b8f7436ce7.png)
