### ISSUE TITLE
Add readPreference secondaryPreferred to QueryCursorPreparer

### ISSUE THREAD

**Issue by peterfouquet0001** [spring-projects/spring-data-mongodb#3669]
Hello,
we will execute find queries on the secondaries in our mongo cluster, but the CursorOption SECONDARY_READS is mapped to primaryPreferred in MongoTemplate.QueryCursorPreparer.getReadPreference. The mapping isn't customizable and the code isn't extendable by subclassing the MongoTemplate.
Please add a mapping for CursorOption SECONDARY_PREFRERRED with secondaryPreferred.
Kind regards
Peter

**Comment by mp911de** [comment]
`CursorOption` is a legacy from the early MongoDB driver where `DBCollection.find(…)` accepted a flag parameter called `option`. See the historical Javadoc of [`QUERYOPTION_*`](https://www.javadoc.io/static/org.mongodb/mongo-java-driver/2.0/com/mongodb/Bytes.html#QUERYOPTION_SLAVEOK). The modern driver with `MongoCollection` does not accept options at all, however, the mentioned code is in place for compatibility reasons. 

If you want to customize `ReadPreference`, please set it directly on `MongoTemplate`

**Comment by peterfouquet0001** [comment]
How can I set a different ReadPreference for a single query?
With the mongo driver i use mongoCollection.withReadPreference(ReadPreference.secondaryPreferred()) to execute these query on a secondary, while all other queries where execute with the defaultReadPreference on the primary.
When I change the read preference for the mongo template, I change the read preference for all queries.
Also i will configure these option for a query with the @Meta annotation.

**Comment by mp911de** [comment]
You could override `MongoTemplate`'s `MongoCollection<Document> prepareCollection(MongoCollection<Document> collection)` to supply a read preference based on the collection. Other than that, there's no method that would accept sufficient context to determine a `ReadPreference`.

**Comment by peterfouquet0001** [comment]
When I override the prepareCollection I can't set the read preference for a single query and i can't set the read preference for an annotation based query, because these queries are using the mongo template implizit.

**Comment by mp911de** [comment]
Let me take your request to our team to check whether we can come up with something. For `WriteConcern` we have a `WriteConcernResolver` taking a `MongoAction` as context parameter.

**Comment by peterfouquet0001** [comment]
HI, 
do you have a solution to configure the ReadPreference for a single query?
Kind regards
Peter

**Comment by mp911de** [comment]
Right now, we do not have the means to configure `ReadPreference` on a per-query basis. Introducing a `ReadPreferenceResolver` is something that we want to explore in combination with a possibility of declarative configuration that can be used with repository query methods.

**Comment by Liveitabhi14** [comment]
And why does the SECONDARY_READS cursor option return a primaryPreferred() ReadPreference?
Shouldn't it return either secondary() or secondaryPreferred() ?

Maybe I am missing something.. can anyone explain

**Comment by mp911de** [comment]
Fixed via #4286.
