### ISSUE TITLE
Memory Leak: instances of UnwrappedMongoPersistentProperty are accumulating in PreferredConstructor.isPropertyParameterCache

### ISSUE THREAD

**Issue by rogeriomgatto** [spring-projects/spring-data-mongodb#3683]
UnwrappedMongoPersistentProperty doesn't implement equals() and hashCode() and is used as a key in PreferredConstructor.isPropertyParameterCache.

**Comment by christophstrobl** [comment]
Thanks for reporting!

**Comment by rogeriomgatto** [comment]
Forgot to mention:
spring-data-mongodb version 3.2.1
mongodb-driver-sync version 4.2.3

**Comment by rogeriomgatto** [comment]
Regarding urgency: this is a fast leak, MappingMongoConverter triggers this leak for read operations.  Kubernetes is killing my pods.
