### ISSUE TITLE
Support for Document/Domain objects in an Update clause/BulkOperations 

### ISSUE THREAD

**Issue by cyrilmacphilip** [spring-projects/spring-data-mongodb#3699]
- Currently, when we might want to upsert a list of documents in a collection we have a few options to choose from. In the use-case where we might want to upsert all the attributes, we have an option to generate an update clause probably by creating a `Document` object from the custom domain object(Annotated with `@Document`) and passing on the data to `public static Update fromDocument(Document object, String... exclude) `.
- Note: I am using an older version of spring-data where I have to pass a `DBObject` and I am using the `MongoConverter` class to convert my domain object to a `DBObject`.
- While this works fine, it took me some time to understand what happens under the hood and work my way around this. This seemed time-consuming and not very user-friendly, especially when we have options like `save(objectToSave)` when we want to work with a single document.
- I would like the team's opinion on a couple of possible enhancements I had in mind:
- First option: We could introduce something like this: `public static Update fromDocument(Object object, String... exclude)` within the update clause that would internally convert it to a `Document` object and maybe invoke the existing `fromDocument(Document object, String... exclude)` method.
- Second option: We could further abstract this and introduce something like: `BulkOperations upsert(List<? extends Object> documents);` with the BulkOperations interface that would basically achieve something similar.
- While the existing options for updates are very useful I think the addition of something like this might be helpful in the future and make the interaction for bulk updates a lot simpler.
- Do let me know if you'd require more code samples if the description is not clear enough.
- Looking forward to opinions/suggestions on the same, would like to contribute if we are able to get some alignment on this. 
Thanks!

**Comment by mp911de** [comment]
To clarify your request: You're asking for a bulk upsert?

Have you tried `BulkOperations.replaceOne(Query, Object, FindAndReplaceOptions)` method accepting `FindAndReplaceOptions` where you can enable the `upsert` flag?

**Comment by cyrilmacphilip** [comment]
> To clarify your request: You're asking for a bulk upsert?
> 
> Have you tried `BulkOperations.replaceOne(Query, Object, FindAndReplaceOptions)` method accepting `FindAndReplaceOptions` where you can enable the `upsert` flag?

Thanks for the suggestion, the version I am currently using does not seem to have this option. Will try to upgrade and test it out. It looks like this option should help in my usecase. You can close the issue, will open another one in the future if required. Thanks!

**Comment by mp911de** [comment]
`BulkOperations.replaceOne` was introduced with version 2.2.
