### ISSUE TITLE
Add support for `$atan`, `$atan2` and `$atanh` aggregation operators

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3709]
Available since MongoDB 4.2.

* https://docs.mongodb.com/manual/reference/operator/aggregation/atan/
* https://docs.mongodb.com/manual/reference/operator/aggregation/atan2/
* https://docs.mongodb.com/manual/reference/operator/aggregation/atanh/

**Comment by petitcl** [comment]
Hi ! I am interested in handling this issue ! Is it ok for you ?

**Comment by mp911de** [comment]
@petitcl there was already a pull request #3794 submitted by the time of your comment.
