### ISSUE TITLE
Add support for $rand aggregation operator.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3724]
This is a `first-timers-only` issue.

This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. 
Thanks!

## Problem
MongoDB 4.4.2 introduced a new aggregation operator `$rand` that we want to support via the Aggregation Framework.
Details about the operator can be found within the MongoDB [Reference Documentation](https://docs.mongodb.com/manual/reference/operator/aggregation/rand/).

## Solution

Introduce `MathOperators` to the `org.springframework.data.mongodb.core.aggregation` package and add a `Rand` type that implements `AggregationExpression`. You may want to have a look at `ArithmeticOperators` to get an impression what this could look like.
Update `org.springframework.data.mongodb.core.spel.MethodReferenceNode` to add SpEL support for the operator via a `rand()` method. 

Make sure to provide tests that assert the expression can be used within an pipeline and produces the desired command.
Again you may want to have a look at existing examples (eg. `ArithmeticOperatorsUnitTests` & `SpelExpressionTransformerUnitTests`).

## Steps to Fix
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and create a pull request

**Comment by ahmedmq** [comment]
@christophstrobl - Can I work on this issue please?

**Comment by christophstrobl** [comment]
sure - please assign it to yourself so others know you're taking care of it.
Happy to help if questions arise. The part with the `MethodReferenceNode` may benefit from changes in #3741 adding `emptyRef()`.

**Comment by ahmedmq** [comment]
@christophstrobl - I am not seeing the button to assign the issue to myself, probably an access issue. could you assign it to me please.

**Comment by ahmedmq** [comment]
@christophstrobl  - Any reason why we do not want to have the new `rand()` aggregation as part of the existing `ArithmeticOperators`? I was thinking we would mostly use the `rand()` operator to perform some arithmetic computation as part of the aggregation pipeline.

**Comment by christophstrobl** [comment]
It's fine to have them there. In case we want to introduce `MathOperators` at some point we can still delegate.
