### ISSUE TITLE
Add support for `$sin` and `$sinh` aggregation operators

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3728]
Available since MongoDB 4.2

* https://docs.mongodb.com/manual/reference/operator/aggregation/sin/
* https://docs.mongodb.com/manual/reference/operator/aggregation/sinh/

**Comment by jagadeeshkoka** [comment]
How can I work on these requests ? I would like to contribute..

**Comment by christophstrobl** [comment]
@jagadeeshkoka thanks for reaching out. There's already a PR (#3755) that covers those operators.
In general, just like this :) - pick one of the open issues, let us know you'd be interested and feel free to submit a PR.

**Comment by jagadeeshkoka** [comment]
@christophstrobl thanks for the reply, so if PR is created, that means someone else is already working on it ? so we should look for open issues and create a PR with proposed solution ? once the PR is being approved we can work on it ?

**Comment by christophstrobl** [comment]
Sorry it took so long to come back to you. We've got labels for like [ideal-for-contribution](https://github.com/spring-projects/spring-data-mongodb/labels/status%3A%20ideal-for-contribution) that should help you look for open tickets. If the ticket does not have an assignee nor a PR linked, that's the ones you might be interested in. Just tell us you'd like to work on something specific so we can assign the issue to you. when done open a PR for it.
