### ISSUE TITLE
$merge in aggregate

### ISSUE THREAD

**Issue by YeungRay** [spring-projects/spring-data-mongodb#3743]
in AggregateIterableImpl.getOutNamespace method
`BsonDocument mergeDocument = lastStageDocument.getDocument("$merge");`
this line dont consider String type when  $merge use the simplified form , like { $merge: “xxx” }
Although users can avoid the problem , but it's a bug

**Comment by christophstrobl** [comment]
Thanks for reporting - we'll take care of this.

**Comment by christophstrobl** [comment]
This is a MongoDB driver internal issue - Please follow updates in the MongoDB bug tracker for [JAVA-4258](https://jira.mongodb.org/browse/JAVA-4258).

**Comment by jyemin** [comment]
Thanks for the report.  We'll get a fix into the next patch release of the driver.
