### ISSUE TITLE
AggregationOptions fails on using index name.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3747]
`AggregationOptions#fromDocument` fails to read index name but expects a `Document`. 

Depends on: #3778

**Comment by christophstrobl** [comment]
Depends on: [JAVA-4262](https://jira.mongodb.org/browse/JAVA-4262)

**Comment by chuckgregoryACES** [comment]
The two dependencies are met. Can this ticket be brought out of the graveyard?

**Comment by christophstrobl** [comment]
@chuckgregoryACES thanks for the heads up. This has been resolved via #4243.
