### ISSUE TITLE
QuerydslMongoPredicateExecutor findAll() tries to get offset for a Pageable.unpaged()

### ISSUE THREAD

**Issue by sfgvieira** [spring-projects/spring-data-mongodb#3751]
Hi,
When passing a Pageable.unpaged() to findAll(Predicate predicate, Pageable pageable) in the QuerydslMongoPredicateExecutor, it will try to call the pageable.getOffset() which  will to a java.lang.UnsupportedOperationException.

I suppose this is a bug because the documentation of the findAll mentions that the pageable can be unpaged.

**Comment by mp911de** [comment]
What would you expect as a result from such a call?

**Comment by sfgvieira** [comment]
My expectation is that if the provided pageable is unpaged, then it would not apply pagination to the result and instead it would provide me an unpaged page with the available contents.

The `PageableExecutionUtils.getPage(...)` call seems to already do this but it never gets to be executed because it fails at the `applyPagination(query, pageable)` due to the call to `pageable.getOffset()` which results in the java.lang.UnsupportedOperationException when the pageable is unpaged.

So as it is right now, yes in can take a Pageable.unpaged() but it will always result in a java.lang.UnsupportedOperationException, therefore it doesn't seem useful to me (unless I am missing something :) )

**Comment by mp911de** [comment]
Thanks a lot. By checking the other implementations, `Pageable.unpaged()` should indeed return all results. The JPA module does already the right thing and we need to fix the issue in MongoDB.
