### ISSUE TITLE
Issue with autogenerating JSON schema based on `@Document` with `MongoJsonSchemaCreator`

### ISSUE THREAD

**Issue by MateuszWicherski** [spring-projects/spring-data-mongodb#3766]
Hi!

I think that `MongoJsonSchemaCreator` is treating `collection like` fields of a `@Document` class incorrectly:
- for simple and enum lists (e.g. `List<String>`, `List<Enum>`), information about expected `array` type is lost and they are included in a resulting schema as `array`
- complex lists (e.g. `List<ObjectType>`), are resolved as an `object` with properties taken from `ObjectType` - the information that it is an `array` is lost completely (and results in not being able to insert correct document into the database).

Minimal example to reproduce the issue can be found here:
https://github.com/MateuszWicherski/spring-data-mongodb-bug

**Comment by jagadeeshkoka** [comment]
@MateuszWicherski why are you not using `@Feild` annotation if you want to include any embedded documents inside a document ?

**Comment by christophstrobl** [comment]
Thanks for bringing this up. We'll have a look!

**Comment by christophstrobl** [comment]
We updated the `MappingMongoJsonSchemaCreator` to include _items_ in case you want to give #3837 a try.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by MateuszWicherski** [comment]
Hi! Sorry for delay, I had no time to check it. The fix looks nice, I have checked it against my code and it is working as expected. 5 star job!

**Comment by christophstrobl** [comment]
@MateuszWicherski thanks for giving it a try!
