### ISSUE TITLE
single fetch with skip and limit returns wrong result

### ISSUE THREAD

**Issue by MadyZaid** [spring-projects/spring-data-mongodb#3770]
I have MongoDB collection that have 4 documents, which I am running a query against it. The query fetches one document at a time. 

the first 2 fetches return the expected result, while the last 2 fetches are fetching the third document only, while the last document is not being fetched at all.

Note: I have not investigated the issue, so I am not really sure if the issue is Spring-data or MongoDb engine issue.

below is java code that will produces the issue.

Sort sort = new Sort(Sort.Direction.ASC, "createdDate"); //createdDate is a property in my document
       for(int i = 0; i < 4;  i++) {
            Query query = new Query();              
            query.skip(i);
            query.limit(1);
            query.with(sort);
            List<A> As = mongoOperation.find(query, A.class);
        }

        
        
 below is my dependencies

    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.1.RELEASE</version>
		<relativePath/>
	</parent>
	
	<properties>
		<querydsl-mongo.version>4.2.1</querydsl-mongo.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>

                 <dependency>
			<groupId>org.springframework.plugin</groupId>
			<artifactId>spring-plugin-core</artifactId>
			<version>2.0.0.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-mongodb</artifactId>
			<version>${querydsl-mongo.version}</version>
		</dependency>

		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>${querydsl-mongo.version}</version>
		</dependency>
		</dependencies>

**Comment by MadyZaid** [comment]
i investigated and it is mongo db issue not spring data

**Comment by christophstrobl** [comment]
Thanks for letting us know!
