### ISSUE TITLE
@MongoId data type mismatch

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3784]
Spring data 3.3.0-M2

Before I use the ObjectId type for _id field on my documents and I want to change data type to string. I have prepared a mongodb script from ObjectId to String. After running the script all data converted to string type and  then added new data to documents from the application nothing changed. All _id fields have been stored as ObjectId.

Old implementation

```
@MongoId(targetType = FieldType.OBJECT_ID)
private String id;
```

New Implementation

```
@MongoId(targetType = FieldType.STRING)
private String id;
```

**Comment by christophstrobl** [comment]
I've not been able to reproduce the issue based on the given information. 

```java
class WithExplicitTargetTypes {

	@MongoId(targetType = FieldType.STRING)
	String stringAsString;
}

@Test // GH-3784
void mapsIdValueToExplicitTargetType() {

	WithExplicitTargetTypes source = new WithExplicitTargetTypes();
	source.stringAsString = new ObjectId().toString();

	org.bson.Document target = new org.bson.Document();
	converter.write(source, target);

	assertThat(target.get("_id")).isEqualTo(source.stringAsString);
}
```
I might be missing something here. Please provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by blueiceprj** [comment]
Ok. I see. You assign to value manually on your code. But I didn't assign any value to id field when insert document. It was null value. If the id field is null then mongodb setting automatically ObjectId. I think spring can inject data to there.

But it is not easy to use this way.

**Comment by blueiceprj** [comment]
Now I have resolved on event listener with BeforeSaveEvent. Thank you.

```
        @Override
	public void onBeforeSave(BeforeSaveEvent<T> event)
	{
		if (StringUtil.isBlank(event.getSource().getId())) {
			event.getSource().setId(new ObjectId().toHexString());
		}
		log.info("Before save collection name:" + event.getCollectionName());
		super.onBeforeSave(event);
	}
```

**Comment by jagadeeshkoka** [comment]
I think there should be a way to tell spring data to use `String` instead of `ObjectId` even though you specify the type in `@MongoId()` 

Instead of relying on listener, there should be a better way to do this. Please suggest
