### ISSUE TITLE
New feature or extending @DocumentReference annotation

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3789]
Hello,
I believe that @DocumentReference is useful and very good feature to product development. Thank you your efforts.
However, I think it would be better to use it in the following way. You should protect the default using. 

This is just a suggestion.

```
public class City 
{
        @DocumentReferences({
		@DocumentReference(name = "query1", fields = {"id", "name"} , defaultQuery = true, ......)				
		@DocumentReference(name = "query2", fields = {"id", "name", "population"}, sort ="population", ......)				
	})	
	private Country country;

	public Country getCountry() { // default = true
		.........
	}
        .................
	public Country getCountry(@QueryName String queryName) { // if empty use defaultQuery
		..........
	}
}
```

**Comment by mp911de** [comment]
Thanks for checking out document references. References are resolved during object mapping. Object mapping doesn't use attached objects nor does it apply AOP transformations but rather produces plain objects. Accessing a value in a field or a property through its getter returns immediately the actual value.

Care to elaborate what use-case you want to address with the suggestion above?

**Comment by blueiceprj** [comment]
Reference objects can sometimes be very large and I don't want to use all of the incoming data and I want more options (multiple annotation). Here, the reference object does not need to change. Only the fields it queries and fetch from the database should be optional.

I made this proposal to improve application performance and for more usable solution in a production environment. This is somewhat similar to the "query by name" feature in JPA.

**Comment by mp911de** [comment]
Thanks a lot. For a single-object reference, it doesn't matter much as BSON documents are capped at 16megs. If references impose significant performance drag, then we recommend fetching references explicitly instead of letting the mapping layer fetch references.

I'm closing this one since attached objects aren't valid in the context of Spring Data MongoDB.

**Comment by blueiceprj** [comment]
Right now we're already doing it this way and the document reference doesn't need any more. Thanks for your replies.
