### ISSUE TITLE
Enhance @DocumentReference to allow OneToMany style lookups

### ISSUE THREAD

**Issue by caspian-borison-by** [spring-projects/spring-data-mongodb#3798]
This is an amazing new feature and I definitely am looking forward to using it when 2.6 is released.

However, I have been playing around with it in some sandbox projects and (perhaps there is something I am missing, the documentation doesn't seem to address it?) but there appears to be one specific functional gap in the usage of it.

Assume I have:
```
class Book {
    @Id   
    String id;
    
    private String publisherId;
}

class Publisher {
   @Id
   String id;
   
   @ReadOnlyProperty
   @DocumentReference(lookup="{'publisherId': <this.id> ???}")
   List<Book> books;
}
```

Is it at all possible for the list of books to do a db.books.find({'publisherId': Publisher::id}) without storing a List<String> bookIds on the Publisher class? Perhaps I am missing something from the documentation and this is already supported?

If not, then (I realize we're starting to get into foreign key relationships with Mongo which isn't the greatest thing), it does seem like a use case that would be beneficial to support if possible?

Thanks!

**Comment by christophstrobl** [comment]
@caspian-borison-by thanks for the suggestion! Turns out with a few bits changed this can be done (#3802).

**Comment by caspian-borison-by** [comment]
Awesome! I can definitely see the self reference being useful.
Thank you!

**Comment by alabotski** [comment]
Hi can you explain me

[MongoTemplateDocumentReferenceTests](https://github.com/spring-projects/spring-data-mongodb/pull/3802/files#diff-d7570daecbb6be94c76c6959a43dc560f76e37ec09b5bec1a3c4ce60733abd7e)

Test - allowsOneToMayStyleLookupsUsingSelfVariable works fine

But if I rewrite it. It doesn't pass... =(

```
	@Test // GH-3798
	void allowsOneToMayStyleLookupsUsingSelfVariable_2() {

		OneToManyStylePublisher publisher = new OneToManyStylePublisher();
		template.save(publisher);

		OneToManyStyleBook book1 = new OneToManyStyleBook();
		book1.id = "id-1";
		book1.publisherId = publisher.getId();

		OneToManyStyleBook book2 = new OneToManyStyleBook();
		book2.id = "id-2";
		book2.publisherId = "p-200";

		OneToManyStyleBook book3 = new OneToManyStyleBook();
		book3.id = "id-3";
		book3.publisherId = publisher.getId();

		template.save(book1);
		template.save(book2);
		template.save(book3);

		OneToManyStylePublisher target = template.findOne(query(where("id").is(publisher.id)), OneToManyStylePublisher.class);
		assertThat(target.books).containsExactlyInAnyOrder(book1, book3);
	}
```
