### ISSUE TITLE
Saving an existing document leads to insert when the identifier field is named `_id` without using `@Id`

### ISSUE THREAD

**Issue by ppooii12009** [spring-projects/spring-data-mongodb#3799]
Hi! I'm using mongodb to handle some data.
But something is wrong when using `XX.save(Object object)` to update an existed document.
My entity is like
```
@Document(value = "test")
public class TestDO
{
    @Id
    @Field(value = "_id", targetType = FieldType.OBJECT_ID)
    private String _id;

    @Field(value = "pa")
    private Integer pa;

    @Field(value = "pb")
    private String pb;
}
```

And following is the DAO interface

```
public interface TestDAO extends MongoRepository<TestDO, String>
{
}
```

But When I use the following code and try to update the document, error appears
```
TestDO testDO = testDAO.findBy_idEquals(_id);
        testDO.setPc(new Date());
        testDO.setPa(98);
        testDO.setPb("66666");
        testDAO.save(testDO);
```

The error is 
`E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }`

seems `save()` can't update the data. But I google that `save()` can do this. Can someone fix this? Would be appreciated.

**Comment by ppooii12009** [comment]
> Which Spring Data MongoDB version are you using? Can you provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem. We weren't able to reproduce the issue with the given code.

MongoDB version is 5.0.2 Community.
Spring Data Jpa version is 2.5.4
The dependency is 
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>2.5.4</version>
        </dependency>
```

Here I use 3 java files named `TestDO.java` `TestDAO.java` and `TestController.java`
The content of `TestDO.java` and `TestDAO.java` has already been given above(the getters and setters of `TestDO.java` are omitted here), and `TestController.java` seems like following
```
@Controller
public class TestController
{
    @Autowired    
    private TestDAO testDAO;    

    @RequestMapping("/test")
    @ResponseBody
    public String test()
    {
        TestDO testDO1 = testDAO.findBy_idEquals(_id);
        testDO1.setPc(new Date());
        testDO1.setPa(98);
        testDO1.setPb("66666");
        testDAO.save(testDO1);
    }
}
```

Then run the spring project and I access `localhost:<myport>/test` , the error appears.
Before I run the porject, the object `testDO1` already has a property  `_id`  of value `ObjectId('6130d0e926df0b133148b57a')`

**Comment by mp911de** [comment]
There's some fundamental mismatch here. The comment above says Spring Data JPA whereas we're discussing MongoDB issues here. Having a self-enclosed project (go to start.spring.io and generate one) is what we're looking for.

**Comment by jagadeeshkoka** [comment]
> Hi! I'm using mongodb to handle some data.
> But something is wrong when using `XX.save(Object object)` to update an existed document.
> My entity is like
> 
> ```
> @Document(value = "test")
> public class TestDO
> {
>     @Id
>     @Field(value = "_id", targetType = FieldType.OBJECT_ID)
>     private String _id;
> 
>     @Field(value = "pa")
>     private Integer pa;
> 
>     @Field(value = "pb")
>     private String pb;
> }
> ```
> 
> And following is the DAO interface
> 
> ```
> public interface TestDAO extends MongoRepository<TestDO, String>
> {
> }
> ```
> 
> But When I use the following code and try to update the document, error appears
> 
> ```
> TestDO testDO = testDAO.findBy_idEquals(_id);
>         testDO.setPc(new Date());
>         testDO.setPa(98);
>         testDO.setPb("66666");
>         testDAO.save(testDO);
> ```
> 
> The error is
> `E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }`
> 
> seems `save()` can't update the data. But I google that `save()` can do this. Can someone fix this? Would be appreciated.

Looks like you are tryin got store duplicate value in `_id` field, can you please cross check whether you are able to pass different values or not.

**Comment by ppooii12009** [comment]
> There's some fundamental mismatch here. The comment above says Spring Data JPA whereas we're discussing MongoDB issues here. Having a self-enclosed project (go to start.spring.io and generate one) is what we're looking for.

Here's the demo project
[demo.rar](https://simplebbs-1252616544.cos.ap-shanghai.myqcloud.com/demo.rar)

**Comment by ppooii12009** [comment]
> > Hi! I'm using mongodb to handle some data.
> > But something is wrong when using `XX.save(Object object)` to update an existed document.
> > My entity is like
> > ```
> > @Document(value = "test")
> > public class TestDO
> > {
> >     @Id
> >     @Field(value = "_id", targetType = FieldType.OBJECT_ID)
> >     private String _id;
> > 
> >     @Field(value = "pa")
> >     private Integer pa;
> > 
> >     @Field(value = "pb")
> >     private String pb;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And following is the DAO interface
> > ```
> > public interface TestDAO extends MongoRepository<TestDO, String>
> > {
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But When I use the following code and try to update the document, error appears
> > ```
> > TestDO testDO = testDAO.findBy_idEquals(_id);
> >         testDO.setPc(new Date());
> >         testDO.setPa(98);
> >         testDO.setPb("66666");
> >         testDAO.save(testDO);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error is
> > `E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: hospital.test index: _id_ dup key: { _id: ObjectId('6130d0e926df0b133148b57a') }`
> > seems `save()` can't update the data. But I google that `save()` can do this. Can someone fix this? Would be appreciated.
> 
> Looks like you are tryin got store duplicate value in `_id` field, can you please cross check whether you are able to pass different values or not.

If I store a new object with `_id` valued `null`, it's ok and `_id` will be auto generated.
If I generate a new ObjectId and it's also ok
but I check the doc and it says `save` method can update the data, which confuses me

**Comment by mp911de** [comment]
Thanks for the reproducer. It's quite a mess and it took a while to clean up the project to make it runnable. There are two issues that should be considered:

1. The used `@Id` annotation comes from the JPA project (`javax.persistence.Id`). Since MongoDB isn't related to JPA at all, the annotation is silently ignored. Please use `org.springframework.data.annotation.Id`.
2. The identifier field is named `_id`. When renaming that one to `id`, then Spring Data MongoDB will identify that field as primary key and is able to correctly detect whether the entity is a new one or whether it should exist in the database.
