### ISSUE TITLE
Add support for deriving json schema for encrypted properties.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3800]
This issue aims toward support for creating a `MongoJsonSchema` containing encrypted fields for a given type based on mapping metadata.  Currently encrypted fields can only be defined manually via the `MongoJsonSchemaBuilder`.

```java
 MongoJsonSchema.builder()
    .properties(
        encrypted(string("ssn"))
            .algorithm("AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic")
            .keyId("...")
	)
```

An `@Encrypted` annotation should allow to derive required `encryptMetadata` and `encrypt` properties within a given (mapping)context.

```java
@Document
@Encrypted(keyId = "...")
static class Patient {

    // ...

    @Encrypted(algorithm = "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic")
    private Integer ssn;

}

MongoJsonSchemaCreator schemaCreator = MongoJsonSchemaCreator.create(mappingContext);
MongoJsonSchema patientSchema = schemaCreator
    .filter(MongoJsonSchemaCreator.encryptedOnly())
    .createSchemaFor(Patient.class);
```

**Comment by jagadeeshkoka** [comment]
Can I work on this one ?

**Comment by christophstrobl** [comment]
@christophstrobl there's a PR (#3801). Please feel free to add your thoughts.
