### ISSUE TITLE
No option 'dataSize' option to get the data size of the Mongodb collection using Java MongoOperations.

### ISSUE THREAD

**Issue by shiv15** [spring-projects/spring-data-mongodb#3804]
The MongoDB collection method`db.collection.dataSize()` has no option in MongoOperations. Something like, mongoOpObj.getCollection('collectionName').dataSize() could be added.

**Comment by mp911de** [comment]
That isn't something we can add in Spring Data. A `dataSize()` method needs to be exposed by the MongoDB driver on `com.mongodb.client.MongoCollection` respective its reactive variant. You might want to file a ticket at https://jira.mongodb.org/.
