### ISSUE TITLE
will @DocumentReference support reactive infrastructure in future versions 

### ISSUE THREAD

**Issue by iamanewofkotlin** [spring-projects/spring-data-mongodb#3808]
The guide original has one that `` There is no support for reading document references using reactive infrastructure. ``.

That is meaning current version no support or forever no support?

[https://docs.spring.io/spring-data/mongodb/docs/3.3.0-M2/reference/html/#mapping-usage.document-references](https://docs.spring.io/spring-data/mongodb/docs/3.3.0-M2/reference/html/#mapping-usage.document-references)

**Comment by christophstrobl** [comment]
Thanks for getting in touch! We prefer to use GitHub issues only for bugs and enhancements. Please use the search to check for existing issues before opening new ones.

Nevertheless, reference resolution incurs blocking data access when it retrieves the reference(s). Applying the same resolution strategy in a reactive environment would lead to unwanted, blocking access.

Please see #2468 and #2496.
