### ISSUE TITLE
Pattern not format Special characters

### ISSUE THREAD

**Issue by ICLXL** [spring-projects/spring-data-mongodb#3813]
![image](https://user-images.githubusercontent.com/30027321/132670403-6ca63d22-f72a-4f32-ba91-fea2667d1dc3.png)

**Comment by jagadeeshkoka** [comment]
What are you trying to do ? `22(` is not a valid `regexp`

**Comment by ICLXL** [comment]
I want to try keyword search, just like using the like keyword in mysql, in mongo we usually use $regex:"",$options:"i", but in the springdata-mongo framework Criteria.regex(regex,options  ), the Pattern class is used for regexp, resulting in semantic inconsistency with mongo dsl, mongo $regex supports "22(", but the Criteria.regex method does not support.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
