### ISSUE TITLE
Declarative $jsonSchema setting

### ISSUE THREAD

**Issue by hrg921** [spring-projects/spring-data-mongodb#3826]
Is there a way to set $jsonSchema declaratively?

Or is there's a plan to develop this feature?

For example,

# AS-IS

```Java
MongoJsonSchema schema = MongoJsonSchemaCreator.create(mongoOperations.getConverter())
    .createSchemaFor(Person.class);

template.createCollection(Person.class, CollectionOptions.empty().schema(schema));
```

# TO-BE

```Java
@SchemaValidator
public class Person {

    private final String firstname;
    private final int age;
    private Species species;
    private Address address;

    public Person(String firstname, int age) {
        this.firstname = firstname;
        this.age = age;
    }
}
```

**Comment by mp911de** [comment]
In short: There is not and we do not plan to implement such a feature. 

The main reason is that we cannot apply a sensible strategy to feed the schema into a collection. An application _could_ create a collection upon startup with the appropriate schema, but collections can be created and dropped while an application is running. As a consequence, Spring Data MongoDB would need to check for collection presence upon each interaction with MongoDB that then affects throughput performance.

Additionally, in arrangements with multiple instances of the same application, there's no mechanism to synchronize such activity across nodes.

We recommend using either the API you've stated above or move this task into the operational area and perform schema creation/updates to the schema out-of-band by e.g. an ops team.

We have (had) a similar arrangement with automated index creation upon application startup/upon first interaction with a Java entity type. We learned from auto-index creation that while such a feature is neat for development time, in production it can cause all sorts of issues and is not a good fit for the majority of production use-cases.
