### ISSUE TITLE
Support for Atlas $search aggregation pipeline

### ISSUE THREAD

**Issue by pax95** [spring-projects/spring-data-mongodb#3831]
Add support for https://docs.atlas.mongodb.com/atlas-search/  aggregation pipeline, and the $search operator.
Currently it's not natively supported, and you use the AggregationOperation instead eg. 
```

var searchOperation = (AggregationOperation)context -> new Document("$search",
                                                                            new Document("index", "season-title")
                                                                                .append("wildcard",
                                                                                        new Document("query", title)
                                                                                            .append("path", "presentationSeries.title")
                                                                                            .append("allowAnalyzedField", true)));
        Aggregation aggregation = Aggregation.newAggregation(searchOperation, Aggregation.project()
            .and("_id")
            .as("presentationSeriesId")
            .and("presentationSeries.title")
            .as("title"));
        List<Stats> stats = mongoTemplate.aggregate(aggregation, "presentation_series", Stats.class).getMappedResults();
```
There is also some talk about it here https://www.mongodb.com/community/forums/t/using-atlas-search-with-java-not-working/16117/8

**Comment by divyajnu08** [comment]
Hi Mark/Christoph

Can I work on this issue ?

Thanks

**Comment by divyajnu08** [comment]
Hi

Accidently I deleted the PR , I was deleting the other one.
Is there any way it can be recovered ?
Or I have to write it again ?

Thanks

**Comment by mp911de** [comment]
Thanks everyone for your contributions around Atlas Search. Spring Data has always supported open-source data stores and will continue to do so. With the introduction of commercial-/enterprise-only features to some data stores, we face a conflict between remaining accessible to our open source community and demand from users that would like to consume enterprise features provided by their data store. We cannot resolve this conflict with a satisfactory outcome. Supporting commercial features introduces a series of challenges around licensing, testability. Additionally, each feature imposes additional complexity to our code base that needs to be managed in terms of implementation, maintenance, and support.

We need to draw a line somewhere. We decided to not include support for commercial-only features in Spring Data MongoDB. Spring is built with enabling our users in mind and designed in a way that you can achieve your goal while using Spring. You can use the Atlas Search API directly by specifying the `$search` stage in your code. A concise Lambda-representation could look like:

```java
AggregationOperation $search = context -> {
	Document near = new Document("path", "released")
			.append("origin", Instant.ofEpochMilli(1000L))
			.append("pivot", 7776000000L);
	return new Document("$search", new Document("near", near));
};
Aggregation.newAggregation($search, project("title", "released").andExclude("id"));
```

Alternatively, a more elaborate approach is constructing an API using proper factory classes to generate the search document:

```java
Aggregation.newAggregation(AtlasSearch.$search(TextSearch.text("spring").inPath("season")));

public class AtlasSearch implements AggregationOperation {
	private String indexName;
	private AggregationExpression expression;
	@Override
	public Document toDocument(AggregationOperationContext context) {
		Document $search = new Document();
		if(StringUtils.hasText(indexName)) {
			$search.put("index", indexName);
		}
		$search.putAll(expression.toDocument(context));
		return new Document("$search", $search);
	}
	static AtlasSearch $search(AggregationExpression searchFor) {
		// ...
	}
}
public class TextSearch implements AggregationExpression {
	@Override
	public Document toDocument(AggregationOperationContext context) {
		Document text = new Document();
		text.put("query", "...");
		text.put("path", "...");
		text.put("score", "...");
		// ...
		return new Document("text", text);
	}
	public static TextSearch text(String query) {
		// ...
	}
	public TextSearch inPath(String path) {
		// ...
	}
}
```
