### ISSUE TITLE
MongoRepository different response from save and findById on java.time.Instant

### ISSUE THREAD

**Issue by emilwihlander** [spring-projects/spring-data-mongodb#3832]
## Summary
When saving (using `save`) a document containing a `java.time.Instant` property the microseconds are part of the response, but when getting (using `findById`) the same document the microseconds are removed.

## Details
```
versions:
mongoDb docker image: mongo:4.4.6
spring-data-mongodb: 3.2.4
```
The documentation for `save`:

> Saves a given entity. Use the returned instance for further operations as the save operation might have changed the entity instance completely.
>Returns: the saved entity; will never be null.

This description makes me think that `save` and `findById` should return the same value, but the following example in kotlin, shows this isn't the case:

```kotlin
@Document
data class Entity(@Id val id: UUID, val timestamp: Instant)

interface EntityRepository : MongoRepository<Entity, UUID>

fun saveAndGet() {
  // imaging this as a function in a service, and EntityRepository is Autowired as repo
  val e = Entity(UUID.randomUUID(), Instant.now())
  val saved = repo.save(e).timestamp.nano
  val fetched = repo.findById(e.id).timestamp.nano
  println(saved)
  println(fetched)
}

// Output:
// 346393000
// 346000000
```

**Comment by schauder** [comment]
This is to be expected.

Micro and nanoseconds don't get persisted, therefore you see the difference when loading the entity again. 

With `save` you get the original entity back, so you don't see this effect.

**Comment by emilwihlander** [comment]
I do understand that that is the case for the current implementation, but the documentation states the opposite (quoted above). Either the implementation is incorrect or the documentation is.

**Comment by schauder** [comment]
> but the documentation states the opposite 
While I don't agree I guess one could argue that point. 

But "fixing" that would require to reload every entity after saving it, which certainly wouldn't appreciated by most users.

**Comment by emilwihlander** [comment]
I don't see what "Use the returned instance for further operations as the save operation might have changed the entity instance completely." would refer to if this sort of transformation isn't part of it. But yes, the overhead might be more of a problem than actually fixing this, I agree.
