### ISSUE TITLE
Lazy @DocumentReference getting empty object 

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3849]
Hi,
I use lombok and mapstruct together on my project. I wrote a decorator class for mapping object from Document-to-DTO. If I use decorator method "toDto" its getting empty object like this. But the database reference is null.

```
@Document("Student")
@Getter
@Setter
public class Student extends AbstractBaseDocument
{
...............
..............
	@DocumentReference(lazy = true)
	private SchoolClass enrolledClass;
.............
```

```
	public StudentDTO toDto(Student document)
	{
		if (document == null)
		{
			return null;
		}
		final StudentDTO dto = mapper.toDto(document);

                if (document.getEnrolledClass() != null)
		{
			dto.setEnrolledClass(new SchoolClassDTO(document.getEnrolledClass().getId(), document.getEnrolledClass().getName(),
					new AcademicPeriodDTO(document.getEnrolledClass().getAcademicPeriod().getId(),
							document.getEnrolledClass().getAcademicPeriod().getName())));
		}

```
![Clipboard - October 1, 2021 2_55 PM](https://user-images.githubusercontent.com/1829975/135603309-77038fe6-5234-4f9b-bd44-4ef791f90554.png)

**Comment by blueiceprj** [comment]
I should check if Id exist. 

`if (document.getEnrolledClass() != null && document.getEnrolledClass().getId() != null)`

**Comment by blueiceprj** [comment]
If I remove lazy property or set to false everything is running as well.

**Comment by christophstrobl** [comment]
Right now, we struggle to understand what you want to achieve. Please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by blueiceprj** [comment]
When I update a document has reference object its getting this error.


```
java.lang.NullPointerException: null
	at org.springframework.data.mongodb.core.convert.DocumentPointerFactory.computePointer(DocumentPointerFactory.java:91)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writePropertyInternal(MappingMongoConverter.java:834)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeAssociation(MappingMongoConverter.java:777)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeProperties(MappingMongoConverter.java:747)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:733)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:706)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:656)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:106)
	at xxxxxx.base.objects.repository.impl.AbstractMongoRepository.update(AbstractMongoRepository.java:195)
```

<img width="945" alt="Ekran Resmi 2021-10-01 13 58 33" src="https://user-images.githubusercontent.com/1829975/135616373-36959708-7ed7-475e-ba47-4bc0117ef909.png">

**Comment by christophstrobl** [comment]
It does not help to post images and partial stack traces without their context (domain types involved, the update statement, additional setup like converters, etc.) 
As said, if you'd like us to spend some time investigating, please take the time to provide something that reproduces the problem.

**Comment by blueiceprj** [comment]
Ok. Sorry about that. I am going to explain as an example.

According to this example (lazy=false) the reference object (getCountry()) return empty object but not null. All country fields is null also Id field. I guess the the lazy referenced proxy object is not running properly.

```
public class City extends AbstractBaseDocument
{
	@DocumentReference(lazy = true)
	private Country country;
```

If I set lazy false or remove this option the reference object is not empty and getting all fields values

```
public class City extends AbstractBaseDocument
{
	@DocumentReference(lazy = false)
	private Country country;

 OR 

public class City extends AbstractBaseDocument
{
	@DocumentReference
	private Country country;
```

**Comment by blueiceprj** [comment]
City object on mongodb 

<img width="371" alt="Ekran Resmi 2021-10-01 14 30 34" src="https://user-images.githubusercontent.com/1829975/135620037-881f5346-c6ea-400f-ace5-35146dff4bbb.png">
go

**Comment by blueiceprj** [comment]
To be sure I'm checking again right now. And everything is running properly. This is my bad.

**Comment by christophstrobl** [comment]
Thanks for letting us know! Glad it works for you now :)
