### ISSUE TITLE
AbstractReactiveMongoConfiguration seems related to spring boot trying mongodb at 127.0.0.1

### ISSUE THREAD

**Issue by indiepopart** [spring-projects/spring-data-mongodb#3868]
I am testing a webflux application with spring-boot-starter-data-mongodb-reactive, and used AbstractReactiveMongoConfiguration to setup custom mongodb converters as explained in https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.custom-converters.xml.

Using docker, I get monitor exceptions and connection errors:

First attempt:
`demo_1     | 2021-10-27 06:09:07.032  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}`
`demo_1     | 2021-10-27 06:09:07.098  INFO 1 --- [127.0.0.1:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server 127.0.0.1:27017`

Second attempt with the right configuration:
`demo_1     | 2021-10-27 06:09:09.952  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[mongodb:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
`

Failed query request:
`demo_1     | 2021-10-27 06:11:57.982  INFO 1 --- [or-http-epoll-2] org.mongodb.driver.cluster               : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1458/0x000000080130dc30@63c1fe3e from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]}. Waiting for 30000 ms before timing out
`

If I remove the AbstractReactiveMongoConfiguration, and configured converters with:

```java
   @Bean
    public MongoCustomConversions mongoCustomConversions() {

        return new MongoCustomConversions(
            Arrays.asList(...);
    }
```

The spring-boot app no longer tries 127.0.0.1. Is it the wrong choice to use AbstractReactiveMongoConfiguration with spring-boot-starter-data-mongodb-reactive?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Oualitsen** [comment]
I am facing the same issue here.
I am using webflux with `AbstractReactiveMongoConfiguration` it works just fine one localhost.
But when I dockerize the app I see error messages similar to @indiepopart 's
