### ISSUE TITLE
Automatic generation of complex primary keys

### ISSUE THREAD

**Issue by boerngen-schmidt** [spring-projects/spring-data-mongodb#3873]
Hello everyone,

I wanted to request a feature for generating complex primary key for a Document. 

An example Document and complex key
```java
@Document("test")
public class Test {
  @Id
  public VersionedKey id;

  // Other fields
}

public class VersionedKey implements Serializable {

    public VersionedKey() {
        id = new ObjectId();
        version = "current";
    }
    ObjectId id;
    String version;
}
```

When calling save() it fails at https://github.com/spring-projects/spring-data-mongodb/blob/f94a7ee742fca024eb13bd240d5fa320c1435da5/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/EntityOperations.java#L616 since VersionedKey is not in this list.

One thing I have not found is where the Id generation takes place. If this is covered by MongoDB itself my request does not seem feasable, but if it is done by Spring-Data would it be possible to register a Bean, just like BackendIdConverter in spring-data-rest which is used to create a new Id if none was given.

**Comment by mp911de** [comment]
> One thing I have not found is where the Id generation takes place

That happens within the database. Upon document insertion, that does not contain a `_id` field, MongoDB auto-generates an identifier and hydrates it back to the `Document`.

`MongoTemplate` then populates the identifier into the saved object, see

https://github.com/spring-projects/spring-data-mongodb/blob/f94a7ee742fca024eb13bd240d5fa320c1435da5/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoTemplate.java#L1259-L1261

Having a complex object with a different representation than what MongoDB generates wouldn't work as identifiers are generated by MongoDB and MongoDB isn't aware that you want to use a customized identifier structure. In the example above, `_id` would be set to an `ObjectId` while the entity represents the identifier differently.

You can register an `EntityCallback`, specifically `BeforeConvertCallback` if you want to generate identifiers yourself in a lifecycle callback.

**Comment by boerngen-schmidt** [comment]
> You can register an `EntityCallback`, specifically `BeforeConvertCallback` if you want to generate identifiers yourself in a lifecycle callback.

That is exactly what I'm doing and thank you for clarification that the IDs are generated by MongoDB itself.
