### ISSUE TITLE
ReactiveMongoTemplate: The 'cursor' option is required

### ISSUE THREAD

**Issue by brianmarting** [spring-projects/spring-data-mongodb#3900]
As the title states, I'm getting `com.mongodb.MongoCommandException: Command failed with error 9 (FailedToParse): 'The 'cursor' option is required, except for aggregation explain'` when running my aggregation with the options: `.withOptions(AggregationOptions.builder().allowDiskUse(true).cursor(new Document()).cursorBatchSize(1).build())`. 

When looking a bit into the reactive template code, it seems that the option called 'cursor' is not even being used at https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/ReactiveMongoTemplate.java#L1000-L1026

Or am I just doing something wrong here? I also posted the question [here](https://stackoverflow.com/questions/70216555/reactive-mongo-template-the-cursor-option-is-required-on-mongo-4-4-0)

Using mongodb 4.4.0 by using a DownloadConfigBuilderCustomizer. For the rest, using spring-data-mongodb: 3.2.2

```
    @Bean
    public DownloadConfigBuilderCustomizer downloadConfigBuilderCustomizer() {
        return (downloadConfigBuilder) -> downloadConfigBuilder
                // Can be found on https://www.mongodb.com/download-center/community/releases/archive instead of letting
                // flapdoodle handle it itself through the properties as it fails to use a correct url
                .downloadPath(distribution -> "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-4.4.0.zip")
                .build();
    }
```

**Comment by mp911de** [comment]
Care to provide additional details? What MongoDB driver version are you using? The cursor options is being configured by the MongoDB driver class `com.mongodb.internal.operation.AggregateOperationImpl`.

**Comment by brianmarting** [comment]
I downgraded it to version 4.2.0 and its still giving the error, currently at driver 4.2.3: `{ driver: { name: "mongo-java-driver|reactive-streams|spring-boot", version: "4.2.3" }, os: { type: "Windows", name: "Windows 10", architecture: "amd64", version: "10.0" }, platform: "Java/AdoptOpenJDK/11.0.11+9" }`.
In my code I'm doing `reactiveMongoTemplate.aggregate(Aggregation.newAggregation(...` which just means that I'm using the aggregate method on the reactiveMongoTemplate. When looking a bit deeper down into this aggregate option, it is executing the `doAggregate` method, which also executes the `aggregateAndMap` method.

But the thing is that when I pass the option `.cursor(new Document())` in the aggregation options, this option is not even being used in the underlying code when we look at https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/ReactiveMongoTemplate.java#L1000-L1026

When looking at my error code `'The 'cursor' option is required`, I assume that the aggregation option   `.cursor(new Document())` should do the trick, but eventually in the reactive mongo template its not being used at all which explains the error. So my question is on how to resolve this issue
FYI the entire aggregate can be seen in my stackoverflow link, the only thing that has changed since that post is my downgrade to mongo v 4.2.0

**Comment by mp911de** [comment]
Both, the 4.4 and the 4.2 driver lines assemble the `cursor` option in `AggregateOperationImpl` and that is nothing Spring Data can even remotely do. Paging @jyemin @rozza

**Comment by jyemin** [comment]
Hi @brianmarting can you paste the full stack trace of the exception please?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
