### ISSUE TITLE
use spring-data-mongodb2 ,Download speed is very slow

### ISSUE THREAD

**Issue by liweiye-2021** [spring-projects/spring-data-mongodb#3903]
use GridFSBucket  api

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by liweiye-2021** [comment]
dependency:
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.5</version>
        <relativePath/> 
    </parent> 
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>


Demo:
public byte[] findByFileId() throws Exception {
        InputStream inputStream = new FileInputStream(new File("D:\\test\\aa.xlsx"));
        ObjectId objectId = gfTemplate.store(inputStream, "fileName", "1");
        byte[] content = null;
        try (ByteArrayOutputStream outStream = new ByteArrayOutputStream()) {
            gridFsBucket.downloadToStream(objectId, outStream);
            content = outStream.toByteArray();
        } catch (IOException e) {
            LOG.error("read GridFsFile error, fileId:", e);
        }
        return content;
    }

**Comment by mp911de** [comment]
The code above is pretty generic and it doesn't express what performance you expect vs. the one you get.

**Comment by liweiye-2021** [comment]
thanks for your answer，I try again by my server,  Performance is the result of other issues.Maybe the version of mongodb or others.

Next time I have to try more before I ask，thanks
