### ISSUE TITLE
How to scope client session bean properly?

### ISSUE THREAD

**Issue by rvplauborg** [spring-projects/spring-data-mongodb#3910]
Hi,

We are attempting a DDD architecture, where we use repositories (custom ones) that in turn use MongoOperations. To have more control and easier testing we use a UnitOfWork start and commit transactions. So we need our repositories to use the same ClientSession as our UnitOfWork in order for transactions to work as intended.

We use an in-memory synchronous mediator to decouple our code, so performing a POST will first be handled by one class calling the UnitOfWork to start the transaction, doing work on a domain entity which may result in events, and then saves using a repository, and commits the transaction using UnitOfWork. These events result in other classes getting called, and those classes are not aware of who the caller is as it is just an event being mediated.

All in all, this setup works very well for all our synchronous use cases where all event handling for a given use case is handled synchronously and we want the whole thing done in a transaction.

But we have a use case that needs to start some heavy workload, so we use JobRunr to enqueue that - currently the job code does what a normal event handler in our code does, and may also fire additional events as it modifies domain events. But that breaks since we are no longer in a request context, and the handlers expect a repository using MongoOperations with the session - but there is no session.

Is there a way to avoid request scoping the session but get some of the behavior? The reason I am filing the issue here is that it must be a common use case we are running into so hoping there is something we just dont know.. Or is it an antipattern to try and reuse existing setup for background jobs?

```
    @Bean(destroyMethod = "stop")
    @RequestScope
    fun unitOfWork(session: ClientSession): MongoUnitOfWork = MongoUnitOfWork(session)

    @Bean
    @RequestScope
    fun clientSession(mongoClient: MongoClient): ClientSession {
        return mongoClient.startSession()
    }

    @Bean
    fun mongoOperations(factory: MongoDatabaseFactory, converter: MongoConverter, clientSession: ClientSession): MongoOperations {
        return MongoTemplate(factory, converter).withSession(clientSession)
    }
```

```
abstract class TransactionalCommandHandler<TCommand : Command>(
    private val unitOfWork: UnitOfWork
) : CommandHandler<TCommand> {
    final override fun handle(command: TCommand) {
        unitOfWork.start()
        handleInTransaction(command)
        unitOfWork.commit()
    }

    protected abstract fun handleInTransaction(command: TCommand) // will often modify domain entity, fire domain events and save using some repository
}
```

**Comment by mp911de** [comment]
Transparent session scoping works only when using transactions. Transactions aren't meant to be a mechanism for sessions, but Mongo designed transactions over sessions. There's no annotation-driven mechanism to bind a session to a thread and later on use it.

You could bind the session to the thread yourself through a `ThreadLocal` and override `MongoTemplate.doGetDatabase(…)` to produce a session-bound `MongoDatabaseFactory`.
