### ISSUE TITLE
Update list of supported query method keywords.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#3916]
`IgnoreCase` is not listed in section `mongodb.repositories.queries` for example.

**Comment by mihailcornescu** [comment]
Hi @christophstrobl. I am new to contributing to spring-data-mongodb. Can I handle this issue?

**Comment by mihailcornescu** [comment]
Thank you @christophstrobl. I have checked them already. Can you tell me for which milestone should I include the changes? In other words or from which branch should I create my feature branch.

**Comment by christophstrobl** [comment]
Please use _main_. We'll take care of porting the changes.

**Comment by mihailcornescu** [comment]
@christophstrobl I have raised PR #3950. Can you have a look on it?
