### ISSUE TITLE
Eager loading of collections annotated with @DocumentReference works under certain tricky condition (reactive)

### ISSUE THREAD

**Issue by hicnar** [spring-projects/spring-data-mongodb#3922]
Minimal example below

```
@Data
@Document(collection = "questions")
@AllArgsConstructor
public class Question {
    @Id
    private String id;
    private boolean basic;
       @DocumentReference (collection = "question_content")
    private List<QuestionContent> contents;
}


@Data
@AllArgsConstructor
@Document(collection = "question_content")
public class QuestionContent {
    @Id
    private String id;
    private String content;
}

```

the dao

```

@Slf4j
@Component
@AllArgsConstructor
public class QuestionDao {

    private ReactiveMongoTemplate reactiveTemplate;

    public Mono<Question> save(Mono<Question> question) {
        return question.flatMap(q -> reactiveTemplate.insertAll(q.getContents()).then(Mono.just(q)))
                       .flatMap(q -> reactiveTemplate.insert(q));
    }

    public Mono<Question> findById(String id) {
        return reactiveTemplate.findById(id, Question.class);
    }
}

```

The ```findById(...)``` will fetch the contents from both ```question``` and ```question_content``` collections **only** if the standard blocking mongo dependency, that is the following:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
```

is present in the pom.xml. If not, only the ```id``` and ```basic``` properties of the returned instance of ```Question``` will be populated, the ```contents``` collection will be ```null```.

For the record, when I was generating the dependencies (with the spring initializr) for the app I only selected the reactive mongo library and the standard blocking one was included in the generated pom.

Is this something everybody is/should be aware of and only myself returning to Spring after a few years have no idea about? Not sure if it is a bug, but it took me a while to figure this out, so perhaps this post will help someone in a similar situation. 
PS. I am on Spring Boot 2.6.2

**Comment by christophstrobl** [comment]
As mentioned in the [Reference Documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mapping-usage.document-references) _"There is no support for reading document references using reactive infrastructure"_.
Please report issues when generating the project with Spring Initializr at [https://github.com/spring-io/initializr/issues](https://github.com/spring-io/initializr/issues). Thank you!

**Comment by sonerd** [comment]
@hicnar many thanks. This helped me making my code work.
