### ISSUE TITLE
org.springframework.data.mongodb.core.MongoTemplate:find() cost much time.  about 12s

### ISSUE THREAD

**Issue by xiaoxiaoleng** [spring-projects/spring-data-mongodb#3925]

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
