### ISSUE TITLE
Error at runtime: "java: cannot access com.mongodb.client.MongoCollection"

### ISSUE THREAD

**Issue by mawx** [spring-projects/spring-data-mongodb#3961]
Hello all,
we are using spring-stack with mongo for several years now, and we are currently migrating from java 11 to java 17.
This made us update our dependencies as well:
 - spring: `5.2.6.RELEASE` => `5.3.15`
 - spring-data-mongodb: `2.2.7.RELEASE` => `3.2.7`

These updates made up face a specific problem, I hope you guys already faced it.

We have a class `CustomMongoTemplate` that extends `MongoTemplate`, in order to wrap the behaviour of the `find` and `findAll` methods.
This was not a problem with the previous version of our dependencies. But now it seems that this extends shouts a problem at runtime:
```
java: cannot access com.mongodb.client.MongoCollection
  class file for com.mongodb.client.MongoCollection not found
```

Why does this error pops out? do you have any idea or workaround to face it?

Thank you in advance for your time having a look at this issue 🙏🏻

_Note in order to give more context_: we have created this extend of MongoTemplate in order to clean data coming from the database, here a sample of our code:

```
public class CustomMongoTemplate extends MongoTemplate {

    public CustomMongoTemplate(MongoDatabaseFactory mongoDbFactory, MongoConverter mongoConverter, Validator validator) {
        super(mongoDbFactory, new FailSafeMongoConverter(mongoConverter, validator));
    }

    @Override
    public <T> List<T> find(Query query, Class<T> entityClass) {
        return cleanNullValues(super.find(query, entityClass));
    }

    // ... more overrides omitted here ...

    private <T> List<T> cleanNullValues(List<T> result) {
        return result.stream().filter(Objects::nonNull).collect(Collectors.toList());
    }
}
```

**Comment by christophstrobl** [comment]
Please follow the [upgrading section](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#upgrading.2-3) in the reference documentation and kindly let us know if that solved the issue.

**Comment by mawx** [comment]
Thank you for your heads up,
I've looked over the given upgrading section and I didn't find any step we made wrong.

Moreover I really think the problem comes with this `extends MongoTemplate` as if we use the `MongoTemplate` directly (without using our custom one) the application starts correctly.

**Comment by christophstrobl** [comment]
Given the description above we cannot tell what's the issue. Please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by mawx** [comment]
Following your advice, I've found it my issue.
My spring-data-mongodb dependency was not positionned in the good module. Such a noob error!

Thanks again for your time.
I close the issue.
