### ISSUE TITLE
`@DocumentReference` doesn't work with generated IDs

### ISSUE THREAD

**Issue by alabotski** [spring-projects/spring-data-mongodb#3975]
Hi
@DocumentReference doesn't seem to work correctly with generated IDs

Take for example working test
In it, we put down the ID ourselves
https://github.com/spring-projects/spring-data-mongodb/blob/3d697a1752b8bc24f907dd15bbc5e83de1540d8b/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/core/MongoTemplateDocumentReferenceTests.java#L1156

I rewrite it and it does not pass

```
	@Test // GH-3798
	void allowsOneToMayStyleLookupsUsingSelfVariable_2() {

		OneToManyStylePublisher publisher = new OneToManyStylePublisher();
		template.save(publisher);

		OneToManyStyleBook book1 = new OneToManyStyleBook();
		book1.id = "id-1";
		book1.publisherId = publisher.getId();

		OneToManyStyleBook book2 = new OneToManyStyleBook();
		book2.id = "id-2";
		book2.publisherId = "p-200";

		OneToManyStyleBook book3 = new OneToManyStyleBook();
		book3.id = "id-3";
		book3.publisherId = publisher.getId();

		template.save(book1);
		template.save(book2);
		template.save(book3);

		OneToManyStylePublisher target = template.findOne(query(where("id").is(publisher.id)), OneToManyStylePublisher.class);
		assertThat(target.books).containsExactlyInAnyOrder(book1, book3);
	}

```

**Comment by mp911de** [comment]
The code works as designed. The reason that no objects are found is that MongoDB generates an `ObjectId` for `OneToManyStylePublisher` while the `publisherId` is a `String`. If you consistently use the matching type `ObjectId` for `OneToManyStylePublisher.id` and `OneToManyStyleBook.publisherId`, then Spring Data can perform the lookup successfully.
