### ISSUE TITLE
`MongoTemplate.createCollection(String, CollectionOptions)` does not consider timeseries options

### ISSUE THREAD

**Issue by MaConch** [spring-projects/spring-data-mongodb#3984]
When the convertToDocument method is called when the non-object creation method createCollection is used, this method is not adapted to the time series
![image](https://user-images.githubusercontent.com/28838804/156731619-55ef52ff-ce62-4a0f-9803-86c589150717.png)
![image](https://user-images.githubusercontent.com/28838804/156731921-5a34c15b-e46b-4f8a-912f-dbe3d13d248e.png)

**Comment by christophstrobl** [comment]
good catch - we'll take care of this!
