### ISSUE TITLE
LookupOperation AggregationField clean '$'

### ISSUE THREAD

**Issue by chenfuyuan** [spring-projects/spring-data-mongodb#3985]
LookupOperation AggregationField will clean ‘$’ fieldRef.Now mongodb support $lookup can use '$'.

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve. Maybe you could add a bit more context to the issue covering involved domain types and the aggregation.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
