### ISSUE TITLE
Typo, should be public.

### ISSUE THREAD

**Issue by german-komarov** [spring-projects/spring-data-mongodb#3989]
https://github.com/spring-projects/spring-data-mongodb/blob/49e6d536416b07131f0f5c2c5741a89a5f8cff05/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/schema/TypedJsonSchemaObject.java#L668

**Comment by christophstrobl** [comment]
Thanks for reporting - we'll take care of this!
