### ISSUE TITLE
Can you add Querydsl related extensions?

### ISSUE THREAD

**Issue by sangyongchoi** [spring-projects/spring-data-mongodb#3996]
Hello.
I am a spring data mongo user.
I usually use it in combination with querydsl .
I found some inconvenience.

There are two problems when using MongoOperation (or ReactiveMongOperation) with Query() .
- non type-safe
- possibility of error due to typo

If you use kotlin.TypedCriteriaExtensions.kt, it can be solved to some extent, but there are some inconveniences.

This is not convenient when it is a nested object.

example
```kotlin
@Document
data class Book(
    val title: String,
    val author: Author,
)

@Document
data class Author(
    val name: String,
)

Book::author / Author::name isEqualTo "Herman Melville"
```

If you make an extension of querydsl.Path , I think that nested objects will also be useful.
If you create an extension, you can use it as follows.
```kotlin
val book = QBook.book
book.author.name isEqualTo "author name" 
```

I created this function and sent a [PR](https://github.com/spring-projects/spring-data-mongodb/pull/3988).

Any comments would be appreciated!
thank you.

**Comment by christophstrobl** [comment]
Thanks for getting in touch, but it feels like this is an issue best addressed by the [Querydsl team](https://github.com/querydsl/querydsl/issues). [querydsl-kotlin](https://search.maven.org/artifact/com.querydsl/querydsl-kotlin/5.0.0/jar) already ships some extensions.
