### ISSUE TITLE
PersistentProperty is not getting initialised during reads

### ISSUE THREAD

**Issue by Tarun96** [spring-projects/spring-data-mongodb#4010]
Hi everyone, 

Facing the following issue in spring 2.1.3.RELEASE. 

`[java.lang.IllegalStateException: Expected lazy evaluation to yield a non-null value but got null! at org.springframework.data.util.Lazy.get(Lazy.java:97) at org.springframework.data.mapping.model.AbstractPersistentProperty.hashCode(AbstractPersistentProperty.java:323) at java.util.HashMap.hash(HashMap.java:339) at java.util.HashMap.get(HashMap.java:557) at org.springframework.data.mapping.PreferredConstructor.isConstructorParameter(PreferredConstructor.java:135) at org.springframework.data.mapping.model.BasicPersistentEntity.isConstructorArgument(BasicPersistentEntity.java:137) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:364) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:295) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:275) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:245) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:194) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:190) at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:78) at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3017) at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2626) at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2353) at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:769) at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:757) at `

Background: 
We are using multiple mongo templates in our services and each service is auto-scaled based on demand. 
Unable to reproduce this error in non-production environment. Can anyone help me with this?

**Comment by christophstrobl** [comment]
Sorry but just from looking at the code/exception it's hard to tell what's wrong there. Please take the time and try to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by Tarun96** [comment]
@christophstrobl We don't have a pattern to reproduce this. It is happening rarely and not quite sure when but just a couple times from millions.

**Comment by odrotbohm** [comment]
It would at least be helpful to know about the version of Spring Data MongoDB and Spring Data Commons you use. The "spring 2.1.3.RELEASE" doesn't really make any sense here, as any interpretation of that would mean that you're using pretty old versions of the library. The line numbers in the stack trace don't match any supported version and in currently supported ones, the call stack will never deal with a `null` value by definition.

**Comment by Tarun96** [comment]
Looks like this issue in spring data commons is fixed in this commit: https://github.com/spring-projects/spring-data-commons/commit/a442b9002181fa6461490d105a28dd187dd3c38d. Thanks.
