### ISSUE TITLE
Allow mapping to continue on exception in collection queries

### ISSUE THREAD

**Issue by adrian-skybaker** [spring-projects/spring-data-mongodb#4020]
I'm querying large sets of data into strongly typed Java objects.

Because MongoDB is loosely typed it's entirely possible this mapping fails, due to enum parse errors, null fields where not-null is enforced, many other cases.

Currently any exception when mapping a single document simply halts the entire query, which greatly limits the usefulness of using the data mapping layer to handle bulk reads safely. Instead you would need to instead map to raw documents (and manually code the projections yourself), then map in your own code with try...catch handling.

This doesn't appear possible with a custom converter, as returning null when converting a document will throw an exception in `org.springframework.data.mongodb.core.MongoTemplate.ProjectingReadCallback#doWith`. It's also very awkward writing a converter which delegates to the default underlying converter, as the latter is only accessible after the custom converter is registered.

**Comment by christophstrobl** [comment]
Right now, we struggle to understand what you want to achieve. 
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that shows the problem.

**Comment by adrian-skybaker** [comment]
My apologies for not being clearer, perhaps this helps:

```java
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import org.springframework.data.mongodb.core.MongoOperations;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@RequiredArgsConstructor
public class MongoReader {

    private final MongoOperations mongo;

    public List<CarDto> readAllCars() {
        /** If a single car document in the collection is missing
         * a firstName or has an unrecognised colour, this query will fail. */
        mongo.query(CarDto.class).stream().toList();
    }

    @Document("cars")
    @RequiredArgsConstructor
    public static class CarDto {
        @NonNull private final String firstName;
        @NonNull private final Colour colour;
    }

    public enum Colour {
        BLUE, GREEN
    }
}
```

Also relevant is https://stackoverflow.com/questions/9792098/leniently-handling-conversion-exceptions-skip-ignore-using-mongo-spring-data, although the suggestion there of a a converter doesn't solve the issue that I can see (you can't return null from the converter).

**Comment by christophstrobl** [comment]
It seems the error stems from the fact that the domain model imposes restrictions that need to be met. Having the lookup fail is the desired behavior when the result cannot be mapped due to those restrictions. There's a couple of options like:
- don't select the invalid entries in first place, 
- lift domain model restrictions, 
- clean up the data,
- ...

**Comment by LaoYueHanNi** [comment]
> I'm querying large sets of data into strongly typed Java objects.
> 
> Because MongoDB is loosely typed it's entirely possible this mapping fails, due to enum parse errors, null fields where not-null is enforced, many other cases.
> 
> Currently any exception when mapping a single document simply halts the entire query, which greatly limits the usefulness of using the data mapping layer to handle bulk reads safely. Instead you would need to instead map to raw documents (and manually code the projections yourself), then map in your own code with try...catch handling.
> 
> This doesn't appear possible with a custom converter, as returning null when converting a document will throw an exception in `org.springframework.data.mongodb.core.MongoTemplate.ProjectingReadCallback#doWith`. It's also very awkward writing a converter which delegates to the default underlying converter, as the latter is only accessible after the custom converter is registered.

Hello, I also encountered such a problem! My program needs a collection of findall during initialization. I use spring data mongodb:2.2.7 There is no problem during release. After upgrading spring data mongodb:3.3.4, an error is reported. The error log shows that the conversion of a field from array->map failed. I can't handle this error before I expect it, because I can't know whether it is a->b or c->b in advance. Can this only clean up the data? I'd like to ask how you solved it

**Comment by adrian-skybaker** [comment]
@LaoYueHanNi I wasn't able to solve this. Instead I had to move the mapping into my own code, leaving the framework only to map to very general raw structures.

**Comment by adrian-skybaker** [comment]
>Having the lookup fail is the desired behavior when the result cannot be mapped due to those restrictions. 

Respectfully, this ticket was raised because this behaviour can be quite undesirable when dealing with large collections. One failure out of potentially millions will cause the entire query to fail irrecoverably. As a default it might suit, but the issue is there is no way to intervene to capture and handle an exception for individual records and continue.

This is at odds for example with the concept in https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/RowMapper.html#mapRow-java.sql.ResultSet-int- , which allows a null to be returned (for handling downstream).

>There's a couple of options like:

>don't select the invalid entries in first place,

This is impractical for a complex model. There is no automatic way to translate a Java domain model with multiple layers of nested classes and fields, not-null validations, enums, all into a projection that somehow automatically excludes anything not perfectly mirroring this model from the query. Doing this manually would be effectively mean a very time consuming duplication of domain model in a very fragile and awkward manner.

>lift domain model restrictions,

At some point the model needs restricting because bad/invalid/missing/unrecognised data must be excluded/handled. The question is just whether it's done (1) before insertion into the DB, (2) the data mapping layer, or (3) downstream. By suggesting it can only be done safely in (3), I would suggest you're somewhat defeating the purpose of the data mapping layer. You can always just select raw documents, and process them outside of the queries, but I believe the data mapping layer exists to reduce the manual mapping effort.

>clean up the data,

It would seem odd that a query/mapping framework would impose cleanup requirements on a source before it can be fully utilised. And in any case, even with cleanup, unless the database is enforcing the domain model via json schemas (this also seems an unreasonable requirement), there is always the possibly of unrecognised data being introduced.

**Comment by LaoYueHanNi** [comment]
> 
thank you! I'm going to clean up the wrong data. The wrong data structure should indeed be treated as an error. Even if the query is allowed to be null, other codes used here in the system still cannot run。

**Comment by LaoYueHanNi** [comment]
> @LaoYueHanNi I wasn't able to solve this. Instead I had to move the mapping into my own code, leaving the framework only to map to very general raw structures.

thank you! I'm going to clean up the wrong data. The wrong data structure should indeed be treated as an error. Even if the query is allowed to be null, other codes used here in the system still cannot run。
