### ISSUE TITLE
ClassNotFoundException: org.springframework.data.mongodb.core.SimpleMongoDbFactory on Spring Boot 2.5.8

### ISSUE THREAD

**Issue by KolothHaritha** [spring-projects/spring-data-mongodb#4036]
We upgraded Spring Boot to 2.5.8 and while deploying the application over Cloud Foundry, we are getting below error. 

`Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mongodb/core/SimpleMongoDbFactory
21:23:17.626: [APP/PROC/WEB.0] 	at org.springframework.cloud.service.document.MongoDbFactoryCreator.createMongoDbFactory(MongoDbFactoryCreator.java:45)`

We also have the dependency: **spring-cloud-spring-service-connector - version 2.2.2.RELEASE** in our application.

Due to the above error, we have to use an older version of **spring-boot-starter-data-mongodb** where the mentioned class is available.
Is there any known solution to this?

Please let us know if we are missing anything here or if we should make any changes to the application code/dependencies. 
Thanks

**Comment by mp911de** [comment]
[Spring Cloud Service Connectors](https://github.com/spring-cloud/spring-cloud-connectors) is no longer developed and that project is in maintenance mode. With the ongoing development of Spring Data, it can well be that certain parts of Spring Cloud Service Connectors stop working with Spring Data.
Please consider switching to [Java CFEnv](https://github.com/pivotal-cf/java-cfenv).

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
