### ISSUE TITLE
Egregious memory leak in DefaultBulkOperations

### ISSUE THREAD

**Issue by vfunshteyn-zw** [spring-projects/spring-data-mongodb#4039]
`DefaultBulkOperations` has been reimplemented since 1.x to accumulate writes in field called `models`, which is a collection that never gets cleared, but only added to. This results in batches of ever increasing size being sent to to the DB, resulting in out of control accumulation of documents that snowball into batches of ever increasing size. To illustrate, here's `DefaultBulkOperations.execute()` in SD MDB 1.10.x:

```java
	@Override
	public BulkWriteResult execute() {

		MongoAction action = new MongoAction(defaultWriteConcern, MongoActionOperation.BULK, collectionName,
				bulkOperationContext.getEntityType(), null, null);
		WriteConcern writeConcern = writeConcernResolver.resolve(action);

		try {
			return writeConcern == null ? bulk.execute() : bulk.execute(writeConcern);
		} catch (BulkWriteException o_O) {

			DataAccessException toThrow = exceptionTranslator.translateExceptionIfPossible(o_O);
			throw toThrow == null ? o_O : toThrow;

		} finally {
			this.bulk = getBulkWriteOptions(bulkOperationContext.getBulkMode());
		}
	}
```

It's easy to see that the buffer gets reset in the finally clause - not ideal either since the buffer in `this.bulk` gets reset regardless of the outcome, but still better than the behavior in 2.x+ (We are using 3.2.8 which looks almost identical to this):

```java
	@Override
	public com.mongodb.bulk.BulkWriteResult execute() {

		try {

			com.mongodb.bulk.BulkWriteResult result = mongoOperations.execute(collectionName, this::bulkWriteTo);

			Assert.state(result != null, "Result must not be null.");

			models.forEach(this::maybeEmitAfterSaveEvent);

			return result;
		} finally {
			this.bulkOptions = getBulkWriteOptions(bulkOperationContext.getBulkMode());
		}
	}
```

The correct behavior would be to clear the models collection just before the return statement.

The current workaround I am forced to do is to remove the instance of BulkOperations from the `ThreadLocal` instance that wraps it (because the underlying code is not thread-safe obviously), inline with the completion of `execute()` call. This was unnecessary until migrating to SB2/Spring 5.x

**Comment by mp911de** [comment]
`BulkOperations` is intended for single-usage only. As per the documentation:

> This interface defines a fluent API to add multiple single operations or list of similar operations in sequence which can then eventually be executed by calling `#execute()`.


The way bulk operations are used is that you obtain a `BulkOperations` for the desired bulk operation, add operations and run them finally. After calling `execute`, you discard the object. If you want to run another bulk, then you obtain a new `BulkOperations` instance.

**Comment by juanavelez** [comment]
> `BulkOperations` is intended for single-usage only. As per the documentation:
> 
> > This interface defines a fluent API to add multiple single operations or list of similar operations in sequence which can then eventually be executed by calling `#execute()`.
> 
> The way bulk operations are used is that you obtain a `BulkOperations` for the desired bulk operation, add operations and run them finally. After calling `execute`, you discard the object. If you want to run another bulk, then you obtain a new `BulkOperations` instance.

Hmmm I see nothing in here https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/BulkOperations.html about a one-time use maybe it's better to add that to the documentation to be clear.

**Comment by vfunshteyn-zw** [comment]
> If you want to make this a documentation issue, I can live with that outcome, but as it stands, and based on the quote you gave me there, **nothing** in the documentation indicates that BulkOperations instances should not be used in a stateful fashion. If you can find any kind of official developer guide, or API documentation that specifically calls out that usage pattern as invalid, I would be delighted to agree with your assessment that my report is invalid. But as it stands, the issue is real, can be fixed with **one** line of code, and there's absolutely no reason for this gotcha to be there, given that it didn't exist previously - it's effectively a breaking change in behavior without as little as letting the user know.

To provide more context - we rely on your library daily for mission critical components (sometimes transitively), and the mere act of upgrading a key service from Spring Boot 1 to Spring Boot 2 without any business logic or application implementation changes caused us a major production outage, and a support incident in the middle of the night that cost efforts of multiple on call engineers and potentially, customers' trust.
