### ISSUE TITLE
ReplicaSet - com.mongodb.MongoSocketException: mongo1: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by Tyngstast** [spring-projects/spring-data-mongodb#4064]
I'm trying to connect to a replicaSet using it's remote domain, but it seems like `spring-data-mongodb` is picking up the internal domain configured for the replicaSet when trying to connect, which of course won't be accessible from my application.

I'm on `spring-boot-starter:2.6.2` with `spring-data-mongodb:3.3.0` and I'm using `spring.data.mongodb.uri` to connect to the replicaSet as per the documentation.

This gist should provide enough info to reproduce: https://gist.github.com/Tyngstast/45997c498a25a0ca36026b4669a060c9

**Changing the replica set config in the gist to use my machine IP 192.168.x.x as host, instead of docker internal net, works.**

Am I missing something, or is this a bug in spring-data-mongodb?

**Comment by mp911de** [comment]
`MongoSocketException` is an infrastructure exception. It looks as if the name was not resolvable. We're passing on the URI directly to the MongoDB driver and advise you to validate your environmental settings as we cannot help with DNS resolution issues.
