### ISSUE TITLE
Add support for $getField aggregation operator.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#4072]
Since: MongoDB 5.0
See: https://www.mongodb.com/docs/manual/reference/operator/aggregation/getField/

**Comment by sxhinzvc** [comment]
closing since it's a duplicate of https://github.com/spring-projects/spring-data-mongodb/issues/4139

**Comment by sxhinzvc** [comment]
closing since it's a duplicate of https://github.com/spring-projects/spring-data-mongodb/issues/4139
