### ISSUE TITLE
How can I use MongoTemplate binding the database to implement multi-tenancy？

### ISSUE THREAD

**Issue by chikaizhou** [spring-projects/spring-data-mongodb#4086]
We have a project using mongodb,but now we have a requirement to  implement multi-tenancy.
For different tennant ,I have the same collection but different database,how can I use MongoTemplate method like find but using different database ?
And MongoDbTransactionManager is creating by MongoDbFactory.The MongoDbFactory can be creating by MongoClient and database Name .How can I use the MongoDbTransactionManager with all tennant's database.

**Comment by mp911de** [comment]
We recommend multi-tenancy by using different databases. When using Spring Data MongoDB, a routing `MongoDatabaseFactory` would be the way to go. If you want, you can pick up lose ends of #3636 to introduce an implementation for supporting multi-tenancy.
