### ISSUE TITLE
Skip output for `@Aggregation` query methods using `$out` or `void` methods

### ISSUE THREAD

**Issue by diptanil-das** [spring-projects/spring-data-mongodb#4088]
Trying to run an Aggregation which has $out at the end. $out put outputs millions of records, the repository tires to map it and fails with a heap error. I don't need the output at all

**Comment by Content68** [comment]
@mp911de https://visagedawson.github.io/IzR0qYqDP8N4QEPSfbnCfrhKitZW2g5a7PCzQ3rarnfIeNFTsA/
