### ISSUE TITLE
read() of PropertyValueConverter not triggered during save()

### ISSUE THREAD

**Issue by rfelgent** [spring-projects/spring-data-mongodb#4094]
Hello,

thx for the PropertyValueConverter functionality. I am using this feature since Spring Boot 2.7. Anyway, I think my problem is not related to Spring Boot itself.

After performing `save()` of MongoCrudRepository the `write()` method of PropertyValueConverter gets triggered but the `read()` method not. This leads to insconsistent data, as the returned instance of save() does not properly reflect the conversion done by the given `PropertyValueConverter`.

some code for demonstration. The pojo to save in mongodb

```
@AllArgsConstructor
@Document("collection")
class Pojo {
   @Id
   private String id;
   @ValueConverter(ObjectToStringConverter.class)
   private Object data;
}
```
the error prone save() logic
```
    Pojo pojo = new Pojo("1", Map.of());
    ExternalRepertoireEntity inconsistentData = repository.save(pojo);    
```
The field "data" gets converted from Map to String and the value is stored in database, but the variable "inconsistentData" has data field of data type Map instead of String

my workaround is to load the previously saved pojo so that the "read()" of the converter gets triggered
```
    Pojo pojo = new Pojo("1", Map.of());
    ExternalRepertoireEntity inconsistentData = repository.save(pojo); 
    ExternalRepertoireEntity sanitizedData = repository.findById(inconsistentData.getId()).orElseThrow();
```

Am I mis-using the PropertyValueConverter functionality ?

**Comment by mp911de** [comment]
`PropertyValueConverter`s are intended to affect the database representation for a certain property. The `save` method does not propagate the database representation back into the model.  The value returned by `PropertyValueConverter.write(…)` is only used to construct the value being sent to MongoDB. `PropertyValueConverter.read(…)` is only invoked when mapping a loaded MongoDB `Document` onto an entity instance.

Does that help?

**Comment by rfelgent** [comment]
Hi @mp911de ,

thx for your feedback!
Your words make clear, that my use case is based on bad design design decisions. 

We can close this issue.

Thx again!
