### ISSUE TITLE
spring-data-mongodb-reactive stop producing data to rest controller

### ISSUE THREAD

**Issue by MisterRnobe** [spring-projects/spring-data-mongodb#4095]
I have 2 microservices, one of them producing `APPLICATION_NDJSON` data fetched from `ReactiveMongoRepository`
```java
@RestController
@RequestMapping("/documents")
@RequiredArgsConstructor
public class DocumentController {

    private final ReactiveMongoRepository<DocumentWrapper, ObjectId> repository;

    @GetMapping(produces = MediaType.APPLICATION_NDJSON_VALUE)
    public Flux<DocumentWrapper> getAll() {
        return repository.findAll();
    }
}
```
The another one consumes it using `WebClient`
```java
public Flux<DocumentWrapper> getDocuments() {
        return webClient.method(HttpMethod.GET)
                .uri(properties.getUrl() + "/documents")
                .contentType(MediaType.APPLICATION_NDJSON)
                .retrieve()
                .bodyToFlux(DocumentWrapper.class);
    }
```
Recently, I discovered that sometimes the producing microservice stops streaming data after a while with no reason - no error or no cancel command is generated. Why does it happen and how could it be fixed?

I implemented a project demonstrating this behavior, you could find it [on GitHub](https://github.com/MisterRnobe/spring-webfux-mongo-bug-demo)

P.S.

I guess the problem is in integration between reactive mongodb driver and spring rest controller (or netty). I replaced database access 
```java
repository.findAll()
```
with mock data like
```java
Flux.generate(...)
```
and the problem was gone.

I also replaced data streaming from database to file not to controller and it worked fine too.

**Comment by mp911de** [comment]
There could be a variety of underlying reasons ranging from backpressure calculation to race conditions within the driver. Have you tried to reproduce the issue using just the MongoDB driver (i.e. without using Spring Data in between)? Debugging issues that require millions of documents to surface is always tricky.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
You might want to file a ticket in the [MongoDB Driver issue tracker](https://jira.mongodb.org/projects/JAVA/issues/JAVA-4600?filter=allopenissues). When using the driver directly, that indicates that it is a driver issue.
