### ISSUE TITLE
Support for MongoDB TimeSeries expireAfterSeconds

### ISSUE THREAD

**Issue by Kruschenstein** [spring-projects/spring-data-mongodb#4099]
Hello 🙂

Spring-data-mongodb supports [TimeSeries](https://docs.spring.io/spring-data/mongodb/docs/4.0.0-M3/api/org/springframework/data/mongodb/core/mapping/TimeSeries.html) since version 3.3. It allows to declare and create new timeseries collection. The [@TimeSeries](https://docs.spring.io/spring-data/mongodb/docs/4.0.0-M3/api/org/springframework/data/mongodb/core/mapping/TimeSeries.html) annotation offers many parameters such as those which are in the sub-object [timeseries](https://www.mongodb.com/docs/manual/reference/method/db.createCollection/#mongodb-method-db.createCollection), (`timeField`, `metaField` and `granularity`). But there is no support for a field that comes with the TimeSeries arrival which is `expireAfterSeconds` ([time series collections](https://www.mongodb.com/docs/manual/core/timeseries-collections/#std-label-manual-timeseries-collection-create)).

Regarding the code the [`CollectionOptions`](https://github.com/spring-projects/spring-data-mongodb/blob/f15fd2a4182fa34d68b280fcd5c2f150ec43455f/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/CollectionOptions.java) class, there is no field corresponding to `expireAfterSeconds`. Then if we want to create a time series with automatic expiration period, we must bypass the Spring classes and annotations (that's sad 🙁).

Is a support for the `expireAfterSeconds` planned for `@TimeSeries`? If not, I suggest to add the option to `@TimeSerie` annotation only. As mentionned in [documentation](https://www.mongodb.com/docs/manual/reference/method/db.createCollection/#mongodb-method-db.createCollection):
`expiredAfterSeconds`

> Optional. Enable the automatic deletion of documents in a [time series collection](https://www.mongodb.com/docs/manual/reference/glossary/#std-term-time-series-collection) by specifying the number of seconds after which documents expire. MongoDB deletes expired documents automatically.

(_therefore, I don't understand why this option is not part of `timeseries` sub-object..._)

I hope this proposal will interest you
Regards

**Comment by gbaso** [comment]
Is there any progress on this issue? Automatic expiration on time series is an important feature and it would be great to have spring support.
