### ISSUE TITLE
Pagination with sort on a view doesn't work correctly

### ISSUE THREAD

**Issue by afxgroup** [spring-projects/spring-data-mongodb#4108]
I have a **view** on mongodb but when using pagination (with view itself using $sort or using java code) produces wrong pagination.

For example. If I request the first page i get some results. If i ask for the second page i get some results that are present also in the first one. This doesn't happens with the plain collection where pagination + sorting works correctly

spring-boot-starter-data-mongodb version 2.7.1
mongodb 3.6.3

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
