### ISSUE TITLE
Mongodb BulkOperations Fail

### ISSUE THREAD

**Issue by xiaozaiyuji** [spring-projects/spring-data-mongodb#4112]
for (int i = 0; i < deviceDataList.size(); i++) {

                updateList = new ArrayList<>();
                deviceData = deviceDataList.get(i);

                Query query = new Query();
                query.addCriteria(new Criteria("seqId").is(deviceData.getDeviceCd()));
                query.addCriteria(new Criteria("time").is(deviceData.getGpsAtMillis()));

                Update update = new Update();
                update.set("seqId", deviceData.getSeqId());
                update.set("partId", deviceData.getPartId());
                update.set("partName", deviceData.getPartName());
                update.set("time", deviceData.getTime());

                Pair<Query, Update> updatePair = Pair.of(query, update);
                updateList.add(updatePair);

            }

            MongoTemplate mongoTemplate = null;

            BulkOperations operations = mongoTemplate.bulkOps(BulkOperations.BulkMode.UNORDERED, collectionName);
            operations.upsert(updateList);
            BulkWriteResult writeResult = operations.execute();

            result.setSuccess(writeResult.wasAcknowledged());
            result.setResult(writeResult.getModifiedCount());
I write a code to insert a data when data is not exist or update data when data exist,but I find when the update data is include ,the updateList data not save into the mongodb，I did not know why,this confuse me.
I use mongodb 3.4.12 ,use the spring-data-mongodb jar,I am not sure why this happen, what I should do to solve this problem.

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve. It would help if you take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem (ideally with a failing test case).

**Comment by xiaozaiyuji** [comment]
Thanks for your help,I can not find the problem,but this I test again,can not reconstruct this problem.mybe the mongodb cluster is wrong , I am so sorry.
