### ISSUE TITLE
Release 3.4.3 (2021.2.3)

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#4116]

**Comment by YanHui88666** [comment]
may I ask when the 3.4.3 is expected to be released? we need to use the new version to solve the problems existing in the 3.4.2

**Comment by mp911de** [comment]
Check out the [Spring Release Calendar](https://calendar.spring.io/) for Spring project release planning.

**Comment by YanHui88666** [comment]
> Check out the [Spring Release Calendar](https://calendar.spring.io/) for Spring project release planning.

Thank you very much. It means a lot to me
