### ISSUE TITLE
Question about construction misinterpretation

### ISSUE THREAD

**Issue by zenon-was-here** [spring-projects/spring-data-mongodb#4126]
Hello, longtime user, first time caller here. 

I am using Spring Boot and  Starter Mongodb version 2.5.14.

I have run into an issue where a parameter on a constructor is errantly being expected to be mapped to a database field.

I received this error:

```
An unhandled exception was thrown: org.springframework.data.mapping.MappingException: No property builder found on entity class com.zebra.phoenix.userservice.domain.dto.UniqueRoleDTO to bind constructor parameter to!
```

My class looks like this (omitting some boilerplate):

```
@Data
public class UniqueRoleDTO {

    private UniqueRoleDTO(UniqueRoleDTOBuilder builder) {
        this.tenantId = builder.tenantId;
        this.domain = builder.domain;
        this.scope = builder.scope;
        this.roleId = builder.roleId;
    }

    private String tenantId;
    private String domain;
    private String scope;
    private String roleId;

    public String toGlobalId() {
        return tenantId + domain + scope + roleId;
    }

    public static UniqueRoleDTOBuilder builder() {
        return new UniqueRoleDTOBuilder();
    }

    public static class UniqueRoleDTOBuilder {

        private String tenantId;
        private String domain;
        private String scope;
        private String roleId;

        public UniqueRoleDTOBuilder tenantId(String tenantId) {
            ...
        }

        public UniqueRoleDTOBuilder tenantId(String tenantId, String tenantIdIfEmpty) {
           ...
        }

        public UniqueRoleDTOBuilder domain(String domain) {
            ...
        }

        public UniqueRoleDTOBuilder domain(String domain, String domainIfEmpty) {
           ...
        }

        public UniqueRoleDTOBuilder scope(String scope) {
            ...
        }

        public UniqueRoleDTOBuilder scope(String scope, String scopeIfEmpty) {
            ...
        }

        public UniqueRoleDTOBuilder roleId(String roleId) {
           ...
        }

        public UniqueRoleDTO build() {
           ...
            return new UniqueRoleDTO(this);
        }
    }
}
```

I determined that it was specifically failing on the parameter called `builder` on the constructor, rather than the method `builder()` by renaming them while probing the issue.

I was able to resolve the issue by deleting my constructor, and using a Lombok-generated one.

I'm not sure if this an issue, or some error on my part, but I've never seen this behavior before, and I'm trying to understand it. Could you help me understand how that parameter would have gotten caught up in that error?

Thank you.

**Comment by mp911de** [comment]
Spring Data does not support the builder pattern. There are a lot of variants for builders and how builders behave in terms of configuration/`with`/bare-named methods and what they return. We do not plan to support builders. 

If you want to encapsulate your model, then the way is to create a `private` all args constructor and annotate it with `@PersistenceConstructor`. Spring Data can use private constructors to materialize entities.

**Comment by zenon-was-here** [comment]
Thanks for this explanation!
