### ISSUE TITLE
support for BsonExtraElements in spring data mongodb

### ISSUE THREAD

**Issue by vijayaba1** [spring-projects/spring-data-mongodb#4127]
Hi In my project I am trying to use the new mongodb driver 4.7.0 along with spring data mongodb version 3.0.9.RELEASE and trying to use the BsonExtraElements for below example model
client 1 using
public class Person {
@Id
private int id;
private String name;
@BsonExtraElements
private Map<String, String> extraElements;
}

client 2 updated the model
public class Person {
@Id
private int id;
private String name;
private String address;
@BsonExtraElements
private Map<String, String> extraElements;
}

if we use the mongo db driver the encode/decode support the forward compatibility any missing attributes goes as part of extraElements, so we can have the different clients on different versions of the model.

the spring data mongodb which version do we need to use to get the BsonExtraElements support?
Please let me know.
thanks
Vijaya

**Comment by mp911de** [comment]
`@BsonExtraElements` is part of the MongoDB POJO Codec. You can register a pojo codec in MongoDB's `CodecRegistry` to leverage POJO codec features. Spring Data's conversion layer does not support injection of unmapped properties on the same level. If you want to get access to all document fields, you would need to use `Document` instead of a mapped entity.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
