### ISSUE TITLE
Allow to create case insensitive indexes via annotations 

### ISSUE THREAD

**Issue by jakubpradzynski** [spring-projects/spring-data-mongodb#4130]
Hi,

the option for creating case insensitive index in MongoDB is available by setting `collation`. Specifically `locale` and `strength` values. It's described [in MongoDB documentation](https://www.mongodb.com/docs/manual/core/index-case-insensitive/).

Currently, annotations `@Indexed` and `@CompoundIndex` don't have `collation` in parameters to set.
Such option is available for `@Document` annotation but this will set value for all indexes in collection.

**Comment by christophstrobl** [comment]
Thank you for the PR @jakubpradzynski !

**Comment by StefanTirea** [comment]
Actually I created the PR and referenced this ticket because it would also solve this one 😁. I would be happy for feedback on it if you find the time to review it @christophstrobl .

**Comment by chandni-navani** [comment]
Can someone explain how to use this new index and what versions it's available in?
