### ISSUE TITLE
Support @RepositoryDefinition add "pagingAndSorting" field

### ISSUE THREAD

**Issue by YoungTakhin** [spring-projects/spring-data-mongodb#4134]
Could the annotation @RepositoryDefinition support  add "pagingAndSorting" field to enhance the MongoTemplate?

**Comment by mp911de** [comment]
What is a `pagingAndSorting` field and how is that related to the Template API? I currently do not understand what you're asking for. What problem are you trying to solve?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
