### ISSUE TITLE
How do I konw the compatible spring-boot version?

### ISSUE THREAD

**Issue by wangyi7099** [spring-projects/spring-data-mongodb#4136]
For example, if I use spring-data-mongodb 3.4.2, but how do I know the compatible spring-boot version ? Thanks!

**Comment by mp911de** [comment]
Spring Boot documents their Spring Data dependency in the [Spring Boot release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes).
