### ISSUE TITLE
[Question] How to update MongoDB Credentials at runtime

### ISSUE THREAD

**Issue by sullrich84** [spring-projects/spring-data-mongodb#4143]
I'm using `spring-boot-starter-data-mongodb-reactive` along with `spring-cloud-vault-config-databases` for dynamic secret rotations. Whenever the secret lease expires, I need to manually update the `MongoClient` credentials. Unfortunately I found no way to do so, since the credentials field in `MongoClientImpl.settings` can't be reassigned.

Is there any efficient way to achieve this, without swapping the hole MongoDB client configuration? I already asked this on StackOverflow but with no feedback.

**Comment by mp911de** [comment]
There is no mechanism to update credentials yet. You can follow https://jira.mongodb.org/browse/JAVA-3896 which enables credential rotation within the driver. 

Credential rotation is likely being provided by the driver entirely so closing this ticket.
