### ISSUE TITLE
MongoTemplate应当优化的两点

### ISSUE THREAD

**Issue by Sunw730** [spring-projects/spring-data-mongodb#4149]
First, the background.

Recently I did a project and I wanted to use `MongoTemplate` to query the data collection corresponding to a certain Entity, and then to convert it into a Dto type; and the fields in the Dto and the Entity were the same, so I hoped that `MongoTemplate` would directly query a Document and convert it into a Dto instead of an Entity.

However, I looked at the `MongoTemplate` source code, and found that it could not be realized for the reason below:

## `MongoTemple` should provide the following methods but it did not:

1. <code>public <T, R> R findOne(Query query, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
2. <code>public <T, R> List<R> find(Query query, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
3. <code>public <T, R> R findById(Object id, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
4. <code>public <T, R> R findAndModify(Query query, UpdateDefinition update, FindAndModifyOptions options, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
5. <code>public <T, R> R findAndRemove(Query query, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
6. <code>public <T, R> List<R> findAll(Class<T> entityClass, String collectionName, Class<R> resultClass)</code>
7. <code>public <T, R> List<R> findAllAndRemove(Query query, Class<T> entityClass, String collectionName, Class<R> resultClass)</code>

These methods will make `MongoTemplate` more flexible.

## The inner class or method modifiers in `MongoTemplate` was inapporpriate.

A method is defined in `MongoTemplate`, as follows:

<code>protected <S, T> List<T> doFind(String collectionName, Document query, Document fields, Class&lt;S> entityClass, CursorPreparer preparer, DocumentCallback<T> objectCallback)</code>

This is a protected method, which should be allowed to be overridden by subclasses, but the parameter <code>DocumentCallback</code> is the internal interface in `MongoTemplate`, which is only visible to the package, This means that the protected method cannot be overridden by subclasses, which makes no sense.

    Hope for an improved `MongoTemplate`.

**Comment by christophstrobl** [comment]
Please report issues in English, thank you!

**Comment by Sunw730** [comment]
> Please report issues in English, thank you!

I have reported it in English.

**Comment by christophstrobl** [comment]
Thank you. We'll revisit the _protected doFind(...)_ method. Meanwhile, have you checked the [Fluent Template API](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.query.fluent-template-api)? 
It allows to define the mapping source as well as target class for read/write ops

```java
List<Jedi> all = template.find(SWCharacter.class)    
  .as(Jedi.class)
  .matching(where(...
```

**Comment by Sunw730** [comment]
> Thank you. We'll revisit the _protected doFind(...)_ method. Meanwhile, have you checked the [Fluent Template API](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.query.fluent-template-api)? It allows to define the mapping source as well as target class for read/write ops
> 
> ```java
> List<Jedi> all = template.find(SWCharacter.class)    
>   .as(Jedi.class)
>   .matching(where(...
> ```

Thanks, I will try it.
