### ISSUE TITLE
Switch MongoOperations.updateMulti Kotlin extension function to accept a more generic UpdateDefinition

### ISSUE THREAD

**Issue by gavvvr** [spring-projects/spring-data-mongodb#4153]
Today I was surprised, that I can't express the same update with Kotlin, which I can express with Java's MongoOperations API. My code was
```java
mongoTemplate.updateMulti(
    Query.query(Criteria.where("someField").type(JsonSchemaObject.Type.DOUBLE)),
    AggregationUpdate.update()
        .set(...),
  MyEnt::class.java
)
```

Usually Kotlin extension allows me to write the same code, but without ugly `::class.java`. So I would expect the following to work:

```kotlin
mongoTemplate.updateMulti<MyEnt>(
    Query.query(Criteria.where("someField").type(JsonSchemaObject.Type.DOUBLE)),
    AggregationUpdate.update()
        .set(...)
)
```
but it does not compile.

The reason is that the signature of Kotlin extension for `MongoOperations` is different from the one defined on the original `MongoOperations` interface method:

https://github.com/spring-projects/spring-data-mongodb/blob/3342c75ecf3e560c70637155df8cae658ff4a6bb/spring-data-mongodb/src/main/kotlin/org/springframework/data/mongodb/core/MongoOperationsExtensions.kt#L538-L540

https://github.com/spring-projects/spring-data-mongodb/blob/3342c75ecf3e560c70637155df8cae658ff4a6bb/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoOperations.java#L1511

The Kotlin extension accepts a more narrow type `org.springframework.data.mongodb.core.query.Update` type, while the Java interface accepts a more generic `org.springframework.data.mongodb.core.query.UpdateDefinition`.

By looking at the implementation of the Kotlin extension, I see not reasons for it to accept a different type. So, I think the type accepted by Kotlin extension function should be aligned with the one defined on the original interface it extends.

**Comment by christophstrobl** [comment]
@gavvvr thanks for pointing that out. If you have the time - a PR would be welcome :)
