### ISSUE TITLE
TimeSeries Collection without createCollection

### ISSUE THREAD

**Issue by MartinMogh** [spring-projects/spring-data-mongodb#4166]
When using timeseries annotation 

```java
@TimeSeries(collection = "test", timeField = "timestamp", metaField = "metaData")
public class MyDocument{
    @MongoId
    private String id;
    private Date timestamp;
    private MetaData metaData;

    public static class MetaData {
        private String test;
    }
}
```
then saving without calling createCollection

```java
mongoTemplate.save(myDocument) 
```

a new none timeseries collection is created.

This might be a bug?

**Comment by christophstrobl** [comment]
time series collections need to be created before inserting data as mentioned in the [reference documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#time-series)

**Comment by EndermanAPM** [comment]
Is there any technical reason why Spring data can't handle this? or it's just a missing feature?

**Comment by christophstrobl** [comment]
@EndermanAPM We cannot tell upfront if a collection already exists. To support this we'd need to issue additional calls on every insert/update operation to find out (cause the collection might have been dropped inbetween) and potentially run the collection creation. 
Using a `BeforeSaveCallback` offers a hook that allows to run this kind of checks. You can find more about this in the [Reference Documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#entity-callbacks.implement).

**Comment by EndermanAPM** [comment]
@christophstrobl I don't have any idea of the inner workings of mongodata so please correct me if I'm wrong, but when storing the document using a MongoRepository already creates the collection, couldn't then get the collection type be sent? Or mongo implicitly creates the collection when new documents get send?
