### ISSUE TITLE
Change Streams fullDocumentBeforeChange support

### ISSUE THREAD

**Issue by kufd** [spring-projects/spring-data-mongodb#4187]
Hi,

In my project, I need to receive a Full Document Before Change from Change Streams
This feature is available in mongo 6 and in mongo-java-driver

Do you have any plans for its implementation in spring-data-mongodb?

Maybe it makes sense for me to try to provide a pull request?

**Comment by christophstrobl** [comment]
Thanks for the heads up. A PR is always welcome. Please make sure to read the [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc).
