### ISSUE TITLE
Why doesn't add field to Object in Aggregation addFields Operator?

### ISSUE THREAD

**Issue by lsb530** [spring-projects/spring-data-mongodb#4214]
AddFieldsOperation addFields = addFields()
.addField("type").withValue("test").build();

mongoTemplate.aggregate To Object.class..

But It didn't added fields dynamically..
I know java is compiled language, if you can update added field to Object.

It works differently Mongo Compass pipeline

Thank you

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

**Comment by lsb530** [comment]
Yes, I think It is quite impossible because Aggregation called by API so it it runtime.
But Java is compile language. Can it be added new field to Object in Runtime?

**Comment by christophstrobl** [comment]
I still struggle to understand what you want to achieve, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by lsb530** [comment]
Okay..! Since i am in company.. Approximately 1 hour half, i will make it. Thank you

**Comment by christophstrobl** [comment]
Thanks for the feedback, glad it works for you now.
