### ISSUE TITLE
Introduce a system for handling polymorphism with a little more agility

### ISSUE THREAD

**Issue by PierrickPuimeanChieze** [spring-projects/spring-data-mongodb#4219]
Currently, polymorphism is handled by mongoDB using the _class attribute. It work well in itself, but I would like to be able to customize it. 

For example, let's imagine we have an Order class, which can come from two different provider, each one having a different way to identifying it. so we have an interface `OrderId` which define a getter `getProviderId` (returning an Id for the provider), and two implementation, `ProviderAOrderId` and `ProviderBOrderId`.

```java
interface OrderId {

    String getProviderId();
}
```
```java

class ProviderAOrderId implements OrderId {
    private String warehouseId;
    private String partId;

    @Override
    public String getProviderId() {
        return "PROVIDER_A";
    }
    // Getter and setter omitted for the sake of brevity
}

```
```java
class ProviderBOrderId implements OrderId {
    private String orderId;

    @Override
    public String getProviderId() {
        return "PROVIDER_B";
    }
    // Getter and setter omitted for the sake of brevity

}
```

I would like to have a mechanism for indicating to mongoDB to get rid of the _class attribute when serializing `ProviderAOrderId` and `ProviderBOrderId` and to use the value of `getProviderId` to find the correct implementation class.

I see at least two reasons for that : 
- If we have two application which access these data, it make no sense for one of them to have an insight to the internal of the other one.
- In case of refactoring, it keep the said refactoring local to the code, you don't have to update your data to finalize it.

A good example of said-agility is how jackson use the two annotations `JsonTypeInfo` and `JsonSubTypes` to handle. I don't say that the solution I would like to see implemented, but it give a good insight on how a more agile method could be use.

Thanks you.

**Comment by mp911de** [comment]
You can achieve this customization by providing your implementation of `MongoTypeMapper`. The default implementation `DefaultMongoTypeMapper` can customize the field name that is used in the `Document`. 

Type hints can be read and written in the context of an existing type hint (e.g. `writeType(Class<?> type, …)`, `readType(S source, TypeInformation<T> defaultType)`) but also without having a target Java type (`TypeInformation<?> readType(S source)`).

Let us know whether this hook is sufficient for your use case.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
