### ISSUE TITLE
Transaction rollback handling - API Usage question

### ISSUE THREAD

**Issue by alexanderankin** [spring-projects/spring-data-mongodb#4223]
https://github.com/spring-projects/spring-data-mongodb/blob/8aab5e5a0160317cf38724a6a9e4404c90e077f4/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoOperations.java#L200-L204

How is the client code supposed to invoke this library code so that a transaction rollback is possible? It seems like this should already be something that happens in mongooperations. The below is not very user friendly

```java
MongoOperations mo = ...;
AtomicReference<Throwable> t = new AtomicReference<>();
mo.withSession(getClientSessionOptions()).execute((withSession) -> {
  try {
    // something
    return 1;
  } catch (tr) {
    t.set(tr);
  },
  session -> { t.get() == null ? session.commit() : session.rollback(); });
```

**Comment by mp911de** [comment]
Care to elaborate on what you want to achieve? Spring's transaction management is built with the assumption of rolling back on exceptions. That means any exception thrown from the code enclosed in a transaction will lead to a rollback.

Generally, you would configure a `MongoTransactionManager` bean and use transactions either through `@Transactional` methods or `TransactionTemplate`. The approach via the session is low-level code and should not be the default case.

The [reference documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.transactions.transaction-template) is your friend.
