### ISSUE TITLE
Unable to run toJson() on org.springframework.data.mongodb.core.query.Query after using .projectAs() on the fields object

### ISSUE THREAD

**Issue by rdhillon1016** [spring-projects/spring-data-mongodb#4232]
Version: 3.4.5

**Reproduction Steps:**

1. Initialize a query
`Query query = new Query();`
2. Add to the Field using .projectAs, using any of the official examples on the API javadocs
`// native MongoDB expression`
`.projectAs(MongoExpression.create("'$toUpper' : '$name'"), "name");`
or
`// Aggregation Framework expression`
`.projectAs(StringOperators.valueOf("name").toUpper(), "name");`
or
`// Aggregation Framework SpEL expression`
`.projectAs(AggregationSpELExpression.expressionOf("toUpper(name)"), "name");`
3. Convert to JSON (or do basically any other operation on the document)
`query.getFieldsObject().toJson()`

**Results in an exception like the following (different class for each case, but same exception):**

Example for native MongoDB expression:
`Exception in thread "main" org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class org.springframework.data.mongodb.BindableMongoExpression`

Seems like an issue similar to:
https://github.com/spring-projects/spring-data-mongodb/issues/2857

**Comment by christophstrobl** [comment]
`query.getFieldsObject()` is subject to further processing within the mapping layer and may contain types not directly writeable by any bson codec. `org.springframework.data.mongodb.core.query.SerializationUtils#serializeToJsonSafely` creates a pseudo JSON representation as far as possible which can be used for eg. logging purposes.

**Comment by rdhillon1016** [comment]
So is this not a bug in the library?
Essentially the `.getFieldsObject()` method isn't transforming Spring Data MongoDB types like AggregationSpELExpression into its document, MongoDB simple type form.

This led to me to believe that this was unintended behaviour, considering the Aggregation equivalent:
`ProjectionOperation.andExpression(...)`
and then
`Aggregation.toString()` returns the expected response.

Otherwise, how would one convert the document returned by `.getFieldsObject()` into something that _is_ writeable by a bson codec, considering types like BindableMongoExpression and AggregationSpELExpression aren't custom types created by the user?

**Comment by christophstrobl** [comment]
As mentioned, the mapping layer with its `QueryMapper`, `UpdateMapper`, etc. is responsible for creating a driver native representation.
