### ISSUE TITLE
MongoTransactionManager.debugString() always contains error

### ISSUE THREAD

**Issue by kacz** [spring-projects/spring-data-mongodb#4241]
If server session is not null, String formatting in `MongoTransactionManager.debugString()` fails and therefore the output always contains "error = d != java.lang.Boolean".
The root cause is on line `String.format("closed = %d, ", session.getServerSession().isClosed())` as boolean is not accepted by `%d`.

**Comment by christophstrobl** [comment]
Good catch @kacz! Should have been `%b`.
