### ISSUE TITLE
Duplicate log in query execution 

### ISSUE THREAD

**Issue by Raghav2211** [spring-projects/spring-data-mongodb#4253]
Hi,
  I'm not quite sure if this is a duplicate or I'm missing something 
  
  https://github.com/spring-projects/spring-data-mongodb/blob/187f260fe4d868f76f9b2a9b08b01d05fa82f4ab/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/ReactiveMongoTemplate.java#L2168
  
  https://github.com/spring-projects/spring-data-mongodb/blob/187f260fe4d868f76f9b2a9b08b01d05fa82f4ab/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/ReactiveMongoTemplate.java#L2636
  
  This is replicate in [MonoTemplate](https://github.com/spring-projects/spring-data-mongodb/blob/187f260fe4d868f76f9b2a9b08b01d05fa82f4ab/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoTemplate.java#L163) also
  
Spring boot version: 3.0.0
 Java version: 17 
 
 Thanks

**Comment by christophstrobl** [comment]
Good catch - thanks for reporting!

**Comment by Raghav2211** [comment]
@christophstrobl Thanks for reviewing it , I submitted a PR against it [PR](https://github.com/spring-projects/spring-data-mongodb/pull/4259) Please let me know if any concern.
