### ISSUE TITLE
Is the matcherType of EXACT wrong ? It is a regular expression not the exact string

### ISSUE THREAD

**Issue by xuyingjie-coder** [spring-projects/spring-data-mongodb#4254]
https://github.com/spring-projects/spring-data-mongodb/blob/187f260fe4d868f76f9b2a9b08b01d05fa82f4ab/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/query/MongoRegexCreator.java#L84

Thanks

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
