### ISSUE TITLE
Add factory method for combined Criteria (and, or)

### ISSUE THREAD

**Issue by sdutry** [spring-projects/spring-data-mongodb#4257]
Currently it's inconvenient to create combined conditions (multiple and or) combinations.

It would be easier if there was a factory method for creating combined criteria.

**Comment by sdutry** [comment]
will provide a PR

**Comment by mp911de** [comment]
How about using `new Criteria().andOperator(…)` or `new Criteria().orOperator(…)`?

**Comment by sdutry** [comment]
you are correct, i did not think about using a new empty Criteria object to do a `andOperator` or `orOperator`:

just tested it in those tests and the criteria definitions below work just as well.

```
		var criteria = (new Criteria())
				.andOperator(Criteria.where("x").is(true), Criteria.where("y").is(42),
						Criteria.where("z").is("value"));
```

```
		var criteria = (new Criteria())
				.orOperator(Criteria.where("x").is(true), Criteria.where("y").is(42),
						Criteria.where("z").is("value"));
```

My apologies, didn't realize this was the way to create this.

**Comment by sdutry** [comment]
existing method for same result exists, closing issue
