### ISSUE TITLE
MongoDB aggregate grouping operation

### ISSUE THREAD

**Issue by authub** [spring-projects/spring-data-mongodb#4269]
I want to use MongoTemplate to do the following actions:
```
db.books.aggregate([
    {
        $group: {
            _id: {
                author: "$author"
            },
            books: {
                $push: "$title"
            }
        }
    }
])
```
An existing GroupOperation could not be completed.
The version I am using is：
``` 
<dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-mongodb</artifactId>
      <version>3.3.4</version>
 </dependency>
```
I don't know if this is a bug, or I'm using it wrong. I didn't find the sample I needed in the documentation

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Please add the code you're using to create the operation with Spring Data. Ideally take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by infoShare** [comment]
@authub - are you sure this is not possible using something similar:
mongoTemplate.aggregate(newAggregation(group("author").push("title").as("books")), "books", Document.class);
Which is equivalent to
{"aggregate": "books", "pipeline": [{"$group": {**"_id": "$author",** "books": {"$push": "$title"}}}]
More or less same functionality.

Spring-data-mongodb is not generating nested fields for single fields which can be checked on GroupOperation.toDocument()
method [idFields.exposesSingleNonSyntheticFieldOnly()]
