### ISSUE TITLE
Support/Bug - MongoRepository methods are missing

### ISSUE THREAD

**Issue by tara-9** [spring-projects/spring-data-mongodb#4276]
spring-data-mongodb: version: **4.0.1**
springboot-version: **2.7.1**

When upgrading to the above version some of the methods of `MongoRepository` are not available for eg: `deleteAll()`, `findByid()`.

And looking at the source code the `MongoRepository` the parent interface `ListCrudRepository` and `ListPagingAndSortingRepository` are not included in the jar. I believe that's the issue for this.

Are we missing something? If not is it possible to get a fix?

Dependency:
`implementation 'org.springframework.data:spring-data-mongodb:4.0.1'`

**Comment by christophstrobl** [comment]
This sounds like there's a mismatch in the dependencies. Please always make sure to not only upgrade `data-mongodb` but also the base `spring-data-commons` artifact.

**Comment by tara-9** [comment]
Thanks @christophstrobl indeed that was the issue. Upgrading that dependency worked
