### ISSUE TITLE
Allow configuration of `ReadConcern` for queries and aggregations

### ISSUE THREAD

**Issue by sad3rasd** [spring-projects/spring-data-mongodb#4277]
Hi,
I would like to use find and aggregate query with readConcern level "snapshot" (and "atClusterTime") in order to get data at a specified point in time.

I can't find any way to implement this with spring data mongodb, am I miss something?
If not already available, how can be implemented using MongoTemplate? Also could this feature be added?

more info: https://www.mongodb.com/docs/manual/reference/read-concern-snapshot/

**Comment by mp911de** [comment]
`ReadPreferences` can be set via:

1. `MongoTemplate` for commands that operate on a collection
2. `Query` meta flags via `CursorOption.SECONDARY_READS`

It would be neat if we could provide the `ReadPreference` through `Query` and `AggregationOptions`.

**Comment by mp911de** [comment]
Please note that `atClusterTime` is a driver-internal attribute that is used with client sessions to track the latest cluster time. It is not intended to go back in time. See also the specification on snapshot reads:

https://github.com/mongodb/specifications/blob/master/source/sessions/snapshot-sessions.rst

> For snapshot reads the driver MUST first obtain atClusterTime from the server response of a find/aggregate/distinct command, by specifying readConcern with snapshot level field, and store it as snapshotTime in the ClientSession object.
> 
> ```
> {
>     find : <string>, // or other read command
>     ... // the rest of the command parameters
>     readConcern :
>     {
>         level : "snapshot"
>     }
> }
> ```
> 
> For subsequent reads in the same session, the driver MUST send the snapshotTime saved in the ClientSession as the value of the atClusterTime field of the readConcern with a snapshot level:
> 
> ```
> {
>     find : <string>, // or other read command
>     ... // the rest of the command parameters
>     readConcern :
>     {
>         level : "snapshot",
>         atClusterTime : <BsonTimestamp>
>     }
> }
> ```

The current documentation creates a slightly different impression of a wayback-machine.
