### ISSUE TITLE
org.bson.codecs.Codec is ignored

### ISSUE THREAD

**Issue by zenbones** [spring-projects/spring-data-mongodb#4279]
I have a Codec registered for a type. If I get codec registry from the mongo client and ask what the codec is for my type I gat back my codec. All good. That codec is never called because the mongo converter something or other takes it upon itself to convert my type and does not bother to ask the client if there's already a codec for it. How can I tell spring data for mongodb to leave my type alone and use the codec registered with the client?

**Comment by christophstrobl** [comment]
Spring Data is using `CustomConversions` to tweak store specific representations of types.
MongoDB's `CodecRegistry` and `Codec`s work differently from how the data project handles those tasks. Integrations attempts have not succeeded, breaking query and update behaviour.
Maybe you could elaborate a bit on what you're trying to do cause at the time of writing there is no straight forward of setting up the conversion engine in a way that supports usage of custom `Codec`s. You may want to have a look at using a `ConverterFactory` as outlined [here](https://gist.github.com/christophstrobl/7299a1e28aee18af14ff).

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
