### ISSUE TITLE
After migrating to spring boot 3.0.2 getting - Couldn't find PersistentEntity for type class org.bson.Document

### ISSUE THREAD

**Issue by serleonsolo2** [spring-projects/spring-data-mongodb#4300]
After upgrading to 
_spring boot 3.0.2
spring-data-mongodb-4.0.1
spring-data-commons-3.0.1_

All calls like below are failing with **Couldn't find PersistentEntity for type class org.bson.Document**:

```
reactiveMongoTemplate.findAndReplace(
                    query,
                    replacement,
                    options,
                    Document::class.java,
                    MasterData.COLLECTION_NAME,
                    MasterData::class.java
                )
```

replacement has no id field, type is org.bson.Document

PS The same code works without any issues on versions:
_spring-data-mongodb-3.2.10
spring-data-commons-2.5.10_

**Comment by christophstrobl** [comment]
@serleonsolo2 thanks for reporting!
