### ISSUE TITLE
Support dynamic conversion of manual reference

### ISSUE THREAD

**Issue by RobinSchwaller** [spring-projects/spring-data-mongodb#4303]
### Use-Case
Support eventual conversion for a reference field (type `String`) which may contain a valid ObjectId, so that the actual type of the field in the database is dynamic (similar behavior like `@Id` or `@MongoId`).

### Example 
```java
public class A {
  @Id
  public String id; 
}

public class B {
  @Id
  public String id;
  public String AId;
}
```
**DB representation**

A.id... 
 * has objectId string -> saved as ObjectId
 * has other string -> saves as String
  
B.AId...
* has objectId string -> saved as String (**desired to be ObjectId**)
* has other string -> saved as String
   
Since obviously you can only have one field annotated with `@Id`, would it be possible to add a new annotation (maybe something like `@ReferenceId`?) which does the same conversion as `@Id` but doesn't have the other characteristics?  
   
`@Field` with targetType goes in the direction but the problem is that it forces the specified type and doesn't allow the defined type from the code.
 
Reasoning:
- We like the flexibility of having our IDs typed as string
- Automatic conversion from and into ObjectId is valuable because of performance/functionality on the DB side

Problem:
- If the referenced IDs does not also support auto-conversion like the ID field we see potential problems regarding joins on the DB side (if ID of A is stored as ObjectId and its reference on B is stored as String)

Having a way (annotation) to support this would let us use all the benefits mentioned above.

**Comment by christophstrobl** [comment]
Have you tried using the `@Field` annotation explicitly defining the desired target type as described in the [reference documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.custom-converters)?

```java
@Field(targetType = OBJECT_ID)
String AId;
```

**Comment by RobinSchwaller** [comment]
Thanks for your response.
  
Yes we tried that, the problem is that once you want to save a string which is not a valid objectId, you will get an exception instead of the the string simply getting saved. So I guess `@Field` doesn't support dynamic types (the conversion `@Id` does for example).

**Comment by christophstrobl** [comment]
For that kind of flexible conversion please use [property specific conversion](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.property-converters).

**Comment by RobinSchwaller** [comment]
We implemented it with a custom converter now, thank you!
