### ISSUE TITLE
Add support for keyset scrolling

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-mongodb#4308]
Based on https://github.com/spring-projects/spring-data-commons/issues/2151, we want to add means to consume a query result set through a scroll API to be able to resume querying at a later stage. We want to introduce keyset-based pagination which allows using keysets to reconstruct a scroll position for subsequent queries.

Tasks:
- [ ] #4317
- [x] #4325
- [x] #4326

**Comment by christophstrobl** [comment]
resolved via #4317
