### ISSUE TITLE
Spring Reactive Mongo @Aggregation causes Mongo Atlas alerts

### ISSUE THREAD

**Issue by bskorka** [spring-projects/spring-data-mongodb#4319]
Hey!
I have observed that one of my queries caused a lot of Mongo Atlas alerts related to Examined / Returned ratio - "Query Targeting: Scanned Objects / Returned has gone above 1000".

I checked whether the index is used and ran explain through the Studio 3T software to track the issue. I saw that the same query ran in Studio 3T doesn't cause the alert, when that one ran as `@Aggregate` in Spring does.

In Mongo Atlas I have observed that all queries reported 32 Docs returned.
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/2901362/223216015-567ecefb-d00d-4ff9-99ae-19a4a801d4fd.png">

I think that it is not true cause the same query run in Studio 3T returned for example 615 documents and the ratio examined/returned instead of 252 is 13 docs.

I believe that 32 documents that are returned can be related to "reactor.bufferSize.x" default size of 32 in `Flux`. Is there a possibility to report the different (real) values of found records in Mongo? Is it the issue on the client or server side?

Spring Boot version I'm using is 2.7.8, and Spring Dependency Management version is 1.0.15.RELEASE.

Repository code:
```java
@Repository
public interface SomeRepository extends ReactiveMongoRepository<SomeData, ObjectId> {

    @Aggregation(
            pipeline = {
                    "{ $match : { 'firstId' : ?0, 'data.secondId._id' : { $in : ?1 } } }",
                    "{ $set : { 'data' : { $filter : { 'input' : '$data', as : 'd', cond : { $in : [ '$$data.secondId._id', ?1 ] } } } } }",
                    "{ $unwind : '$data' }",
                    "{ $group : { '_id' : '$data.secondId._id', 'lastUpdated' : { $max : '$data.lastUpdated' } } }",
            }
    )
    Flux<LastUpdatedWithSecondId> findMaximumLastUpdatedDateBySecondIdForAnFirst(Integer firstId, List<String> dataIds);

    @Data
    class LastUpdatedWithSecondId {
        private String id;
        private OffsetDateTime lastUpdated;
    }

}
```

**Comment by mp911de** [comment]
Reactive API usage is subject to propagate backpressure towards the cursor. This means, any prefetch size and any number of consumed documents are passed on to the actual cursor by specifying the batch size. You can control the batch size by either specifying `@Meta(cursorBatchSize=…)` or you can shape the demand via `limitRate(…)` that translates into the fetch size.

If your result consumption terminates before the entire result is consumed, then you end up with a similar case that you do not fetch all documents from the aggregation.

**Comment by bskorka** [comment]
I see that I have not specified it, but in the end, I'm getting all results from the database - so in the above case I got all results into `.collectList()`, but still, it reports only 32 objects to the driver(?).
Is increasing the `cursorBatchSize` to the expected number of returned records the only way to avoid the issue?

**Comment by mp911de** [comment]
Yes, configuring the batch size is the ideal approach. But if you fetch all data into a List, I wonder why Atlas reports that only a subset was fetched. That alert seems buggy to me (or I do not understand it). In any case, I recommend reaching out to the Atlas folks for clarification.

Closing this ticket until there's something actionable.
