### ISSUE TITLE
Query with or operator and text search

### ISSUE THREAD

**Issue by DUMINGZHI** [spring-projects/spring-data-mongodb#4320]
public Criteria orOperator(Criteria... criteria) {
        BasicDBList bsonList = this.createCriteriaList(criteria);
        return this.registerCriteriaChainElement((new Criteria("$or")).is(bsonList));
    }

Input parameter is only type Criteria, Why not try to support TextCriteria at the same time? both implemented in CriteriaDefinition.

    public Criteria orOperator(CriteriaDefinition... criteria) {
        BasicDBList bsonList = this.createCriteriaList(criteria);
        return this.registerCriteriaChainElement((new Criteria("$or")).is(bsonList));
    }

**Comment by christophstrobl** [comment]
duplicate of #3895
