### ISSUE TITLE
Couldn't find PersistentEntity for type class java.lang.Integer

### ISSUE THREAD

**Issue by dhavaamar** [spring-projects/spring-data-mongodb#4329]
While trying to upsert a Integer/Long/List<Integer>, I am getting Couldn't find PersistentEntity for type class...

The MongoCustomConvertions are **working completely fine for Custom Conversion** Classes. Only **basic types like Integer, Long are failing.**

**Source Code:**

MongoCustomConversions bean defined in MongoConfig file.

```
public class MongoConfigContext extends AbstractMongoClientConfiguration { 
.....
.....
.....
    @Override
    @Bean
    public MongoCustomConversions customConversions() {
        List<Converter<?, ?>> converters = new ArrayList<>();
        if (extension != null) {
            List<Converter<?, ?>> additionalConverters = extension.additionalConverters();
            if (!CollectionUtils.isEmpty(additionalConverters)) {
                converters.addAll(extension.additionalConverters());
            }
        }
        return new MongoCustomConversions(converters);
    }
.....
.....
.....
}
```
Since this is the part of parent library, I added an abstract class to provide a way to add CustomConversions in service through MongoConfigContextExtension class.

```
public abstract class MongoConfigContextExtension {
    
    public List<Converter<?, ?>> additionalConverters() {
        return Collections.emptyList();
    }

}
```
Method written to convert any Object to DBObject

```
protected Object convertToDbData(Object data) {
    if (data == null || data instanceof BSONObject || data instanceof String) {
        return data;
    } else {
        if (data instanceof Collection || data.getClass().isArray()) {
            BasicDBList list = new BasicDBList();
            ((Collection)data).forEach(datum -> {
                DBObject dbData = new BasicDBObject();
                converter.write(datum, (Bson) dbData); // fails when datum is numeric
                list.add(datum);
            });
            return list;
        } else {
            DBObject dbData = new BasicDBObject();
            converter.write(data, (Bson) dbData); // fails when datum is numeric
            return dbData;
        }
    }
}
```
Test class:

```
@Test
    public void testIntCovert() {
        Integer val = new Integer(20);
        curator.update(DEMO_PATH, val, Integer.class);
    }
```
Error Log:

```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.Integer

    at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:80)
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:883)
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:834)
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:120)
    at com.abc.def.xyz.event.ConfigEventHandler.convertToDbData(ConfigEventHandler.java:52)
```

I cloned spring-data-mongodb project in my system, I tried execute same test case from the **MappingMongoConverterUnitTests**

![image](https://user-images.githubusercontent.com/81572944/224955541-af1acae8-9c17-4be9-b217-d35f6d0fc9da.png)

Write for Integer/Long/List<Integer> were supported in 1.x and 2.x versions and working fine, it is failing with latest version of spring-data-mongodb.

Kindly clarify whether this support has been removed? Is this a valid use case? If yes, Am I missing any config to be added? Please support!

**Comment by christophstrobl** [comment]
I'm not sure I understand the issue. The `MappingMongoConverter` is intended to read/write types that qualify as entities and not simple types. 
The description only contains partial data, mentioning custom converters, update and a Stacktrace where a custom `ConfigEventHandler` seems to calling the converter directly. All of this creates an incomplete picture of what is going on.
So please, if you'd like us to spend some time investigating, take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by dhavaamar** [comment]
@christophstrobl Thank you so much for the quick reply!
 > I'm not sure I understand the issue. The MappingMongoConverter is intended to read/write types that qualify as entities and not simple types.
 Exactly this is what my questions was! This is clear.

**One more question:** Read/write of both simple types and entities were working fine with Spring earlier versions. But now it is failing for simple types alone. So, Is this an intended change made by spring-data-mongodb library?(Though I understand, there is no need of read/write type for simple types)

**Comment by christophstrobl** [comment]
The behaviour of the `MappingMongoConverter` in that regard is the same as in version 2.0.x which is out of maintenance since mid 2020 already. So the above test does not seem to be a valid reproducer for the issue. As mentioned before, it is hard to tell what's not working without having a full failing sample.

**Comment by dhavaamar** [comment]
The below test works fine in spring-data-mongodb 1.x versions and fails in the recent version say spring-data-mongodb 3.x

@Test
public void testWriteInteger() {
	Integer val = new Integer("12");
	DBObject dbObject1 = new BasicDBObject();
	converter.write(val, dbObject1);                                     //fails here
	//Some Asserts
}

Fail Reason : Couldn't find PersistentEntity for type class java.lang.Integer

Just want to know if this is intended change!

**Comment by christophstrobl** [comment]
The current behaviour is the intended one.

**Comment by dhavaamar** [comment]
Thank you!
