### ISSUE TITLE
Package private visibility of ConversionContext prevents subclassing of MappingMongoConverter 

### ISSUE THREAD

**Issue by H3adcra5h** [spring-projects/spring-data-mongodb#4345]
We changed from Version 3.3.3 to 3.4.8 by updating Spring Boot from 2.6.6 to 2.7.9.

The visibility of class ConversionContext changed from protected to package private.
Creating a subclass of MappingMongoConverter and overwrite the protected method readDocument is no longer possible if the subclass package is outside of org.springframework.data.mongodb.core.convert. Same with other protected methods that use ConversionContext as parameter.

**Comment by christophstrobl** [comment]
@H3adcra5h thanks for reporting - my bad. sorry for the inconvenience - we'll get this fixed.

**Comment by H3adcra5h** [comment]
Great! Thanks!
