### ISSUE TITLE
Add hidden option for index

### ISSUE THREAD

**Issue by nayu139** [spring-projects/spring-data-mongodb#4348]
I need hidden option when ensureIndex. I have already coded it on my computer, but I don't kown how to push it~

ex:
     Index index = new Index();
     index.named(indexName).background().hidden();
     indexOperations.ensureIndex(index);
and get is hidden when get index info, ex:
    indexOperations.getIndexInfo();

**Comment by nayu139** [comment]
@christophstrobl  Would you add it at 3.3.x branch

**Comment by christophstrobl** [comment]
Thank you @nayu139 for raising this issue. Please make sure to follow the [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc) and open a [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on GH for the modification you propose.
The team will then review the changes and get back to you. Note that reviewing changes can take some time, so please be patient.
The _3.3.x_ line already has already reached the end date of its support. Generally speaking we do not back port enhancements to older versions which typically only see bug fixes and patch level dependency upgrades.

**Comment by nayu139** [comment]
Thank you very much! I already open a PR. Thanks for your guide😀

https://github.com/spring-projects/spring-data-mongodb/pull/4349￼
Add hidden support for index by nayu139 · Pull Request #4349 · spring-projects/spring-data-mongodb
github.com
