### ISSUE TITLE
Sort information does not show up on QueryDebug in doFind

### ISSUE THREAD

**Issue by lomuto** [spring-projects/spring-data-mongodb#4375]
## Version
- java: 11
- spring: 2.6.9
- spring-data-mongodb: 3.3.5

---

in `MongoTemplate.java:2577` if Debug is enabled, logger will left the debug log on console   

<img width="700" alt="Screenshot 2023-04-26 at 11 58 52 PM" src="https://user-images.githubusercontent.com/64261642/234617026-f951f0de-1d04-4650-8161-4b7caec781f6.png">

while query info is serialized with `serializeToJsonSafely` with `mappendQuery`
and `mappedQuery` is retrieved from `queryContext`
and for last, `queryContext` is retrieved from argument `query` and `field` through `BasicQuery`  
   
<img width="700" alt="Screenshot 2023-04-27 at 12 02 33 AM" src="https://user-images.githubusercontent.com/64261642/234618996-fce162cf-6702-4731-a9b2-a447e73d9ade.png">   
   
The problem is
`BasicQuery` has sortObject field, but it is fallbacked with empty document   
   
<img width="700" alt="image" src="https://user-images.githubusercontent.com/64261642/234619580-67a701e4-c7fc-4e5b-85d9-7292f4fc19e9.png">   
   
So eventually, debug log has no information about sort at all   
   
<img width="400" alt="Screenshot 2023-04-27 at 12 12 27 AM" src="https://user-images.githubusercontent.com/64261642/234620960-7b7e876b-adb7-4346-9055-3175d720ec15.png">

---   
   
## Suggestion   
   
Luckly, we can still get sort information from `preparer` argument   
   
<img width="800" alt="Screenshot 2023-04-27 at 12 27 26 AM" src="https://user-images.githubusercontent.com/64261642/234625263-6e5818a9-ea1f-4b8a-b158-6fc7a9f2b80a.png">

Is there any chance that I can use it to fill out my sort information in query log? such as...   
   
``` java
Document mappedFields = queryContext.getMappedFields(entity, entityClass, projectionFactory);
Document mappedQuery = queryContext.getMappedQuery(entity);
Document mappedSort = ((QueryCursorPreparer) preparer).query.getSortObject();

if (LOGGER.isDebugEnabled()) {
    LOGGER.debug("find using query: {} fields: {} sort: {} for class: {} in collection: {}",
    serializeToJsonSafely(mappedQuery), mappedFields, mappedSort, entityClass, collectionName);
}
```   
   
thank you :)

**Comment by christophstrobl** [comment]
I'm sorry but I struggle to understand what you want to achieve. 
Maybe you can provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that shows what you're doing and what's missing in the log information.

**Comment by lomuto** [comment]
Apologize for the late feedback. I will post the sample before the end or week

**Comment by lomuto** [comment]
Here is a [github repository for minimal sample](https://github.com/lomuto/spring-mongodb-issue) that you have requested.   
Thank you :)

**Comment by christophstrobl** [comment]
Thank you @lomuto  for providing the sample!

At this point we do not intend to extend the current logging behavior to cover additional details, though we see there's value in this information. Still we think that using the MongoDB Driver logging facility is better suited for this. 

The MongoDB Java Driver allows to [log commands](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/logging/) sent to the server, which will not only give insight into the query but also its sort, projection, read preference, limit & offset,... 

This can be enabled via the `protocol` logger.

```xml
<logger name="org.mongodb.driver.protocol" level="DEBUG" />
```

Since the output can contain entries unrelated to actual find operations you may want to reduce the scope of what is logged.
I've outlined how this can work using e.g [Logback Filters](https://logback.qos.ch/manual/filters.html) below.


```xml
<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
        <evaluator>
            <matcher>
                <Name>finder</Name>
                <regex>Sending command.*"find":</regex>
            </matcher>
            <expression>finder.matches(formattedMessage)</expression>
        </evaluator>
        <OnMismatch>DENY</OnMismatch>
        <OnMatch>NEUTRAL</OnMatch>
    </filter>
    <encoder>
        <pattern>
            %-4relative [%thread] %-5level %logger{30} - %msg%n
        </pattern>
    </encoder>
</appender>

<logger name="org.mongodb.driver.protocol" level="DEBUG" appender="CONSOLE" />
```
