### ISSUE TITLE
Customizing Individual Repositories is not implemented correctly

### ISSUE THREAD

**Issue by vgarmash** [spring-projects/spring-data-mongodb#4380]
Section [8.6.1. Customizing Individual Repositories](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.single-repository-behavior) of the Spring Data MongoDb documentation describes how we can add custom methods to the repository interface. Please note that that section does not focus on implementing custom query methods but adding custom methods with additional logic in it. 

I tried to follow the documentation but got an exception. In my case I have an entity `ReportPersistenceTaskDoc`, with repository `ReportPersistenceTaskRepository` with added custom interface :

```
@CrossOrigin
@RepositoryRestResource(path = "reportPersistenceTasks", itemResourceRel = "reportPersistenceTask", collectionResourceRel = "reportPersistenceTasks")
@Primary
@SecurityRequirement(name = "JWT Bearer Token")
@PreAuthorize("isAuthenticated")
public interface ReportPersistenceTaskRepository extends MongoRepository<ReportPersistenceTaskDoc, String>,
        RepositoryScheduleSync {

}


...

//Custom interface
public interface RepositoryScheduleSync {

    void resyncTaskWithScheduler(@NotNull ReportPersistenceTaskDoc task);
}

//Custom interface implementation
@Component
@Slf4j
public class RepositoryScheduleSyncImpl implements RepositoryScheduleSync {

    @Autowired
    private ReportSchedulingService reportSchedulingService;

    @Autowired
    private MongoOperations mongoOps;

    @Override
    public void resyncTaskWithScheduler(ReportPersistenceTaskDoc task) {
        //Additional logic being executed here
    }
}


```

When I run the application, I am getting exception "org.springframework.data.mapping.PropertyReferenceException: No property 'resyncTaskWithScheduler' found for type 'ReportPersistenceTaskDoc'". It is true - the ReportPersistenceTaskDoc don't have such property - resyncTaskWithScheduler is a name of new custom method I want to add. I just followed the manual section 8.6.1 https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.single-repository-behavior

Here is full stacktrace for you to review:
[Stacktrace- adding custom repository method fails.txt](https://github.com/spring-projects/spring-data-mongodb/files/11362316/Stacktrace-.adding.custom.repository.method.fails.txt)

I use Spring Boot 2.7.9.

As of now we can work around this issue by adding custom controller with that logic as we already doing it in such cases. Although I wanted to let you know about this issue so you can add a fix for it in future releases.

**Comment by christophstrobl** [comment]
Thank you @vgarmash, unfortunately I was not able to reproduce the issue from the description above with a small project using Spring Boot `2.7.12` along with `data-mongo` and `data-rest`. 
I might be missing something here. If possible please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by christophstrobl** [comment]
Thanks you @vgarmash for the reproducer. By defining `basePackages` via `@EnableMongoRepositories` the component lookup is restricted to beans within that namespace.

You may consider to:
* remove the package restriction from `@EnableMongoRepositories`
* add the package containing the custom implementation to `@EnableMongoRepositories`
* or keep the package restriction as is and move the custom implementation closer to the actual repository
