### ISSUE TITLE
How to perform an upsert that doesn't update specific fields on update?

### ISSUE THREAD

**Issue by almogtavor** [spring-projects/spring-data-mongodb#4383]
I'm using reactive `bulkWrite` to write to Mongo upserts of `UpdateOneModel` like this:

```java

reactiveMongoTemplate.getCollection(config.getCollection()).flatMap(mongoCollection -> {
        var operations = entities.stream().map(entity -> {
            Document doc = new Document();
            reactiveMongoTemplate.getConverter().write(entity, doc);
            var filter = new Document("externalId", entity.getExternalId());
            return new UpdateOneModel<Document>(filter, new Document("$set", doc), new UpdateOptions().upsert(true));
        }).toList();
        return Mono.from(mongoCollection.bulkWrite(operations));
    })
```

I wonder how can I change this so I'd be able to write different POJOs  on insert and update.

The ideal for me would be to use this kind of bulkWrite if this would have work:

```java

reactiveMongoTemplate.getCollection(config.getCollection()).flatMap(mongoCollection -> {
        var operations = entities.stream().map(entity -> {
            Document docToUpdate = new Document();
            Document docToInsert = new Document();
            Entity entityToUpdate = entity.toBuilder().isArchived(null).build();
            Entity entityToInsert = Entity.builder().isArchived(false).build();
            reactiveMongoTemplate.getConverter().write(entityToInsert, docToInsert);
            reactiveMongoTemplate.getConverter().write(entityToUpdate, docToUpdate);
            var filter = new Document("externalId", entity.getExternalId());
            return new UpdateOneModel<Document>(filter, List.of(new Document("$set", docToUpdate), Document("$setOnInsert", docToInsert)), new UpdateOptions().upsert(true));
        }).toList();
        return Mono.from(mongoCollection.bulkWrite(operations));
    })
```
But I get the error of [Unrecognized pipeline stage](https://stackoverflow.com/questions/64560259/unrecognized-pipeline-stage-name-setoninsert), (another relevant link is [this one](https://jira.mongodb.org/plugins/servlet/mobile#issue/JAVA-3872)).

**Comment by christophstrobl** [comment]
@almogtavor thank you for reaching out. I do not see the connection to spring-data here. The above snippets work upon MongoDB Driver API. The only touchpoint with spring-data-mongodb is the template for obtaining the `com.mongodb.reactivestreams.client.MongoCollection` and the converter API. 
The error stems from using an invalid [aggregation stage](https://www.mongodb.com/docs/manual/tutorial/update-documents-with-aggregation-pipeline/) within the update pipeline.

**Comment by almogtavor** [comment]
@christophstrobl Ok thanks!
