### ISSUE TITLE
content of @Aggregate, @Query to load from json files

### ISSUE THREAD

**Issue by fssrepository** [spring-projects/spring-data-mongodb#4405]
Queries and pipelines can be huge in @Aggregate, @Query, and requires escaping and many other stuff to make it readable. You can't use that format directly in mongodb ui.

I have hacked things around to make it work for the time being. (spring boot 3.1.0)
(not an optimal solution, but you can grasp the idea)

https://github.com/fssrepository/springmongojsonfile.git

Instructions are in Readme.md, some classes inside spring is not that extensible, hence i had to copy out.

**Comment by mp911de** [comment]
We do not plan on adding another mechanism for externalizing queries.
