### ISSUE TITLE
Reference documentation contains JPQL queries

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-mongodb#4425]
Hi

Spring Data MongoDB reference documentation(https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/) contains block which is probably about Spring Data JPA as it contains JPQL queries:

```
@Query("select u from User u")
Stream<User> findAllByCustomQueryAndStream();

Stream<User> readAllByFirstnameNotNull();

@Query("select u from User u")
Stream<User> streamAllPaged(Pageable pageable);
```

**Comment by christophstrobl** [comment]
The above snippet is from the _Preface_ that outlines some general concepts. The store specific reference starts at [Reference Documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#reference).
FWIW, the documentation will see some changes (that will address this matter) in the the not distant future.
