### ISSUE TITLE
Database not dropped using reactive since version 4

### ISSUE THREAD

**Issue by Ahli** [spring-projects/spring-data-mongodb#4430]
After upgrading from Spring Boot 2.7.12 to the newest 3.1.1, my test database won't be dropped anymore.
This groovy snipped is supposed to clean up the database during integration tests.

### Issue
Now, **the subscription's methods are not executed and the database is not dropped**!

### Affected versions
I've tested all 4.x versions (4.0.0 to 4.1.1) and they all have this issue.
This code worked fine in 3.x versions.

``` groovy
    private void dropDatabase(String uri) {
        String dbname = uri.substring(uri.lastIndexOf('/') + 1)
        MongoClient mongoClient = MongoClients.create(uri)
        MongoDatabase database = mongoClient.getDatabase(dbname)
        boolean cleared = false
        database.drop().subscribe(new Subscriber<Void>() {
            @Override
            void onSubscribe(Subscription s) {
            }

            @Override
            void onNext(Void unused) {
            }

            @Override
            void onError(Throwable t) {
                log.error("ERROR during drop DB", t)
            }

            @Override
            void onComplete() {
                cleared = true
                mongoClient.close()
            }
        })
        Awaitility.await().atMost(10, TimeUnit.SECONDS).until(() -> cleared)
    }
```
The URI is the default one by Testcontainers 1.18.3 URI which includes the DB name "test".
The MongoDB container used is "mongo:6.0".
Awaitility is used to wait for the subscription to complete.
The test code is in groovy since the project uses Spock.

**Comment by mp911de** [comment]
The code above uses MongoDB API directly, Spring Data isn't involved. Please rather use a `CountDownlLatch` or `CompletableFuture` to synchronize. A plain `boolean` might suffer from visibility issues.
