### ISSUE TITLE
Query parameters to in operator converted to binary

### ISSUE THREAD

**Issue by ehardy** [spring-projects/spring-data-mongodb#4438]
Hello,

We are seeing an issue with a MongoDB query that uses the `in` operator. Somehow the parameters passed to the `in` operator are converted to a base64 binary format, whereas we are expecting they would be simple strings. After enabling query logging, we are seeing queries with the following filter:

```json
{ "tenant" : "TENANT_ID", "scope.accountId" : { "$in" : [{ "bytes" : { "$binary" : { "base64" : "YmQxZTlhY2ItNDcyYS00ZmU3LTk4NTctYjhlN2RhZjE4MGQ1", "subType" : "00"}}, "hash" : 0, "length" : 36, "string" : "bd1e9acb-472a-4fe7-9857-b8e7daf180d5"}]}}
```

This query does not return the expected results. We would be expecting something like the following:
```json
{ "tenant" : "TENANT_ID", "scope.accountId" : { "$in" : ["bd1e9acb-472a-4fe7-9857-b8e7daf180d5"]}}
```

This query returns the expected results.

Is there any Spring Data MongoDB parameter we are not setting that could explain the above? Any connection string parameter? Any MongoDB parameter?

Thanks

**Comment by christophstrobl** [comment]
It is hard to tell what's the issue here by looking at the provided information without context. 
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by ehardy** [comment]
That's fair, thanks for the quick reply @christophstrobl. After some further investigation, it appears the root problem is not a Spring Data MongoDB one. The above mentioned query gets executed as a result of processing a Kafka message. The collection we are passing to the `in` operator is of type `java.util.List<String>` in our code, but it appears the actual runtime values contained in the list coming from the Kafka message are rather of the `org.apache.avro.util.Utf8` type. Spring Data MongoDB treats those values as binary when generating the query, which seems correct.

**Comment by christophstrobl** [comment]
@ehardy thanks for the feedback!
