### ISSUE TITLE
3.x.x doesn't support collation attribute in @CompoundIndex

### ISSUE THREAD

**Issue by salman-khandu** [spring-projects/spring-data-mongodb#4458]
spring-data-mongodb added collation attribute support for @CompundIndex from 4.0.0. We have used 3.x.x and due to some application depending on it, we are not able to migrate it to 4.0.0. Is there any way to backport the collation feature in 3.x.x ?

**Comment by mp911de** [comment]
We do not backport major features to ensure stability for already released versions. Also, service releases are intended not to introduce new API.

**Comment by salman-khandu** [comment]
> We do not backport major features to ensure stability for already released versions. Also, service releases are intended not to introduce new API.

@mp911de is there any work around?
