### ISSUE TITLE
@DocumentReference(lazy = true) proxies are not automatically unwrapped

### ISSUE THREAD

**Issue by epernice** [spring-projects/spring-data-mongodb#4482]
When using @DocumentReference(lazy = true), proxies do not automatically unwrap. This makes lazy loaded documents difficult to work with. For example, if you return a document over a REST endpoint, serializing to JSON, the referenced document properties are all serialized as null. If you want to work with a lazy loaded document in Java code, you must first cast it as a LazyLoadedProxy and call getTarget() to manually obtain the unwrapped object.

Here is a minimal setup that reproduces the problem in a Spring Boot application:

`build.gradle`

	plugins {
		id 'java'
		id 'org.springframework.boot' version '3.1.2'
		id 'io.spring.dependency-management' version '1.1.2'
	}
	
	group = 'com.example'
	version = '0.0.1-SNAPSHOT'
	
	java {
		sourceCompatibility = '17'
	}
	
	repositories {
		mavenCentral()
	}
	
	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}
	
	tasks.named('test') {
		useJUnitPlatform()
	}

`Person.java`

    @Document("person")
    public class Person {
        ObjectId id;
        String name;
    
        @DocumentReference(lazy = true)
        Address address;
    }

`Address.java`

    @Document("address")
    public class Address {
        ObjectId id;
        String city;
    }

`PersonRepository.java`

    @Repository
    public interface PersonRepository extends MongoRepository<Person, ObjectId> {
        Person findByName(String name);
    }

`DemoApplicationTests.java`
	
	@SpringBootTest
	class DemoApplicationTests {
		@Autowired
		PersonRepository personRepository;
	
		@Test
		void lazyLoadedAddress() {
			Person person = personRepository.findByName("John Doe");
	
			// Does not work
			System.out.println("Directly accessing lazy loaded document:");
			System.out.println(person.address.city);
	
			// Works
			System.out.println("Manually unwrapping LazyLoadingProxy:");
			Address address = (Address) ((LazyLoadingProxy) person.address).getTarget();
			System.out.println(address.city);
	
			/**
			 * OUPTUT:
			 *
			 * Directly accessing lazy loaded document:
			 * null
			 * Manually unwrapping LazyLoadingProxy:
			 * San Francisco
			 */
		}
	}

**Comment by mp911de** [comment]
Not unwrapping proxies is the key point of lazy loading. By design, fields of the proxy are left with their default initialization values and you should never access fields directly. Use property accessors instead for proper resolution.

Using property access instead of field access with JSON libraries avoids the problem that JSON renders the default values.

**Comment by epernice** [comment]
Whoops, that was silly of me. My original reproduction of the problem was in Kotlin (which uses field style syntax for property accessors). I converted my code to Java too hastily to see if it was reproducible there, and forgot to switch to getters and setters. I see that the issue is Kotlin specific, so I will file a separate issue.

**Comment by epernice** [comment]
Filed it here: https://github.com/spring-projects/spring-data-mongodb/issues/4483
