### ISSUE TITLE
MongoRepository does not ignore default methods

### ISSUE THREAD

**Issue by ederfmatos** [spring-projects/spring-data-mongodb#4493]
In my domain i have a repository interface with some methods

```kotlin
interface BankRepository {
    fun existsById(id: String): Boolean
    fun getById(id: String): Bank?
    fun create(bank: Bank)
    fun update(bank: Bank)
}
```

And I created another interface to use Spring Data Mongo Repository, creating default methods to translate my repository methods to Mongo Repository methods.

```kotlin
@Repository
interface BankMongoRepository : MongoRepository<Bank, String>, BankRepository {
    override fun create(bank: Bank) {
        this.insert(bank)
    }

    override fun update(bank: Bank) {
        this.save(bank)
    }

    override fun getById(id: String): Bank? {
        return this.findByIdOrNull(id)
    }
}
```

But application does not start.

I would not like to use the @ Query annotation or have to create a class just for my methods with different names, as exemplified in some articles.
How: https://medium.com/@dangeabunea/how-to-create-a-custom-mongodb-spring-data-repository-e51c343064e1

Would it be possible to somehow identify that these methods have a default implementation so that it is not necessary to attempt creation by the spring data mongo repository?

**Comment by christophstrobl** [comment]
Looking at the byte code I do not think the current infrastructure fully understands Koltin `override` as the methods would be kept as is in the interface not becoming some sort of default method.

```java
public abstract interface BankMongoRepository implements MongoRepository, BankRepository {
     <ClassVersion=52>
     <SourceFile=BankMongoRepository.kt>
     <Sig=LMongoRepository<Lo/s/d/m/re/Bank;Lj/l/S;>;Lo/s/da/m/r/BankRepository;>
     public abstract void create(o.s.d.m.r.Bank arg0) {} //(Lo/s/d/m/r/Bank;)V

     public abstract Bank update(o.s.d.m.r.Bank arg0) {} //(L/s/d/m/r/Bank;)V

    // ...
}
```
So there's no such thing as outlined below that could be called.
```java
public Bank update(o.s.d.m.r.Bank arg0) //(Lo/s/d/m/r/Bank;)V
    L0 {
        aload 0 // reference to self
        aload 1
        invokeinterface o/s/d/m/r/BankMongoRepository.save(Ljava/lang/Object;)Ljava/lang/Object;
        checkcast o/s/d/m/r/Bank
        areturn
    }
    // ...
```

Instead there's an additional class `BankMongoRepository$DefaultImpls` with static methods targeting the `BankMongoRepository`

```java
public final class BankMongoRepository$DefaultImpls {
   public static void create(@NotNull BankMongoRepository $this, @NotNull Bank bank) {
      Intrinsics.checkNotNullParameter(bank, "bank");
      $this.insert(bank);
   }

   public static void update(@NotNull BankMongoRepository $this, @NotNull Bank bank) {
      Intrinsics.checkNotNullParameter(bank, "bank");
      $this.save(bank);
   }
}
```

**Comment by mp911de** [comment]
Kotlin's default interface methods do not use Java 8 default interface methods but rather resort to their own implementation. Annotating methods with `@JvmDefault` instructs Kotlin to compile to proper Java 8 default methods.

**Comment by mp911de** [comment]
After discussing this issue with the team, we do not want to include additional complexity by reverse engineering Kotlin's interface defaulting. Please annotate your default methods with `@JvmDefault` for proper default interface methods interoperability on the JVM.
