### ISSUE TITLE
Add Annotation for configuring ChangeStreamOptions

### ISSUE THREAD

**Issue by MCMDEV** [spring-projects/spring-data-mongodb#4538]
I'd like to add an annotation for enabling pre and post images on a collection.
From what I've found about the current situation, one has to enable this by creating the collection manually using a MongoTemplate like this:
```java
mongoTemplate.createCollection(entityClass, CollectionOptions.emitChangedRevisions());
```
I think an annotation like [TimeSeries](https://github.com/spring-projects/spring-data-mongodb/blob/69285151a0a8fc30b90cda06505bef973ea7151b/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/mapping/TimeSeries.java) would be good addition to the API here. Functionality for the ChangeStream annotation could be handled [where functionality for the TimeSeries annotation](https://github.com/spring-projects/spring-data-mongodb/blob/69285151a0a8fc30b90cda06505bef973ea7151b/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/EntityOperations.java#L1057) is handled too.

**Comment by mp911de** [comment]
Mongo is exponentially growing functionality in various areas. That design goes against the principle of keeping usage simple, and now, collection creation options see a lot of extensions.

Our collection creation feature is made to get you started quickly in a development environment. Arguably, it isn't intended for production and therefore we do not plan to extend collection creation functionality beyond what we have. There are already many other options (capped collections, document size, …) that are only accessible through `CollectionOptions` and we want to keep it like that.
