### ISSUE TITLE
ReactiveMongoTemplate - issue with version 4.x

### ISSUE THREAD

**Issue by skamtala** [spring-projects/spring-data-mongodb#4540]
Hello,

We are trying to migrate to spring-boot 3, that has spring-data-mongodb version 4.

 We are observing an issue with aggregate method on this  version of code, which internally makes a call to Flux.concatMap with a default prefetch of 0. Earlier version was using prefetch of 32 and that was faster than the new prefetch of 0.

We are asking is there a way to send non-zero prefetch to aggregate method, hoping that may improve or match the spring-boot 2 SLA.

Thanks,

Shiva

**Comment by mp911de** [comment]
`concatMap` prefetch has been updated by Project Reactor to zero with https://github.com/reactor/reactor-core/issues/2599. As we generally avoid performance-specific tweaks when we apply operators, we cannot do anything here. 

We have over 45 instances of `flatMap` and `concatMap` operators in our template. Allowing performance tweaks to each of these would be impossible to configure.
