### ISSUE TITLE
Capability to disable auditing per entity

### ISSUE THREAD

**Issue by rahimalizada** [spring-projects/spring-data-mongodb#4558]
Given the following entity hierarchy I could not find any way to disable auditing for EntityDetail document.
```
public abstract class AbstractEntity  {
    @Version
    private Integer version;
    // @Created, @CreatedBy, @LastModifiedDate, etc.
   // other base fields
}
```

```
@Document
public abstract class Entity extends AbstractEntity   {
}
```

```
@Document
public abstract class EntityDetail extends AbstractEntity   {
   // additional fields
}
```

EntityDetail  is mapped from Entity and further processed and saved. Audited fields in EntityDetail should not be modified while saving.
The only way that works with current scenario is removing audited fields from parent abstract class and adding them to all sub classes.

I think it would be nice to disable auditing per Document either completely or partially, something like:
`@DisableAuditing(all=true, version=true ...)`

**Comment by christophstrobl** [comment]
The behaviour you experience is the intended one. You may want to use [interface based auditing](https://docs.spring.io/spring-data/commons/reference/auditing.html#auditing.interfaces) to gain more control if needed.

**Comment by rahimalizada** [comment]
Auditable interface does not update version information

**Comment by christophstrobl** [comment]
It does not. Versioning works independently from auditing.
