### ISSUE TITLE
The `transient` modifier is not supported

### ISSUE THREAD

**Issue by human-user** [spring-projects/spring-data-mongodb#4559]
The field is still persisted to MongoDB while using `transient` modifier.  If use `@Transient` annotation, it work as expected.
In my opinion, `transient` modifier means the field should not be serialized and persistence rely on object serialization, therefor it should not be persisted .

case:
```
@Document("admin")
public class Admin implements Serializable {
    @Serial
    private static final long serialVersionUID = -7595740712701326755L;
    @Id
    private String id;
    private String code;
    private transient String name;

    public static Admin of(String code, String name) {
        Admin admin = new Admin();
        admin.code = code;
        admin.name = name;
        return admin;
    }
}
```
```
Admin admin = Admin.of("testCode", "testName");
adminRepository.save(admin);
```

**Comment by christophstrobl** [comment]
This is the expected behaviour. `transient` is a jdk serialization keyword which does not necessarily mean it should not be persisted in the database. That's why there's an explicit `@Transient` annotation.

**Comment by human-user** [comment]
This behaves differently from Spring Data JPA, it confuses me a little.

**Comment by christophstrobl** [comment]
Because of the JPA spec:
> All non-transient instance variables that are not annotated with the Transient annotation are persistent
