### ISSUE TITLE
spring-data-mongodb > 4.2.0-M3. Multicluster config. Errors on startup

### ISSUE THREAD

**Issue by biagioT** [spring-projects/spring-data-mongodb#4566]
I have a Spring Boot 3.2.0-SNAPSHOT based application that connects to MongoDB. My MongoDB is a ReplicaSet deployed on two Kubernetes clusters:
- three nodes on cluster A (and one arbiter)
- three nodes on cluster B The nodes (therefore pods) are exposed via NodePort, so all the synchronization of the ReplicaSet takes place via NodePort.

In the Spring Boot application the value of spring.data.mongodb.uri is as follows:
```
mongodb://my_user:my_pwd@
<MASTER-NODE-CLUSTER-A-IP-1>:30100,
<MASTER-NODE-CLUSTER-A-IP-2>:30101,
<MASTER-NODE-CLUSTER-A-IP-3>:30102,
<INFRA-NODE-CLUSTER-A-IP-1>:30100,
<INFRA-NODE-CLUSTER-A-IP-2>:30101,
<INFRA-NODE-CLUSTER-A-IP-3>:30102,
<MASTER-NODE-CLUSTER-B-IP-1>:30100,
<MASTER-NODE-CLUSTER-B-IP-2>:30101,
<MASTER-NODE-CLUSTER-B-IP-3>:30102,
<INFRA-NODE-CLUSTER-B-IP-1>:30100,
<INFRA-NODE-CLUSTER-B-IP-2>:30101,
<INFRA-NODE-CLUSTER-B-IP-3>:30102
/my_db?replicaSet=rsTest&authSource=my_db
```
instead of connecting to the IPs of the nodes assigned to the ReplicaSet, I use the NodePorts to use the IPs of my Master and Infra nodes (more stable) of my Kubernetes clusters.

I have the following errors:
`<MY-NODE-IP..> is no longer a member of the replica set. Removing from client view of cluster` with stacktrace (I have the same message in the working version but without stacktrace, as INFO).
and then:
`o.s.b.a.health.HealthEndpointSupport : Health contributor org.springframework.boot.actuate.data.mongo.MongoHealthIndicator (mongo) took 30103ms to respond`

`Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=WORKER-NODE-CLUSTER-A-IP-3:30102, type=REPLICA_SET_SECONDARY, roundTripTime=20.0 ms, state=CONNECTED}, {address=ARBITER-SVC:27017, state=CONNECTED}, {address=WORKER-NODE-CLUSTER-A-IP-2:30101, type=REPLICA_SET_SECONDARY, roundTripTime=20.7 ms, state=CONNECTED}, {address=WORKER-NODE-CLUSTER-A-IP-1:30100, type=UNKNOWN, state=CONNECTING}, {address=WORKER-NODE-CLUSTER-B-IP-3:30102, type=REPLICA_SET_SECONDARY, roundTripTime=715.3 ms, state=CONNECTED}, {address=WORKER-NODE-CLUSTER-B-IP-2:30101, type=REPLICA_SET_SECONDARY, roundTripTime=131.8 ms, state=CONNECTED}, {address=WORKER-NODE-CLUSTER-B-IP-1:30100, type=REPLICA_SET_SECONDARY, roundTripTime=793.6 ms, state=CONNECTED}]`

With Spring Boot 3.2.0-M3 I don't have these errors: the application starts normally.

Working library versions (Spring Boot 3.2.0-M3)
- mongodb-driver-core:4.10.2
- mongodb-driver-sync:4.10.2
- spring-boot-starter-data-mongodb:3.2.0-M3
- spring-data-mongodb:4.2.0-M3

error-causing libraries (Spring Boot >= 3.2.0-RC2, eg Spring Boot 3.2.0-SNAPSHOT)
- mongodb-driver-core:4.11.0
- mongodb-driver-sync:4.11.0
- spring-boot-starter-data-mongodb:3.2.0-SNAPSHOT
- spring-data-mongodb:4.2.0-SNAPSHOT

**Comment by mp911de** [comment]
Thanks for reaching out. We cannot do anything about connection timeouts because of infrastructure misconfiguration.
