### ISSUE TITLE
Optimistic @Version is increased when update fails due MongoSocketOpenException

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-data-mongodb#4576]
Actual:
On save attempt `@Version` attribute is increased. When save fails due MongoSocketOpenException, `@Version` attribute  is not restored
As result, when socket connection is back, save fails due OptimisticLockingFailureException

Expected: 
when save fails,  `@Version` attribute should be restored. When socket connection is back, save should succeeded.

spring-data-mongodb 4.1.5

SO question: https://stackoverflow.com/questions/77498546/optimistic-version-is-increased-when-update-fails-due-mongosocketopenexception

**Comment by christophstrobl** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by michaldo** [comment]
Voila: https://github.com/michaldo/spring-data-mongo-4576
