### ISSUE TITLE
 [Spring Data MongoDB 4.2.0] MongoTemplate using incorrect nested fields order

### ISSUE THREAD

**Issue by infoShare** [spring-projects/spring-data-mongodb#4585]
When using MongoTemplate.find(...) order of the nested fields is not preserved. This might be problematic if full objects search is used (for example for indexed complex fields).

Below you can find JUnit with this issue highlighted.

Failing as query for Mongodb is:
        { "nested" : { "**checkName**" : "B", "**checkVersion**" : "1", "**systemName**" : "A" } }
instead of
        { "nested" : { "**systemName**" : "A", "**checkName**" : "B", "**checkVersion**" : "1" } }
on MongoTemplate.doFind() on line: Document mappedQuery = queryContext.getMappedQuery(entity);

https://github.com/infoShare/code-examples/blob/main/spring-data-mongodb-order/src/test/java/infoshare/springdatamongodborder/SpringDataMongodbOrderTests.java

It is working properly on spring-data-mongodb:4.1.5

**Comment by christophstrobl** [comment]
@infoShare thanks for reporting! This looks similar to #4577 having the root cause in #4555. Well fix this with the next service release.
