### ISSUE TITLE
Docs for IndexOperations.resetIndexCache() should be removed

### ISSUE THREAD

**Issue by aalsup** [spring-projects/spring-data-mongodb#4587]
In the docs, section "Index and Collection Management", the `IndexOperations` interface still shows a reference to the `resetIndexCache()` method. Elsewhere in the docs, it does state that this method is no longer supported. However, it is still shown in the docs interface definition - even though the method is not available in the 4.2.0 jar.

**Comment by christophstrobl** [comment]
@aalsup thanks for the heads up. we'll fix that.
