### ISSUE TITLE
Question: Why not add a callback to retrieve such methods?

### ISSUE THREAD

**Issue by haoqi6677** [spring-projects/spring-data-mongodb#4593]
Hello, may I ask, the save method has callback, which is satisfactory and can meet the requirement, but the retrieval method does not have callback, which cannot meet the requirement of adding parameters to the document before query

**Comment by christophstrobl** [comment]
I'm not sure if I understand the issue correctly. Maybe you can give me a bit more context. From what I read this sounds roughly like #2067.

**Comment by haoqi6677** [comment]
> I'm not sure if I understand the issue correctly. Maybe you can give me a bit more context. From what I read this sounds roughly like #2067.

yes....It seems that the issue of multi-tenancy is still bothering me, a user of spring-data-mongo. I have searched a lot, and most of them are based on switching data sources to achieve multi-tenancy, but I think that is not elegant enough and requires too many resources. There are too many, it is unrealistic. I want to make aspects on the `org.springframework.data.mongodb.core.MongoTemplate.doFind` method, but it turns out that it is `default` modified. I want to make `org.springframework.data.mongodb.repository. Query.AbstractMongoQuery.doExecute` This `protected` modified method was rewritten to achieve the purpose of modifying Query. I found that I had to modify the factory, which was too troublesome and still couldn't be done, so I asked here. I also want to ask if it is possible. Are there any examples you can refer to? Reading the official documentation did not achieve the results I wanted

**Comment by haoqi6677** [comment]
Temporarily use a way to achieve the goal, thank you
