### ISSUE TITLE
Add option to disable automatic mapping of java "id" field to Mongo "_id" field?

### ISSUE THREAD

**Issue by takanuva15** [spring-projects/spring-data-mongodb#4596]
We're migrating our microservices to spring-data-mongo and that includes a large number of model classes (200+) that we need to adjust to work with the Spring Mongo mapping layer. Most of the classes are embedded POJOs that do not have their own Mongo collection.

The [Spring documentation](https://docs.spring.io/spring-data/mongodb/docs/current-SNAPSHOT/reference/html/#mongo-template.id-handling) mentions that "A property or field without an annotation but named id maps to the _id field". This is causing an issue for us because we have a large number of embedded classes that have a field named "id", but we do not want it to become the "_id" field in Mongo because it is not a real top-level id. Also, we already have millions of documents sitting in our database where that "id" field is saved as "id", so changing all of those to "_id" just to satisfy Spring-data is impractical.

Thus, I am wondering whether there is a convenient flag/option to disable Spring's automatic conversion of the "id" field to "_id" in Mongo so that Spring only considers fields annotated with `@Id` as true Mongo ids? If not, can this be added as an option to the Spring data mongo configuration setup?

Also, in the meantime, is there some kind of modification (or hack) I could apply to MongoMappingConverter to make this behavior possible where doesn't give special treatment to "id" fields not explicitly marked with the `@Id` annotation?

- One workaround I've found after some Googling is to manually add `@Field("id")` to those embedded "id" fields in our model so that Spring treats them like a normal field, but this is difficult to apply across our entire set of 200+ models without considerable effort.

Note: I read this [SO question](https://stackoverflow.com/q/14846894/6854489) from 10 years ago asking a similar question which was answered by Oliver from the Spring team, but it looks like there was no solution presented.

**Comment by christophstrobl** [comment]
Thank you for taking the time to file this issue. I think it describes the same problem as #3351. Therefore I'll close it as duplicate for now. You may want to leave a comment on the other issue or reopen if the problem at hand differs.
