### ISSUE TITLE
BsonUtils.hasValue(Bson bson, FieldName fieldName) does not deliver expected result

### ISSUE THREAD

**Issue by frederic-huebner** [spring-projects/spring-data-mongodb#4598]
We are using a `@ReadingConverter` to map `null` values in the MongoDB to a specific enum value. After the update from 4.1.7 to 4.2.0, the mapping does not happen anymore, instead we're getting the `null` value, like it's stored in the database. I could pinpoint the change in behavior to [BsonUtils.hasValue(...)](https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/util/BsonUtils.java#L592-L614). That method is [used in the DocumentAccessor](https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/DocumentAccessor.java#L147), which is [used by the MappingMongoConverter](https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L622) while reading properties.

Before the update, the method returned `false`, as I would expect it to do. Afterwards it is returning `true` for `null` values. For illustration, I would the following test in `BsonUtilsTest.java `expect to pass:

```java
@Test
void shouldReturnFalseForNull() {
    var source = new Document().append("a", null);
    assertThat(BsonUtils.hasValue(source, FieldName.path("a"))).isFalse();
}
```

**Comment by mp911de** [comment]
With a recent change, we consider entries having a `null` value as entries with a value. In previous versions, we considered null values as absent ones therefore you see the change.
