### ISSUE TITLE
Nested field with @TypeAlias works when first operation is write and fails when read

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-data-mongodb#4599]
My model is document with polymorphic field:
```
@Document("test-collection")
class MyDocument {

    @Id int id;

    MyAbstract nested;

    MyDocument(MyAbstract nested) {
        this.nested = nested;
    }
}

abstract class MyAbstract { }

@TypeAlias("MY-CO")
class MyConcrete extends MyAbstract { }
```

My database contains one document:
```
[
  {
    "_id": 0,
    "_class": "org.example.MyDocument",
    "nested": {
      "_class": "MY-CO"
    }
  }
]
```
The following code works:
```
  @PostConstruct
  void test() {
      mongoTemplate.dropCollection(MyDocument.class);
      mongoTemplate.save(new MyDocument(new MyConcrete()));
      mongoTemplate.findById(0, MyDocument.class);
  }
```
but this one fails:
```
  @PostConstruct
  void test() {
      mongoTemplate.findById(0, MyDocument.class);
  }
```
with
> Failed to instantiate [org.example.MyAbstract]: Class is abstract

I checked why and I found that on write control goes to
`AbstractMappingContext#getPersistentEntity` and puts `MyConcrete` to `AbstractMappingContext#persistentEntities`

But when first operation is read, `AbstractMappingContext#persistentEntities` does not contain `MyConcrete`, application attempts to instantiate `MyAbstract` and fails

I would like application work regardless first operation is read or write. Any hint?

**Comment by michaldo** [comment]
Hint found here: https://stackoverflow.com/a/74431949/2365727

**Comment by christophstrobl** [comment]
Thank you for getting in touch, sorry it took some time to get back to you. It feels like you figured out how to provide an initial entity set already 👍 . Therefore I'm closing this one. Please feel free to reopen in case still do not work for you.

**Comment by michaldo** [comment]
I would like you reconsider fixing the bug. Although workaroud is simple, the bug still exists and
1. seems be easy to fix
2. is dangerous because is unpredictable. It is possible that bug does not occur for weeks and suddenly appears, when client decide to start conversation from read. Or may never happen on test environment but occur on prod environment.

**Comment by christophstrobl** [comment]
The behaviour is explained in the [Customizing Type Mapping](https://docs.spring.io/spring-data/mongodb/reference/mongodb/converters-type-mapping.html#customizing-type-mapping) section of the reference documentation and boot offers [additional ways](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql.mongodb.repositories) to (auto)configure type discovery.

**Comment by michaldo** [comment]
From framework developer perspective it looks consistent:
1. Framework must know `@Document` and `@TypeAlias` classes to map bson trees to Java classes (_The required entity metadata (1) has to be provided via the configurations initial entity set_)
2. There is feature, invented as handy, that if class is being mapped to bson tree and the class in unknown, then the class is added to known classes ( _The required entity metadata is determined (2) on first save_)
3. All above is documented

From application developer perspective, framework works randomly, depending on first operation: read or write

In my opinion:
1. Currently framework scans by default `@Document` classes. It should scan also `@TypeAlias` classes. It would be consistent to Spring Boot idea - works out of the box with zero configuration
2. By default framework should not add a `@Document` class dynamically to promote deterministic behavior - always works or always fails
