### ISSUE TITLE
@Version Limits Long

### ISSUE THREAD

**Issue by Lucasark** [spring-projects/spring-data-mongodb#4608]
I created this thread on [StackOverflow](https://stackoverflow.com/questions/77557737/version-in-mongodb-limit), but did not recived much attention.

So I am writing just to clear my question:

If i use @Version with Long (On Mongodb Document it will be used with Int64)

When reach limite size of Int64, which is 9223372036854775808 it will going to -9223372036854775808 (negative size expression) , and continue with -9223372036854775807, -9223372036854775806...n.

So, my question is simple, existe any other way to use @Version that not exist "limit" like date, id, etc?

**Comment by mp911de** [comment]
We do not support other than numeric types for `@Version`.

Assuming you're updating a single document every millisecond (constantly throughout the year), then you would have to do this for the next 292 million years (`9223372036854775808/(1000*60*60*24*365)`).

Other than that, adding to Int64 Max size flips the number into negative space.

**Comment by mp911de** [comment]
It is the natural flow. Probably this is only going to be a problem in 584 million years, when hitting zero again.
