### ISSUE TITLE
Make `MongoHandlerContext` public to leverage contextual information to customize `Observation`s

### ISSUE THREAD

**Issue by kevinat** [spring-projects/spring-data-mongodb#4622]
Observation tracing remote service name is hardcoded as "mongo". For microservices, we may need remote service name in pattern `mongo-dbname`.

MongoObservationCommandListener.java

line 108:  
---     ~observationContext.setRemoteServiceName("mongo");~
+++    observationContext.setRemoteServiceName("mongo-%s".formatted(databaseName));

**Comment by mp911de** [comment]
We could introduce template method hooks to customize the context and the observation so you can customize both, the context and the `Observation`. Paging @marcingrzejszczak and @jonatan-ivanov for guidance.

**Comment by marcingrzejszczak** [comment]
One can already do that via the [`ObservationFilter`](https://docs.micrometer.io/micrometer/reference/observation/handler.html#_observation_predicates_and_filters) mechanism

**Comment by mp911de** [comment]
Thanks a lot. I'm going to make our `MongoHandlerContext` public to provide access to underlying details.
