### ISSUE TITLE
`GeoJsonPolygon` does not match GeoJSON spec

### ISSUE THREAD

**Issue by samuelmckean** [spring-projects/spring-data-mongodb#4627]
I noticed that the `GeoJsonPolygon` class does match two requirements of the [GeoJSON Polygon spec](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6)

First, I can create a `GeoJsonPolygon` object with less than four points, which should not be possible. I would expect it to throw an error in this situation but it does not. It seems to be only tied to using the 2nd constructor `publicGeoJsonPolygon(List<Point> points) {}` as the first constructor enforces that there must be at least 4 `Point` args given
```
List<Point> coordinates = new ArrayList<>();
coordinates.add(new Point(100.0, 0.0));
coordinates.add(new Point(101.0, 0.0));

GeoJsonPolygon geoJsonPolygon = new GeoJsonPolygon(coordinates);
System.out.println(geoJsonPolygon.getCoordinates().get(0).getCoordinates());
```

Second, the first and last positions are equivalent and they should contain identical values. I would expect it to either throw an error in this situation as well, but it does not. This issue exists for both constructors as shown below
```
// using first constructor
GeoJsonPolygon geoJsonPolygon1 = new GeoJsonPolygon(new Point(100.0, 0.0), new Point(101.0, 0.0), new Point(101.0, 1.0), new Point(100.0, 1.0));

// using second constructor
List<Point> coordinates = new ArrayList<>();
coordinates.add(new Point(100.0, 0.0));
coordinates.add(new Point(101.0, 0.0));
coordinates.add(new Point(101.0, 1.0));
coordinates.add(new Point(100.0, 1.0));

GeoJsonPolygon geoJsonPolygon = new GeoJsonPolygon(coordinates);
System.out.println(geoJsonPolygon.getCoordinates().get(0).getCoordinates());
```

**Comment by christophstrobl** [comment]
The geojson structures in data-mongoldb are there to allow using them for GeoJSON data supported by the MongoDB database. They are no reference implementation of the geojson spec.
