### ISSUE TITLE
Saved object returned by ReactiveMongoTemplate.save(T) is different from the actual saved object in MongoDB for Instant field

### ISSUE THREAD

**Issue by Doraemoe** [spring-projects/spring-data-mongodb#4628]
Hi,

In the [document](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/ReactiveMongoOperations.html#save(T)) for `ReactiveMongoOperations.save(T)` method, it says the returned object of this method is the saved object. However, if the saved object contains `Instant` field, the value of the saved object this method returns will be different from the actual saved object in MongoDB.

e.g. let's consider a simple db model

```
@Document(collection = "instant")
class DataForDB(
    @Id var id: ObjectId? = null,
    var name: String? = null,
    val time: Instant? = null,
)
```

Then a simple test

```
	companion object {
		val MONGO_CONTAINER = MongoDBContainer(DockerImageName.parse("mongo:latest"))

		@JvmStatic
		@DynamicPropertySource
		fun setProperties(registry: DynamicPropertyRegistry) {
			MONGO_CONTAINER.start()
			registry.add("spring.data.mongodb.uri") {
				"${MONGO_CONTAINER.connectionString}/instant"
			}
		}
	}

	@Autowired
	lateinit var mongoTemplate: ReactiveMongoTemplate

	@Autowired
	lateinit var objectMapper: ObjectMapper


	@Test
	fun shouldEqual(): Unit = runBlocking {
		mongoTemplate.createCollection(DataForDB::class.java).awaitSingle()

		val dataToSave = DataForDB(name = "test", time = Instant.now())
		val saved = mongoTemplate.save(dataToSave).awaitSingleOrNull()

		val query = Query()
			.addCriteria(DataForDB::name.isEqualTo("test"))

		val actual = mongoTemplate.findOne(query, DataForDB::class.java).awaitSingleOrNull()

                // This assert will fail as actual.time will only contains 3 digit precision while saved.time will have 6 digit precision
		assertThat(objectMapper.writeValueAsString(actual?.time)).isEqualTo(objectMapper.writeValueAsString(saved?.time)) 
	}
```

This is probably because MongoDB provides only millisecond-precision according to [this comment](https://github.com/spring-projects/spring-data-mongodb/issues/2883#issuecomment-752666111)
If that's the case, shouldn't saved object also returns millisecond-precision? 

In addition, when check saved object with other application like mongosh/MongoDB Compass, it shows the saved object time only contains 3 digit precision too.

Am I missing something here? Thanks.

**Comment by Doraemoe** [comment]
Thanks, I will try use workaround instead.
However, shouldn't the [document](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/ReactiveMongoOperations.html#save(T)) also make it clear since the return is not exactly `the saved object`?

**Comment by mp911de** [comment]
There are many ways to affect either the written `Document` (converters, entity callbacks, lifecycle events) or the entity without reflecting those changes in the other one.
