### ISSUE TITLE
Possible change in object mapping behaviour regarding 'null' values

### ISSUE THREAD

**Issue by Pascal-Oertli** [spring-projects/spring-data-mongodb#4636]
## Describe the bug

Since SpringBoot version >=3.2.0 (and SpringDataMongoDB >=v4.2.0), fields that are explitly set to 'null' in the DB overwrite potentially already initialized fields during POJO instantiation.

In previous versions (e.g.: SB 3.1.8), if a instance field is initialized within the code, it is only overwritten by non-null values from the DB. 'null' values were ignored.

#### Demo Project

Here is a link to a minimal demo project that highlights the change in mapping behaviour: [Demo Project](https://gitlab.com/elderbyte/public/examples/spring-mongo-null-field-initialization-issue)

#### Demo Code

Declaring a simple class containing two fields: An Id field and a field with a default value (in this case an empty Set):

```
@Document
public class SomeObject {

    @Id
    private String id;

    private Collection<String> someCollection = new HashSet<>(); // Field with default value


    protected SomeObject() {}

    public SomeObject(String id) {
        this.id = id;
    }


    public Collection<String> getSomeCollection() {
        return someCollection;
    }

}
```

Declaring the repository:

```
public interface Repo extends MongoRepository<SomeObject, String> {

}
```

Saving the object to the DB and explicitely updating the field in question to 'null'. The object's field has now the value 'null' after retrieval, even thought it has a default value set in the code:

```
@Test
public void null_field_in_DB_to_POJO() {

    var id = "id_of_test_object";

    // Save object to DB
    repo.save(new SomeObject(id));

    // Explicitly set field to null
    mongoTemplate.updateFirst(
            new Query(Criteria.where("_id").is(id)),
            new Update().set("someCollection", null),
            SomeObject.class
    );

    // Retrieve object from DB
    var object = repo.findById(id).orElseThrow();

    // Expected behaviour ('null' from DB does not override object's field initialization)
    assertNotNull(object.getSomeCollection()); // <--- Is actually 'null'
}
```

## Expected Behaviour

'null' values from the DB do not overwrite the default values of instance fields.

## Actual Behaviour

The instance field 'someCollection' has value 'null' instead of empty Set.

## Versions Used
- SpringBoot 3.2.0
- SpringBootStarterDataMongoDB 3.2.0 -> SpringDataMongoDB 4.2.0
- Java 17
- Gradle 8.5

## Comments

I am not entirely sure if this is a bug or actually expected behaviour. Please enlighten me if this change was intentional.

**Comment by christophstrobl** [comment]
Sorry for the inconvenience but this is actually the expected behaviour for fields that are present in the raw document. In the above you'd have to `$unset` fields.

**Comment by Pascal-Oertli** [comment]
Thank you for your quick response! I can see that this intuitively makes sense (actual data in DB has precedence over default values). But I was still wondering about the change in behaviour after SB >=v3.2.0 (SpringDataMongoDB >=4.2.0).
It seems that in older versions, 'null' values did in fact not overwrite default values.

**Comment by christophstrobl** [comment]
Right, that one should have made it into the release notes on the wiki page. The [Mapping](https://docs.spring.io/spring-data/mongodb/reference/mongodb/mapping/mapping.html#mapping-conversion) section in the documentation contains an extra note that explains the current behaviour.

**Comment by n0daft** [comment]
This change exposes us to all sorts of possible nullPointers. Is there a way we can change this behaviour for collections (see highlighted part in screenshot). A custom converter would not be the right tool, since we actually don't want to convert at all?

<img width="1067" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/2951619/78e76cc6-6efc-43f8-88bb-2cbd447a1205">

**Comment by christophstrobl** [comment]
@n0daft you could use [Lifecycle Events](https://docs.spring.io/spring-data/mongodb/reference/mongodb/lifecycle-events.html) to post process types after conversion.
