### ISSUE TITLE
there is an evident BUG in Query.java line 245 ( getReadPreference method)

### ISSUE THREAD

**Issue by baggior** [spring-projects/spring-data-mongodb#4639]
https://github.com/spring-projects/spring-data-mongodb/blob/1ca64d90526bf2d4855f52d6ae4b61caa8617d83/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/query/Query.java#L245

in method
`public ReadPreference getReadPreference()`

`return getMeta().getFlags().contains(CursorOption.SECONDARY_READS) ? ReadPreference.primaryPreferred() : null;`

I think should be

`return getMeta().getFlags().contains(CursorOption.SECONDARY_READS) ? ReadPreference.secondaryPreferred() : null;`

**Comment by christophstrobl** [comment]
thank you for getting in touch - `secondaryPreferred()` forces reads to a secondary where as `primaryPreferred()` allows reads from secondary which is in line with what `CursorOption.SECONDARY_READS` says.
