### ISSUE TITLE
Inner _id NULL in projects from @Aggregation 

### ISSUE THREAD

**Issue by Lucasark** [spring-projects/spring-data-mongodb#4645]
If create a projection that has _id in inner children, it is seted to NULL in childrens objects, example:

Lets take this cenario:
<img width="1148" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/31750882/569cc216-a96d-4830-91c6-6e51ef2a59ec">

 There is "id" in father an "id" on childrens, but on @Aggregation id children is NULL always, like:

<img width="1051" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/31750882/55fb8112-4074-4a46-9973-b0661bc96171">

However, if i just change the "id" alias it work, like:

<img width="1042" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/31750882/57997c77-a704-4ef8-bf81-e1fcb38c946f">

In this example, i changed "id" to "id2", but i want keep both naming "id".

PS.: I know i can make mapper, converver, etc... but I want keep it simple, and i think mongodb can handle this.

Aggregations created to reproduce this bug:

```

//Not Working

    @Aggregation(pipeline = {
            "{$unwind: '$estados'}",
            "{$lookup: {from: 'estado', localField: 'estados.$id', foreignField: '_id', as: 'estadoFF'}}",
            "{$addFields: {estadoMapped: {$map: {input: '$estadoFF' ,as: 'estado',in: {id: {$toString: '$$estado._id'}, h: 'child'}}}}}",
            "{$project: {_id: 0, id: {$toString: '$_id'}, h: 'father' , estado: '$estadoMapped'}}"
    })
    List<MongoBugResponse> getEntity(String id);

//Working, with SAME implementation just changed "id" named to "id2".

    @Aggregation(pipeline = {
            "{$unwind: '$estados'}",
            "{$lookup: {from: 'estado', localField: 'estados.$id', foreignField: '_id', as: 'estadoFF'}}",
            "{$addFields: {estadoMapped: {$map: {input: '$estadoFF' ,as: 'estado',in: {id2: {$toString: '$$estado._id'}, h: 'child'}}}}}",
            "{$project: {_id: 0, id: {$toString: '$_id'}, h: 'father' , estado: '$estadoMapped'}}"
    })
    List<MongoBugWorkaroundResponse> getEntityDiffId(String id);
```
Link to demo: [Demo](https://github.com/Lucasark/demo-spring-boot/tree/MONGOBUG)

**Comment by christophstrobl** [comment]
Thank you for getting in touch - did you have a look at [how `id` fields are mapped](https://docs.spring.io/spring-data/mongodb/reference/mongodb/mapping/mapping.html#mapping.conventions.id-field)? This may be solved by adding an `@Field` annotation to the domain model. If not, please take the time to trim the demo to only include the relevant parts needed to reproduce the issue, preferred a failing test we can run.

**Comment by Lucasark** [comment]
Add

> Thank you for getting in touch - did you have a look at [how `id` fields are mapped](https://docs.spring.io/spring-data/mongodb/reference/mongodb/mapping/mapping.html#mapping.conventions.id-field)? This may be solved by adding an `@Field` annotation to the domain model. If not, please take the time to trim the demo to only include the relevant parts needed to reproduce the issue, preferred a failing test we can run.

Adding @Field with id worked, liked:

```
  @Field("id")
  private String id;
```

But I still thinking is a little redudance, with I use only @Field (without value) did not work, but in documentation said that it should work, so:

Def | Result Map | Wokerd?
-- | -- | --
String id | _id | No, that I used
@Field String id | _id | No
@Field("x") String id | x | Yes, BUT using "id" for value
@Id String x | _id | No, but I do not think is the right way
@Field("x") @Id String x | _id | ?

I trim the project with Integration Test to run:
[Demo](https://github.com/Lucasark/demo-spring-boot/tree/MONGOBUG)

**Comment by christophstrobl** [comment]
The aggregation pipeline is adding a field named `id` to the nested document, which is not in line with the documentation section for _id fields_ and thus the mapping will not pick the value up. 
I'm closing this one as it can be solved by either using the `@Field` annotation or by correcting the `pipeline` to comply with the actual mapping rules outlined in the documentation by changing `... in: { id: {$toS...` to `... in: { _id: {$toS...`.
