### ISSUE TITLE
`Criteria.regex` converted to `String` for `@Field(targetType = FieldType.STRING)` property

### ISSUE THREAD

**Issue by sunxiang0918** [spring-projects/spring-data-mongodb#4649]
When I use the Criteria class to construct a query with a regex(using mongoTemplate.find() ), the query does not return a result using version 4.2.0+, whereas the same code, using version 4.1.0, returns the result correctly.

Example: `criteria.regex("^abc"). `

I followed the source code to try to find the cause of the problem. Here's what I found:

When querying in mongoTemplate's `doFind` method, the query conditions passed in are transformed as follows: `Document mappedQuery = queryContext.getMappedQuery(entity);`. In versions of spring-data-mongo 4.2+ (spring-core 6.1.0+), the transformed mappedQuery will convert `java.util.regex.Pattern` to `java.lang.String`, which prevents it from entering the mongo-driver's `PatternCodec`. Consequently, the resulting mongo query condition changes from `{ "$regex": "^abc" }` to `"^abc"`, meaning it no longer uses "regex" for regex queries but instead becomes an "equal" comparison query.

The root cause of this issue lies in the fact that in spring-core 6.1.0+ versions, a PR was merged [(spring-core PR-24311)](https://github.com/spring-projects/spring-framework/pull/24311) that added a pattern-to-string converter to `DefaultConversionService` in spring-core, namely the `ObjectToStringConverter`. In the `QueryMapper#applyFieldTargetTypeHintToValue` method of spring-data-mongo, the conversionService's `canConvert(...)` method is called to determine if a Pattern can be converted to a String. In previous versions, without this converter, `canConvert(...) `would return `false`, indicating that conversion was not possible and thus returning `java.util.regex.Pattern` as is.

However, in spring-core 6.1.0+ versions, with the presence of this converter, `canConvert(...)` now returns true, indicating conversion is possible. As a result, `ObjectToStringConverter` is invoked to convert `java.util.regex.Pattern` to String, leading to the aforementioned bug.

spring-core:6.0.11 :
<img width="560" alt="spring_core_6 0" src="https://github.com/spring-projects/spring-data-mongodb/assets/839054/5fbcc9c4-1bc6-4d7a-87c2-01ba1574d122">

spring-core:6.1.3:
<img width="689" alt="spring_core_6 1" src="https://github.com/spring-projects/spring-data-mongodb/assets/839054/bb5c1ed0-32d4-4d6c-b3af-e6863a7fa1d8">

spring-core:6.1.0+:
<img width="1152" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/839054/0ae2ecbb-c621-4892-a40a-72229cc3376c">

<img width="1254" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/839054/52c07b1e-f33c-4c17-96f8-8c05f1b85420">

**Comment by spekdrum** [comment]
Hi, this problem is still happening. In `QueryMapper#getMappedValue` method, `applyFiledTargetTypeHitToValue()` returns the Pattern object correctly after the fix, but later ends calling `convertId(value, getIdTypeForField(documentField))` which ends calling MongoConverter.getConversionService().canConvert() and this is returning true, as described by the op. So Pattern is converted to String anyway.

![image](https://github.com/spring-projects/spring-data-mongodb/assets/3244109/c4b8ff5d-09ca-4efb-9a51-0f3005e6f396)

![image](https://github.com/spring-projects/spring-data-mongodb/assets/3244109/89c6cf8a-3aad-493a-b42b-2b7b11c474da)

**Comment by sunxiang0918** [comment]
No, I'm still waiting for the [4.2.4] version Release.
In my program, I temporarily customized the MongoConverter and deleted the pattern-to-string converter that I don't currently use.
I will upgrade after this problem is officially fixed.

<img width="1427" alt="image" src="https://github.com/spring-projects/spring-data-mongodb/assets/839054/5ab93e7b-e71d-4c74-bf10-9113cd624b3a">
