### ISSUE TITLE
Error Query JPA in INNER...INNER Id

### ISSUE THREAD

**Issue by Lucasark** [spring-projects/spring-data-mongodb#4651]
When a Document has "grandChild" ref, the query is build wrong, like:

Survey --REF--> Child --REF-->  GrandChild, query build by JPA:

```
{ "_id" : { "$oid" : "65e406c4888148611803bc2b"}, "child" : { "$java" : { "$ref" : "child", "$id" : "65e406c4888148611803bc29" } } }
```

Instead of:

```
{ "_id" : { "$oid" : "65e406c4888148611803bc2b"}, "child" : { "$java" : { "$ref" : "grandchild", "$id" : "65e406c4888148611803bc29" } } }
```

[Reproducion](https://github.com/Lucasark/demo-spring-boot/tree/MONGOBUG-2)

[Direct class test](https://github.com/Lucasark/demo-spring-boot/blob/MONGOBUG-2/src/test/java/com/example/demo/DemoApplicationTest.java)

**Comment by christophstrobl** [comment]
Thank you for getting in touch and providing the reproducer. As outlined in the [reference documentation](https://docs.spring.io/spring-data/mongodb/reference/mongodb/repositories/query-methods.html) deriving queries that target `dbref` properties is not supported.
