### ISSUE TITLE
Annotation @Version for optimistic locking : lack of standardization

### ISSUE THREAD

**Issue by Jeancricri** [spring-projects/spring-data-mongodb#4652]
Using Hibernate, the code below enables the optimistic locking in a class annotated @Entity.
@Version
private **Long** version;

However, it won't work using a MongoDB repository ( object MongoRepository ) in a class annotated @Document.
The way to make it work is to use the code below.
@Version
private **long** version;

So, you see the difference : a **Long** (java object) for Hibernate, and a **long** (java primitive) for a MongoDB Repository.

We might face the same lack of standardization with the primitive int and the java object Integer for the annotation @Version.

**Comment by schauder** [comment]
Moved the issue and assigne @christophstrobl since this seems to be about Spring Data MongoDB and its treatment of version attributes.

**Comment by christophstrobl** [comment]
Glad it works for you now - thanks for letting use know!
