### ISSUE TITLE
Centering the documentation

### ISSUE THREAD

**Issue by venkatasreekanth** [spring-projects/spring-data-mongodb#4659]
Hello,

Would it be possible to offer the option of offering to align the page, like center left or right etc. It would reduce the neck pain from having to read your documentatio.

Thanks,
Venkata

**Comment by ilayaperumalg** [comment]
Hi, Thanks for reporting. We would like to understand your suggestion better especially, more detail on the alignment which could make it better for people to read. While this specific requirement could change from one person to other, it would be better to know more around the alignment you are suggesting. 
Given, the documentation of these projects are based on Antora, please follow up your suggestion [here](https://github.com/spring-io/antora-ui-spring) .
