### ISSUE TITLE
AggregationResults include documents outside the MatchOperation when there is a MergeOperation present

### ISSUE THREAD

**Issue by lanespade** [spring-projects/spring-data-mongodb#4671]
### Summary
Running an aggregation pipeline to update multiple documents returns documents outside the MatchOperation after adding a MergeOperation.

Java Sync Driver Version: 4.11.1
Spring Data MongoDB Version: 3.4.18
Atlas Version: 7
MongoDB Type: Replica Set

### How to Reproduce

Insert 2 documents into a collection with a field having different values.

Run the following code...

```
final MatchOperation matchOperation = AggregationUpdate.match(Criteria.where("thatField").is("oneOfTheValues"));

final AggregationResults<CollaborationRequestRecord> aggregationResults = mongoTemplate.aggregate(             
    AggregationUpdate.newUpdate(matchOperation),
    WhateverModel.class,
    WhateverModel.class
);

return aggregationResults.getMappedResults();
```

You should see 1 result getting returned.

Run the following code...

```
final MatchOperation matchOperation = AggregationUpdate.match(Criteria.where("thatField").is("oneOfTheValues")); 

final MergeOperation mergeOperation = AggregationUpdate.merge()
    .intoCollection("whatever")
    .build();
 
final AggregationResults<CollaborationRequestRecord> aggregationResults = mongoTemplate.aggregate(         
    AggregationUpdate.newUpdate(matchOperation, mergeOperation),
    WhateverModel.class,
    WhateverModel.class );

return aggregationResults.getMappedResults();
```

You should see 2 results getting returned now even though 1 does not match.

Note that changing the MergeOperation's "whenNotMatched" nor "on" properties do not change anything.

### Additional Background
I am trying to execute a single query to update and return multiple documents.

**Comment by christophstrobl** [comment]
Please follow the guidelines outlined in the [MongoDB Documentation](https://www.mongodb.com/docs/manual/tutorial/update-documents-with-aggregation-pipeline/#updates-with-aggregation-pipeline) as it only allows certain pipeline stages.

**Comment by lanespade** [comment]
Thanks Chris, could you please help me understand more? Are you suggesting
a merge stage is unsupported? The operation works on the data in an
expected way, it’s just the results that are unexpected.

**Comment by mp911de** [comment]
Cross-link to the original issue created in MongoDB Jira: https://jira.mongodb.org/browse/JAVA-5378
