### ISSUE TITLE
Disable auditable fields on query basis 

### ISSUE THREAD

**Issue by mipo256** [spring-projects/spring-data-mongodb#4682]
### The Problem

There is an interesting predicament our team encountered in our project.

Normally, our entities extend the common abstract entity, that has some auditable fields, annotated with auditable annotations from spring-data-commons. So it looks something like this:

```
public abstract class AbstractEntity {
  @CreatedDate
  private U createdAt;

  @LastModifiedDate
  private U updatedAt;

  @CreatedBy
  private T createdBy;

  @LastModifiedBy
  private T updatedBy;
}
```
And it works great. Most of the time we really need this fields to be set when we insert a new entity. Now, assume we have an entity `A`, that extends `AbstractEntity`. Entity `A` also needs auditable fields to be populated.

But apparently, we have just one query that inserts new `A` entity document into the collection, and in that particular query we do not want to set any auditable annotations. Notice that for other insert methods of `A` we want to populate auditable fields, but for one particular query - we do not. I've not found any way to achieve this using some standard framework technics.    

### Suggestion:

I think that here, we can consider adding new annotation, like `@AuditConfig` that will have attributes like `enableCreatedDate`, `enableCreatedBy` etc. That way, we'll be able to customize the auditing not just for our case, but for an even tricker problem that might occur later (when for instance we would want to only omit `@CreatedBy`, and not the other stuff)

P.S: It also seems to make sense to introduce a new annotation in common, since this problem seems to be a more general one, it is not strictly related to MongoDB per se.

**Comment by mp911de** [comment]
Auditing fields are updated in `AuditingEntityCallback` which is a `BeforeConvertCallback`. Using a `BeanPostProcessor` (or registering infrastructure beans yourself), you could wrap `AuditingEntityCallback` in your own callback and apply auditing based on the object/collection yourself.

Alternatively, you can convert the object into `Document` using `MongoConverter` and insert the resulting `Document` via `MongoTemplate.insert(…)` to bypass any model-specific actions that would be otherwise in place if you passed the original object into `MongoTemplate.insert(…)`.

Let me know whether this helps.

**Comment by mipo256** [comment]
Thanks for the reply! 
I honestly do not view implementing our own `BeanPostPrcoessor` and callback wrapping as an easy solution. That is doable, I understand, but it seems that framework can hide this complexity. 
Converting an entity to a `Document` is not that great since we seem to lose other things like callbacks for given entity (not for `Document`), version inspection etc.

So, I personally think that this is more like a workaround, but not a solution.

**Comment by mp911de** [comment]
We never intended to have conditional auditing hence there's no other way to make auditing conditional. As we do not plan on adding such a feature, I'm closing the ticket.
