### ISSUE TITLE
`$all` on `_id` leads to Exception if Collection with one element is passed

### ISSUE THREAD

**Issue by YuriiAndreitsev** [spring-projects/spring-data-mongodb#4736]
if one element in Collection is passed in .all() criteria it is not preserved as array in spring-data-mongodb higher that 4.3.0

![image](https://github.com/spring-projects/spring-data-mongodb/assets/53789299/d5ee1290-c616-4189-8b53-d04fa308c405)

![image](https://github.com/spring-projects/spring-data-mongodb/assets/53789299/df0f66c7-3cb1-4f90-b14c-42cdca61749c)

**Comment by christophstrobl** [comment]
Thank you for getting in touch. Please do not upload images but take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem. Thank you!

**Comment by christophstrobl** [comment]
Thank you @YuriiAndreitsev - I was able to reproduce the issue. We'll have a closer look!
