### ISSUE TITLE
Why Spring Data MongoDB doesn't support cascade save for fields annotated with `@DBRef` or `@DocumentReference`?

### ISSUE THREAD

**Issue by yuezk** [spring-projects/spring-data-mongodb#4775]
Hi Team,

I'm new to Spring Data MongoDB and found that the cascade save is not supported in Spring Data MongoDB, as [highlighted](https://docs.spring.io/spring-data/mongodb/reference/mongodb/mapping/document-references.html#:~:text=The%20mapping%20framework%20does%20not%20handle%20cascading%20saves.%20If%20you%20change%20an%20Account%20object%20that%20is%20referenced%20by%20a%20Person%20object%2C%20you%20must%20save%20the%20Account%20object%20separately.%20Calling%20save%20on%20the%20Person%20object%20does%20not%20automatically%20save%20the%20Account%20objects%20in%20the%20accounts%20property.) in the documentation.

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/fbbf5f08-0d1b-4638-870c-cd77f9bb0582">

I did some research and found that there is a workaround to achieve this and lots of questions and answers on this topic.

- [Custom Cascading in Spring Data MongoDB](https://www.baeldung.com/cascading-with-dbref-and-lifecycle-events-in-spring-data-mongodb)
- [Spring Data MongoDB cascade save on DBRef objects](https://www.javacodegeeks.com/2013/11/spring-data-mongodb-cascade-save-on-dbref-objects.html)

It looks like this is a common requirement and people are looking for a solution.

I also found a closed issue in this repo, which has been moved to backlog but not planned.

- #1377

So, I'm curious to know if there is any plan to support cascade save in Spring Data MongoDB in the future. Or is there any specific reason why it is not supported?

Thanks in advance.

**Comment by mp911de** [comment]
Spring Data conceptually builds on Aggregates in the sense of Domain-Driven design. An aggregate is valid in itself with all nested data structures.

MongoDB documents are a great match for aggregates as documents are hierarchical, updates to documents are atomic.

Outgoing references such as `DBRef` and `DocumentReference` are utilities to link to other aggregates. In an aggregate-oriented approach, working on one aggregate (e.g. persisting it) should never affect a different aggregate. 

That being said, we do not intend having cascading operations as that doesn't match the programming model we want to support.
