### ISSUE TITLE
Doubt about compatibility Matrix in doc

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-mongodb#4785]
Hi

Checking the [compatibility matrix](https://docs.spring.io/spring-data/mongodb/reference/preface.html#compatibility.matrix), I don't know if there is a possible typo. 

![image](https://github.com/user-attachments/assets/7572bca8-40c5-45c1-91df-e038bbe7fd31)

I see that spring-data-mongdodb 4.1.x supports server version 7.0 but spring-data-mongdodb 4.3.x supports server version 6.0.

Is there a typo or are there features that mongo server 7.0 supports in 4.1.x but not in 4.3.x?

Thank you very much

**Comment by christophstrobl** [comment]
thank you @jorgerod - yeah, that's a mistake. Overall I think we should update the matrix to define a range of tested versions.
