### ISSUE TITLE
MongoTemplate performance issue during call to find()

### ISSUE THREAD

**Issue by clucacicerqlar** [spring-projects/spring-data-mongodb#4846]
While using spring-data-mongodb version 4.2.12, Ive noticed that MongoTemplate during a call to find/doFind also performs `getMappedSortObject` using the original `query` object. The resulting variable `mappedSort` is also not even used if `isDebugEnabled` is FALSE. 

In some cases, this call to getMappedSortObject ends creating lots of PropertyReferenceException which end up calling Throwable fillInStackTrace and perform native/synchronized code so lot of time spent for no reason building stack traces?

**Comment by christophstrobl** [comment]
Thank you @clucacicerqlar. The `4.2.x` line is already out of OSS support. 
If the problem exists on more recent versions please provide us with a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem and maybe some flame graphs or other data that help us understand the issue better.

**Comment by clucacicerqlar** [comment]
hi @christophstrobl thank you for the reply, indeed the issue is there even in the latest versions, see below.

https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoTemplate.java#L2596C12-L2596C22

RE sample, you can see above, its problem is pretty easy to spot. the variable `Document mappedSort` is never used, in the below IF, and neither in the return function call. 

RE flamegraph, in my particular case, it was unable to find 3 fields, so you can see the native code red/yellow being called 3 times, each time using synchronised/native code. 

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/429f778b-8dbc-4acd-b57f-5665471b5a59">

**Comment by christophstrobl** [comment]
thank you @clucacicerqlar for bringing this to our attention!

**Comment by christophstrobl** [comment]
Getting rid of the `PropertyReferenceException` is long overdue, so thank you for giving us another nudge in that direction. We've opened spring-projects/spring-data-commons#3220 to capture ideas and flesh out details.

For now, we'll make sure the additional sort mapping happens only if debug logging is turned on.
