### ISSUE TITLE
Creating IndexOptions using expireAfter method sets wrong options

### ISSUE THREAD

**Issue by mozzer39** [spring-projects/spring-data-mongodb#4851]
Hi!
I have noticed a bug in `IndexOptions` class. Using `expireAfter(Duration duration)` method should set `expire` field with given expiration time, but `duration` parameter is not used and `unique` option is set instead.

https://github.com/spring-projects/spring-data-mongodb/blob/f910839dcad0e0293186af18308317e387dc5038/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/index/IndexOptions.java#L86-L91

**Comment by christophstrobl** [comment]
Now that is something. Thank you @mozzer39 for reporting the issue. We'll get that fixed!
